import { fetch as uniswap } from "../../DefiLlama-Adapters/projects/uniswap";
import { fetch as oneinch } from "../../DefiLlama-Adapters/projects/1inch.js";
import { fetch as aave } from "../../DefiLlama-Adapters/projects/aave.js";
import { fetch as acryptos } from "../../DefiLlama-Adapters/projects/acryptos.js";
import { fetch as alchemix } from "../../DefiLlama-Adapters/projects/alchemix.js";
import { fetch as augur } from "../../DefiLlama-Adapters/projects/augur.js";
import { fetch as autofarm } from "../../DefiLlama-Adapters/projects/autofarm.js";
import { fetch as badgerdao } from "../../DefiLlama-Adapters/projects/badgerdao.js";
import { fetch as balancer } from "../../DefiLlama-Adapters/projects/balancer.js";
import { fetch as barnbridge } from "../../DefiLlama-Adapters/projects/barnbridge.js";
import { fetch as basiscash } from "../../DefiLlama-Adapters/projects/basis-cash.js";
import { fetch as bella } from "../../DefiLlama-Adapters/projects/bella.js";
import { fetch as boringdao } from "../../DefiLlama-Adapters/projects/boringdao.js";
import { fetch as bprotocol } from "../../DefiLlama-Adapters/projects/b-protocol.js";
import { fetch as btfinance } from "../../DefiLlama-Adapters/projects/bt-finance.js";
import { fetch as bzx } from "../../DefiLlama-Adapters/projects/bzx.js";
import { fetch as cofix } from "../../DefiLlama-Adapters/projects/cofix.js";
import { fetch as compound } from "../../DefiLlama-Adapters/projects/compound.js";
import { fetch as cover } from "../../DefiLlama-Adapters/projects/cover.js";
import { fetch as cream } from "../../DefiLlama-Adapters/projects/cream.js";
import { fetch as curve } from "../../DefiLlama-Adapters/projects/curve.js";
import { fetch as defichain } from "../../DefiLlama-Adapters/projects/defichain.js";
import { fetch as defidollar } from "../../DefiLlama-Adapters/projects/defidollar.js";
import { fetch as defisaver } from "../../DefiLlama-Adapters/projects/defisaver.js";
import { fetch as demex } from "../../DefiLlama-Adapters/projects/demex.js";
import { fetch as deversifi } from "../../DefiLlama-Adapters/projects/deversifi.js";
import { fetch as devprotocol } from "../../DefiLlama-Adapters/projects/dev.js";
import { fetch as dhedge } from "../../DefiLlama-Adapters/projects/dhedge.js";
import { fetch as dodo } from "../../DefiLlama-Adapters/projects/dodo.js";
import { fetch as dpi } from "../../DefiLlama-Adapters/projects/dpi.js";
import { fetch as dracula } from "../../DefiLlama-Adapters/projects/dracula.js";
import { fetch as energiswap } from "../../DefiLlama-Adapters/projects/energiswap.js";
import { fetch as fantom } from "../../DefiLlama-Adapters/projects/fantom.js";
import { fetch as finnexus } from "../../DefiLlama-Adapters/projects/finnexus.js";
import { fetch as flamincome } from "../../DefiLlama-Adapters/projects/flamincome.js";
import { fetch as flexa } from "../../DefiLlama-Adapters/projects/flexa.js";
import { fetch as fuse } from "../../DefiLlama-Adapters/projects/fuse.js";
import { fetch as gdao } from "../../DefiLlama-Adapters/projects/gdao.js";
import { fetch as goose } from "../../DefiLlama-Adapters/projects/goose.js";
import { fetch as growthdefi } from "../../DefiLlama-Adapters/projects/growth-defi.js";
import { fetch as hakka } from "../../DefiLlama-Adapters/projects/hakka.js";
import { fetch as hardprotocol } from "../../DefiLlama-Adapters/projects/hard.js";
import { fetch as harvest } from "../../DefiLlama-Adapters/projects/harvest.js";
import { fetch as hbtc } from "../../DefiLlama-Adapters/projects/hbtc.js";
import { fetch as hegic } from "../../DefiLlama-Adapters/projects/hegic.js";
import { fetch as idle } from "../../DefiLlama-Adapters/projects/idle.js";
import { fetch as imbtc } from "../../DefiLlama-Adapters/projects/imbtc.js";
import { fetch as incognito } from "../../DefiLlama-Adapters/projects/incognito.js";
import { fetch as indexed } from "../../DefiLlama-Adapters/projects/indexed.js";
import { fetch as kava } from "../../DefiLlama-Adapters/projects/kava.js";
import { fetch as keeperdao } from "../../DefiLlama-Adapters/projects/keeper-dao.js";
import { fetch as keep } from "../../DefiLlama-Adapters/projects/keep.js";
import { fetch as lido } from "../../DefiLlama-Adapters/projects/lido.js";
import { fetch as linkswap } from "../../DefiLlama-Adapters/projects/linkswap.js";
import { fetch as mantradao } from "../../DefiLlama-Adapters/projects/mantradao.js";
import { fetch as mushrooms } from "../../DefiLlama-Adapters/projects/mushrooms.js";
import { fetch as nerd } from "../../DefiLlama-Adapters/projects/n3rd.js";
import { fetch as onx } from "../../DefiLlama-Adapters/projects/onx.js";
import { fetch as opium } from "../../DefiLlama-Adapters/projects/opium.js";
import { fetch as pancakeswap } from "../../DefiLlama-Adapters/projects/pancake-swap.js";
import { fetch as pickle } from "../../DefiLlama-Adapters/projects/pickle.js";
import { fetch as piedao } from "../../DefiLlama-Adapters/projects/piedao.js";
import { fetch as rari } from "../../DefiLlama-Adapters/projects/rari.js";
import { fetch as raydium } from "../../DefiLlama-Adapters/projects/raydium.js";
import { fetch as ren } from "../../DefiLlama-Adapters/projects/ren.js";
import { fetch as sablier } from "../../DefiLlama-Adapters/projects/sablier.js";
import { fetch as saddle } from "../../DefiLlama-Adapters/projects/saddle.js";
import { fetch as serum } from "../../DefiLlama-Adapters/projects/serum.js";
import { fetch as shell } from "../../DefiLlama-Adapters/projects/shell.js";
import { fetch as siren } from "../../DefiLlama-Adapters/projects/siren.js";
import { fetch as smoothy } from "../../DefiLlama-Adapters/projects/smoothy.js";
import { fetch as snowswap } from "../../DefiLlama-Adapters/projects/snowswap.js";
import { fetch as strudel } from "../../DefiLlama-Adapters/projects/strudel.js";
import { fetch as swerve } from "../../DefiLlama-Adapters/projects/swerve.js";
import { fetch as synlev } from "../../DefiLlama-Adapters/projects/synlev.js";
import { fetch as synthetix } from "../../DefiLlama-Adapters/projects/synthetix.js";
import { fetch as thorchain } from "../../DefiLlama-Adapters/projects/thorchain.js";
import { fetch as tornado } from "../../DefiLlama-Adapters/projects/tornado-cash.js";
import { fetch as uma } from "../../DefiLlama-Adapters/projects/uma.js";
import { fetch as unagii } from "../../DefiLlama-Adapters/projects/unagii.js";
import { fetch as unitprotocol } from "../../DefiLlama-Adapters/projects/unit.js";
import { fetch as unslashed } from "../../DefiLlama-Adapters/projects/unslashed.js";
import { fetch as valuedefi } from "../../DefiLlama-Adapters/projects/valuedefi.js";
import { fetch as venus } from "../../DefiLlama-Adapters/projects/venus.js";
import { fetch as wanswap } from "../../DefiLlama-Adapters/projects/wanswap.js";
import { fetch as wbtc } from "../../DefiLlama-Adapters/projects/wbtc.js";
import { fetch as wepiggy } from "../../DefiLlama-Adapters/projects/wepiggy.js";
import { fetch as wingfinance } from "../../DefiLlama-Adapters/projects/wing.js";
import { fetch as xtoken } from "../../DefiLlama-Adapters/projects/xtoken.js";
import { fetch as yaxis } from "../../DefiLlama-Adapters/projects/yaxis.js";
import { fetch as zlot } from "../../DefiLlama-Adapters/projects/zlot.js";

// New adapters
import mph from "../../DefiLlama-Adapters/projects/88mph/index.js";
import yearn from "../../DefiLlama-Adapters/projects/yearn/index.js";
import alphaHomora from "../../DefiLlama-Adapters/projects/alpha-homora/index.js";
import auctus from "../../DefiLlama-Adapters/projects/auctus/index.js";
import bancor from "../../DefiLlama-Adapters/projects/bancor/index.js";
import connext from "../../DefiLlama-Adapters/projects/connext/index.js";
import core from "../../DefiLlama-Adapters/projects/core/index.js";
import creamswap from "../../DefiLlama-Adapters/projects/creamswap/index.js";
import ddex from "../../DefiLlama-Adapters/projects/ddex/index.js";
import definer from "../../DefiLlama-Adapters/projects/definer/index.js";
import defiswap from "../../DefiLlama-Adapters/projects/defi-swap/index.js";
import derivadex from "../../DefiLlama-Adapters/projects/derivadex/index.js";
import dextf from "../../DefiLlama-Adapters/projects/dextf/index.js";
import dforce from "../../DefiLlama-Adapters/projects/dforce/index.js";
import dydx from "../../DefiLlama-Adapters/projects/dydx/index.js";
import enzyme from "../../DefiLlama-Adapters/projects/enzyme/index.js";
import erasure from "../../DefiLlama-Adapters/projects/erasure/index.js";
import fortube from "../../DefiLlama-Adapters/projects/fortube/index.js";
import futureswap from "../../DefiLlama-Adapters/projects/futureswap/index.js";
import gnosis from "../../DefiLlama-Adapters/projects/gnosis/index.js";
import idex from "../../DefiLlama-Adapters/projects/idex/index.js";
import kyber from "../../DefiLlama-Adapters/projects/kyber/index.js";
import lightningNetwork from "../../DefiLlama-Adapters/projects/lightning-network/index.js";
import loopring from "../../DefiLlama-Adapters/projects/loopring/index.js";
import makerdao from "../../DefiLlama-Adapters/projects/maker/index.js";
import mcdex from "../../DefiLlama-Adapters/projects/mcdex/index.js";
import metronome from "../../DefiLlama-Adapters/projects/metronome/index.js";
import mstable from "../../DefiLlama-Adapters/projects/mstable/index.js";
import nexus from "../../DefiLlama-Adapters/projects/nexus/index.js";
import notional from "../../DefiLlama-Adapters/projects/notional/index.js";
import peakdefi from "../../DefiLlama-Adapters/projects/peakdefi/index.js";
import perlinx from "../../DefiLlama-Adapters/projects/perlinx/index.js";
import polygon from "../../DefiLlama-Adapters/projects/polygon/index.js";
import pooltogether from "../../DefiLlama-Adapters/projects/pooltogether/index.js";
import powerindex from "../../DefiLlama-Adapters/projects/powerindex/index.js";
import primitive from "../../DefiLlama-Adapters/projects/primitive/index.js";
import qian from "../../DefiLlama-Adapters/projects/qian/index.js";
import ray from "../../DefiLlama-Adapters/projects/ray/index.js";
import reflexer from "../../DefiLlama-Adapters/projects/reflexer/index.js";
import setProtocol from "../../DefiLlama-Adapters/projects/set-protocol/index.js";
import sfinance from "../../DefiLlama-Adapters/projects/sfinance/index.js";
import truefi from "../../DefiLlama-Adapters/projects/truefi/index.js";
import unitrade from "../../DefiLlama-Adapters/projects/unitrade/index.js";
import valueliquid from "../../DefiLlama-Adapters/projects/valueliquid/index.js";
import vesper from "../../DefiLlama-Adapters/projects/vesper/index.js";
import xdai from "../../DefiLlama-Adapters/projects/xdai/index.js";
import yfii from "../../DefiLlama-Adapters/projects/yfii/index.js";
import sushiswap from "../../DefiLlama-Adapters/projects/sushiswap/index.js";
import { fetch as secretNetwork } from "../../DefiLlama-Adapters/projects/scrt.js";
import { fetch as pangolin } from "../../DefiLlama-Adapters/projects/pangolin.js";
import jarvis from "../../DefiLlama-Adapters/projects/jarvis/index.js";
import forcedao from "../../DefiLlama-Adapters/projects/forcedao/index.js";
import stakedao from "../../DefiLlama-Adapters/projects/stakedao/index.js";
import basketdao from "../../DefiLlama-Adapters/projects/basketdao/index.js";
import { fetch as ellipsis } from "../../DefiLlama-Adapters/projects/ellipsis.js";
import { fetch as swipeswap } from "../../DefiLlama-Adapters/projects/swipeswap.js";
import { fetch as instadapp } from "../../DefiLlama-Adapters/projects/instadapp.js";

import { baseIconsUrl } from "../constants";


export interface Protocol {
  id: string;
  name: string;
  address: string;
  symbol: string;
  url: string;
  description: string;
  chain: string;
  logo: null | string;
  audits: null | string;
  audit_note: null;
  gecko_id: string;
  cmcId: string;
  category: string;
  tvlFunction: () => Promise<number>;
}

export default [
  {
    id: "1",
    name: "Uniswap",
    address: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    symbol: "UNI",
    url: "https://info.uniswap.org/",
    description:
      "A fully decentralized protocol for automated liquidity provision on Ethereum.\r\n",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "uniswap",
    cmcId: "7083",
    category: "Dexes",
    tvlFunction: uniswap,
  },
  {
    id: "2",
    name: "WBTC",
    address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    symbol: "WBTC",
    url: "https://wbtc.network/",
    description:
      "Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin.\r\nCompletely transparent. 100% verifiable. Community led.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/d2T9nXpn_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "wrapped-bitcoin",
    cmcId: "3717",
    category: "Assets",
    tvlFunction: wbtc,
  },
  {
    id: "3",
    name: "Curve",
    address: "0xD533a949740bb3306d119CC777fa900bA034cd52",
    symbol: "CRV",
    url: "https://curve.fi",
    description:
      "Curve is a decentralized exchange liquidity pool on Ethereum designed for extremely efficient stablecoin trading",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "curve-dao-token",
    cmcId: "6538",
    category: "Dexes",
    tvlFunction: curve,
  },
  {
    id: "111",
    name: "AAVE",
    address: "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
    symbol: "AAVE",
    url: "https://aave.com\r\n",
    description:
      "Aave is an Open Source and Non-Custodial protocol to earn interest on deposits and borrow assets",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "aave",
    cmcId: "7278",
    category: "Lending",
    tvlFunction: aave,
  },
  {
    id: "112",
    name: "Harvest Finance",
    address: "0xa0246c9032bC3A600820415aE600c6388619A14D",
    symbol: "FARM",
    url: "https://harvest.finance/",
    description: "Harvest automatically farms the highest yields in DeFi",
    chain: "Ethereum",
    logo: null,
    audits: "1",
    audit_note: null,
    gecko_id: "harvest-finance",
    cmcId: "6859",
    category: "Yield",
    tvlFunction: harvest,
  },
  {
    id: "113",
    name: "Yearn Finance",
    address: "0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e",
    symbol: "YFI",
    url: "https://yearn.finance/",
    description:
      "Yearn.finance is an aggregator service for decentralized finance (DeFi) investors, using automation to allow them to maximize profits from yield farming.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/X8fdf5p-_400x400.png`,
    audits: "1",
    audit_note: null,
    gecko_id: "yearn-finance",
    cmcId: "5864",
    category: "Yield",
    tvlFunction: yearn.tvl,
  },
  {
    id: "114",
    name: "Compound",
    address: "0xc00e94cb662c3520282e6f5717214004a7f26888",
    symbol: "COMP",
    url: "https://compound.finance",
    description:
      "Compound is an algorithmic, autonomous interest rate protocol built for developers, to unlock a universe of open financial applications.",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "compound-governance-token",
    cmcId: "5692",
    category: "Lending",
    tvlFunction: compound,
  },
  {
    id: "115",
    name: "Synthetix ",
    address: "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f",
    symbol: "SNX",
    url: "https://synthetix.io",
    description:
      "Synthetix is a derivatives liquidity protocol providing the backbone for derivatives trading in DeFi.",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "havven",
    cmcId: "2586",
    category: "Dexes",
    tvlFunction: synthetix,
  },
  {
    id: "116",
    name: "Balancer",
    address: "0xba100000625a3754423978a60c9317c58a424e3d",
    symbol: "BAL",
    url: "https://balancer.finance/",
    description:
      "Balancer is a protocol for programmable liquidity.\r\n\r\n\r\n",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "balancer",
    cmcId: "5728",
    category: "Dexes",
    tvlFunction: balancer,
  },
  {
    id: "117",
    name: "REN Protocol",
    address: "0xeb4c2781e4eba804ce9a9803c67d0893436bb27d",
    symbol: "renBTC",
    url: "https://renproject.io/",
    description:
      "Introducing RenVM, an open protocol providing access to inter-blockchain liquidity for all decentralized applications. Bring BTC, BCH and ZEC to your Ethereum app.",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "republic-protocol",
    cmcId: "2539",
    category: "Assets",
    tvlFunction: ren,
  },
  {
    id: "118",
    name: "MakerDAO",
    address: "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2",
    symbol: "MKR",
    url: "https://makerdao.com/",
    description:
      "Builders of Dai, a digital currency that can be used by anyone, anywhere.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zacb-9pN_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "maker",
    cmcId: "1518",
    category: "Minting",
    tvlFunction: uniswap,
  },
  {
    id: "119",
    name: "SushiSwap",
    address: "0x6b3595068778dd592e39a122f4f5a5cf09c90fe2",
    symbol: "SUSHI",
    url: "https://sushiswap.fi/",
    description:
      "A fully decentralized protocol for automated liquidity provision on Ethereum.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/jwiN1Fd2_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: "sushi",
    cmcId: "6758",
    category: "Dexes",
    tvlFunction: sushiswap.tvl,
  },
  {
    id: "120",
    name: "InstaDApp",
    address: null,
    symbol: "-",
    url: "https://instadapp.io/",
    description:
      "Aims to drive interoperability between protocols for power users and ease of development allowing developers of all stripes to start leveraging the full potential of Decentralised Finance.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/instadapp.jpg`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Services",
    tvlFunction: instadapp,
  },
  {
    id: "121",
    name: "CREAM Finance",
    address: "0x2ba592F78dB6436527729929AAf6c908497cB200",
    symbol: "CREAM",
    url: "https://cream.finance/",
    description: null,
    chain: "Ethereum",
    logo: null,
    audits: "3",
    audit_note: null,
    gecko_id: "cream",
    cmcId: "6193",
    category: "Lending",
    tvlFunction: cream,
  },
  {
    id: "122",
    name: "Nexus Mutual",
    address: "0xd7c49cee7e9188cca6ad8ff264c1da2e69d4cf3b",
    symbol: "NXM",
    url: "https://nexusmutual.io/",
    description:
      "Nexus Mutual offers decentralized cover against smart contract failure.\r\n",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "nexus",
    cmcId: "1103",
    category: "Insurance",
    tvlFunction: nexus.tvl,
  },
  {
    id: "123",
    name: "dForce",
    address: "0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0",
    symbol: "DF",
    url: "https://dforce.network/",
    description:
      "dForce network is an ecosystem of protocols aiming to be a full stack solution for DeFi.",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "dforce-token",
    cmcId: "4758",
    category: "Others",
    tvlFunction: dforce.tvl,
  },
  {
    id: "124",
    name: "KEEP Network",
    address: "0x8dAEBADE922dF735c38C80C7eBD708Af50815fAa",
    symbol: "KEEP",
    url: "https://tbtc.network/",
    description: "Deposit and redeem BTC in DeFi without intermediaries.",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "keep-network",
    cmcId: "5566",
    category: "Assets",
    tvlFunction: keep,
  },
  {
    id: "125",
    name: "mStable",
    address: "0xa3BeD4E1c75D00fa6f4E5E6922DB7261B5E9AcD2",
    symbol: "MTA",
    url: "https://mstable.org/",
    description:
      "mStable unites stablecoins, lending and swapping into one standard.",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "meta",
    cmcId: "5748",
    category: "Minting",
    tvlFunction: mstable.tvl,
  },
  {
    id: "126",
    name: "Loopring",
    address: "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd",
    symbol: "LRC",
    url: "https://loopring.org/#/",
    description: "Loopring is a zkRollup Exchange and Payment Protocol.",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "loopring",
    cmcId: "1934",
    category: "Dexes",
    tvlFunction: loopring.tvl,
  },
  {
    id: "127",
    name: "Kyber",
    address: "0xdd974d5c2e2928dea5f71b9825b8b646686bd200",
    symbol: "KNC",
    url: "https://kyber.network/",
    description:
      "Kyber Network is connecting the fragmented tokenized world by enabling instant and seamless transactions between platforms, ecosystems.",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "kyber-network",
    cmcId: "404",
    category: "Dexes",
    tvlFunction: kyber.tvl,
  },
  {
    id: "128",
    name: "Hegic",
    address: "0x584bC13c7D411c00c01A62e8019472dE68768430",
    symbol: "HEGIC",
    url: "https://www.hegic.co/ ",
    description:
      "Trade non-custodial options for profits or to hedge your positions.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/hegic.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "hegic",
    cmcId: "6929",
    category: "Options",
    tvlFunction: hegic,
  },
  {
    id: "129",
    name: "xDAI Stake",
    address: "0x0Ae055097C6d159879521C384F1D2123D1f195e6",
    symbol: "STAKE",
    url: "https://xdaichain.com/ ",
    description:
      "The first-ever USD stable blockchain and multi-chain staking token.\r\n",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "xdai-stake",
    cmcId: "5601",
    category: "Layer2",
    tvlFunction: xdai.tvl,
  },
  {
    id: "130",
    name: "imToken",
    address: "0x3212b29E33587A00FB1C83346f5dBFA69A458923",
    symbol: "imBTC",
    url: "https://token.im/",
    description:
      "imToken is an easy and secure digital wallet trusted by millions",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: "imbtc",
    cmcId: "5292",
    category: "Assets",
    tvlFunction: imbtc,
  },
  {
    id: "131",
    name: "BarnBridge",
    address: "0x0391D2021f89DC339F60Fff84546EA23E337750f",
    symbol: "BOND",
    url: "https://barnbridge.com/",
    description:
      "A fluctuations derivatives protocol for hedging yield sensitivity and market price.",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "barnbridge",
    cmcId: "7440",
    category: "Yield",
    tvlFunction: barnbridge,
  },
  {
    id: "132",
    name: "hBTC",
    address: "0x0316EB71485b0Ab14103307bf65a021042c6d380",
    symbol: "hBTC",
    url: "https://www.hbtc.finance/ ",
    description:
      "HBTC token aims to promote the growth of the decentralized marketplace by injecting Bitcoin (BTC), the largest and most liquid asset, into the decentralized finance (DeFi) eco-system.",
    chain: "Ethereum",
    logo: null,
    audits: "0",
    audit_note: null,
    gecko_id: "huobi-btc",
    cmcId: "478",
    category: "Assets",
    tvlFunction: hbtc,
  },
  {
    id: "133",
    name: "Shell Protocol",
    address: null,
    symbol: "-",
    url: "https://www.shellprotocol.io/",
    description:
      "Deposit your stablecoins into our liquidity pool and receive shells, a natively liquid, diversified and yield bearing asset.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/FR750pnZ_400x400.jpg`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: shell,
  },
  {
    id: "134",
    name: "Pickle",
    address: "0x429881672B9AE42b8EbA0E26cD9C73711b891Ca5",
    symbol: "PICKLE",
    url: "https://pickle.finance/",
    description:
      "The Pickle protocol uses farming incentives, vaults, and governance to bring stablecoins closer to their pegs.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/439Roxx3_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: pickle,
  },
  {
    id: "135",
    name: "Kava",
    address: null,
    symbol: "KAVA",
    url: "https://www.kava.io/",
    description:
      "Kava.io is the first cross-chain DeFi hub providing applications and services to the worlds largest cryptocurrencies.",
    chain: "Multi-Chain",
    logo: `${baseIconsUrl}/ECfmsFee_400x400.png`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: kava,
  },
  {
    id: "136",
    name: "Rari Capital",
    address: "0xD291E7a03283640FDc51b121aC401383A46cC623",
    symbol: "RGT",
    url: "https://rari.capital/",
    description:
      "Rari Capital aims to deliver the best yield to all users with various risk tolerances. Easy, sustainable and built for the future.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ZyleKD4B_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: rari,
  },
  {
    id: "137",
    name: "Thorchain",
    address: null,
    symbol: "RUNE",
    url: "https://thorchain.org/",
    description:
      "THORChain facilitates cross-chain liquidity pools with no pegged or wrapped tokens.",
    chain: "Binance",
    logo: `${baseIconsUrl}/p1ecyvxG_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: thorchain,
  },
  {
    id: "138",
    name: "Hakka Finance",
    address: "0x0E29e5AbbB5FD88e28b2d355774e73BD47dE3bcd",
    symbol: "HAKKA",
    url: "https://hakka.finance/",
    description:
      "Hakka Decentralized Finance Ecosystem Warped Spacetime with Crypto Native Primitives.",
    chain: "Ethereum",
    logo: null,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: hakka,
  },
  {
    id: "139",
    name: "SnowSwap",
    address: "0xfe9A29aB92522D14Fc65880d817214261D8479AE",
    symbol: "SNOW",
    url: "https://snowswap.org/",
    description:
      "SnowSwap is designed for low slippage stablecoin swaps and is based on Curve's AMM.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/oWZl3IYr_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: snowswap,
  },
  {
    id: "140",
    name: "Hard Protocol",
    address: null,
    symbol: "HARD",
    url: "https://hard.kava.io/",
    description:
      "Cross-chain money market. Lend, borrow, and earn with your crypto.\r\n",
    chain: "Multi-Chain",
    logo: `${baseIconsUrl}/qv-OI4YK_400x400.png`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: null,
    tvlFunction: hardprotocol,
  },
  {
    id: "141",
    name: "UMA Protocol",
    address: "0x04Fa0d235C4abf4BcF4787aF4CF447DE572eF828",
    symbol: "UMA",
    url: "https://umaproject.org/",
    description: "A Protocol for Building Synthetic Assets",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Minting",
    tvlFunction: uma,
  },
  {
    id: "142",
    name: "Swerve",
    address: "0xB8BAa0e4287890a5F79863aB62b7F175ceCbD433",
    symbol: "SWRV",
    url: "https://swerve.fi/",
    description:
      "Swerve is a community fork of curve.fi designed for efficient stablecoin trading.",
    chain: "Ethereum",
    logo: null,
    audits: "3",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: swerve,
  },
  {
    id: "143",
    name: "Flexa",
    address: "0xff20817765cb7f73d4bde2e66e067e58d11095c2",
    symbol: "AMP",
    url: "https://amptoken.org/",
    description: "Collateral for fast and efficient value transfer",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/flexa.png_small`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: null,
    tvlFunction: flexa,
  },
  {
    id: "144",
    name: "dYdX",
    address: null,
    symbol: "-",
    url: "https://dydx.exchange/",
    description:
      "The most powerful open trading platform for crypto assets. Margin trade, borrow, and lend cryptocurrency.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/-m722G1f_400x400.jpg`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: dydx.tvl,
  },
  {
    id: "145",
    name: "Serum",
    address: null,
    symbol: "SRM",
    url: "https://projectserum.com/",
    description:
      "Serum is a decentralized exchange (DEX) and ecosystem that brings unprecedented speed and low transaction costs to decentralized finance.",
    chain: "Solana",
    logo: `${baseIconsUrl}/9yyO0Klj_400x400.jpg`,
    audits: null,
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: serum,
  },
  {
    id: "146",
    name: "DODO",
    address: "0x43Dfc4159D86F3A37A5A4B3D4580b888ad7d4DDd",
    symbol: "DODO",
    url: "https://dodoex.io/",
    description: "Trade crypto assets with market-leading liquidity",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/wG29L0wM_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: dodo,
  },
  {
    id: "148",
    name: "Tornado Cash",
    address: null,
    symbol: "-",
    url: "https://tornado.cash/",
    description: "Non-custodial anonymous transactions on Ethereum.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ZINt8NSB_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Services",
    tvlFunction: tornado,
  },
  {
    id: "149",
    name: "B.Protocol",
    address: "",
    symbol: "-",
    url: "https://www.bprotocol.org/",
    description:
      "B.Protocol makes lending platforms more secure by eliminating the gas wars and shifting the miner’s profit to the users.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/jPH5weGQ_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: bprotocol,
  },
  {
    id: "150",
    name: "Idle Finance",
    address: "0x875773784Af8135eA0ef43b5a374AaD105c5D39e",
    symbol: "IDLE",
    url: "https://idle.finance",
    description:
      "Choose your strategy and earn the yield you deserve without worry about finding the best option, either if you want to optimize returns or risks.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/BiCdsrIH_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: idle,
  },
  {
    id: "151",
    name: "DeversiFi",
    address: "0xcc80c051057b774cd75067dc48f8987c4eb97a5e",
    symbol: "NEC",
    url: "https://www.deversifi.com/",
    description:
      "DeversiFi gives traders ​the edge​ in fast moving decentralised finance (DeFi) markets by allowing them to ​trade at lightning speed​ and ​with deep aggregated liquidity​, directly from their privately owned cryptocurrency wallet.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/WC8lhLs5_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: deversifi,
  },
  {
    id: "152",
    name: "Augur",
    address: "0x221657776846890989a759ba2973e427dff5c9bb",
    symbol: "REP",
    url: "https://www.augur.net/",
    description:
      "A transparent exchange with no limit on what you can bet on, no max limits on the amount you can bet and no rollover requirements.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/gHlsZLWU_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: augur,
  },
  {
    id: "153",
    name: "CoFiX",
    address: "0x1a23a6bfbadb59fa563008c0fb7cf96dfcf34ea1",
    symbol: "COFI",
    url: "https://cofix.io",
    description: "CoFiX is the most efficient DEX on Ethereum.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/dnPnSkfa_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: cofix,
  },
  {
    id: "155",
    name: "KeeperDAO",
    address: "0xfA5047c9c78B8877af97BDcb85Db743fD7313d4a",
    symbol: "ROOK",
    url: "https://keeperdao.com/",
    description: "KeeperDAO is an on-chain liquidity underwriter for DeFi.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/z8n7Rb13_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: keeperdao,
  },
  {
    id: "156",
    name: "zLot",
    address: "0xA8e7AD77C60eE6f30BaC54E2E7c0617Bd7B5A03E",
    symbol: "zLot",
    url: "https://zlot.finance/",
    description: "The first staking protocol built upon Hegic.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/OS3WBPFJ_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: zlot,
  },
  {
    id: "157",
    name: "88mph",
    address: "0x8888801af4d980682e47f1a9036e589479e835c5",
    symbol: "MPH",
    url: "https://88mph.app/",
    description: "Earn fixed-rate interest on your crypto.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/yfU-_Tcj_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: mph.tvl,
  },
  {
    id: "158",
    name: "Dracula",
    address: "0xb78B3320493a4EFaa1028130C5Ba26f0B6085Ef8",
    symbol: "DRC",
    url: "https://dracula.sucks/",
    description:
      "Meta-level vampirism concept implemented in Dracula protocol delivers higher profits while mitigating those risks.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zDPmiv40_400x400.png`,
    audits: "2",
    audit_note: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: dracula,
  },
  {
    id: "159",
    name: "Growth DeFi",
    address: "0x09e64c2B61a5f1690Ee6fbeD9baf5D6990F8dFd0",
    symbol: "GRO",
    url: "https://growthdefi.com/",
    description:
      "gToken holders can benefit from the positive effects of compounded interest, high liquidity and a share of arbitragers profit without suffering from impermanent loss.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ijnFH9ZE_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: growthdefi,
  },
  {
    id: "160",
    name: "Alpha Finance",
    address: "0xa1faa113cbe53436df28ff0aee54275c13b40975",
    symbol: "ALPHA",
    url: "https://alphafinance.io/",
    description:
      "Alpha Finance Lab is an ecosystem of cross-chain DeFi products that focus on capturing unaddressed demand in an innovative and user friendly way. Alpha Homora, the first product, is a leveraged yield farming and leveraged liquidity providing protocol where ETH lenders can earn high lending interest rate and leveraged yield farmers/liquidity providers can increase the APY.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/eMgmyBiA_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: alphaHomora.tvl,
  },
  {
    id: "161",
    name: "BoringDAO",
    address: "0x3c9d6c1c73b31c837832c72e04d3152f051fc1a9",
    symbol: "BOR",
    url: "https://www.boringdao.com/",
    description:
      "BoringDAO is a decentralized bridge that connects all blockchain assets, we offer users a safe way to maximize their utilization rate of crypto assets.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/irryNMYm_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Minting",
    tvlFunction: boringdao,
  },
  {
    id: "162",
    name: "Bancor",
    address: "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
    symbol: "BNT",
    url: "https://app.bancor.network/",
    description:
      "Bancor is an on-chain liquidity protocol that enables automated, decentralized exchange on Ethereum and across blockchains.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/pKhMnarD_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: bancor.tvl,
  },
  {
    id: "163",
    name: "ForTube",
    address: "0x1fcdce58959f536621d76f5b7ffb955baa5a672f",
    symbol: "FOR",
    url: "https://for.tube/",
    description:
      "Based on The Force Protocol, ForTube is committed to providing decentralized lending services for cryptoasset enthusiasts around the world.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/EJnnBDeZ_400x400.jpg`,
    audits: "4",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: fortube.tvl,
  },
  {
    id: "164",
    name: "ValueDefi",
    address: "0x49e833337ece7afe375e44f4e3e8481029218e5c",
    symbol: "VALUE",
    url: "https://valuedefi.io/",
    description:
      "The Value DeFi protocol is a platform and suite of products that aim to bring fairness, true value, and innovation to Decentralized Finance.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/jN72Swyu_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: valuedefi,
  },
  {
    id: "165",
    name: "Cover Protocol",
    address: "0x5d8d9f5b96f4438195be9b99eee6118ed4304286",
    symbol: "COVER",
    url: "https://www.coverprotocol.com/",
    description: "A peer-to-peer coverage market.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/1VPyoo_r_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Insurance",
    tvlFunction: cover,
  },
  {
    id: "166",
    name: "TrueFi",
    address: "0x4c19596f5aaff459fa38b0f7ed92f11ae6543784",
    symbol: "TRU",
    url: "https://truefi.io/",
    description:
      "Earn high yields on stablecoin loans and borrow capital without collateral",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/4kwLEUTx_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: truefi.tvl,
  },
  {
    id: "167",
    name: "PieDAO",
    address: "0xad32A8e6220741182940c5aBF610bDE99E737b2D",
    symbol: "DOUGH",
    url: "https://www.piedao.org/",
    description:
      "PieDAO is the decentralized community building ETF products known as pies. Their offerings provide diversified exposure to both DEFI and the wider cryptocurrency ecosystem, with baskets of tokens automatically rebalancing to maintain set allocations. All decisions are made as a community, with members using the DOUGH token to vote on proposals. DOUGH also provides holders with a share of the fees generated by the DAO's products. The platform aims to simplify decentralized finance with automation and minimize risk with diversified portfolios reducing exposure to any one single asset.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/4Qb2jwin_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    tvlFunction: piedao,
  },
  {
    id: "168",
    name: "Dev Protocol",
    address: "0x5caf454ba92e6f2c929df14667ee360ed9fd5b26",
    symbol: "DEV",
    url: "https://devprtcl.com/",
    description: "Making open activities sustainable with staking\r\n\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/08leXwpT_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: null,
    tvlFunction: devprotocol,
  },
  {
    id: "169",
    name: "Basis Cash",
    address: "0x3449fc1cd036255ba1eb19d65ff4ba2b8903a69a",
    symbol: "BAC",
    url: "https://basis.cash/",
    description:
      "Basis Cash is a censorship-resistant and fairly distributed implementation of the Basis Protocol.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/2_vq9Ovq_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Assets",
    tvlFunction: basiscash,
  },
  {
    id: "170",
    name: "FinNexus",
    address: "0xef9cd7882c067686691b6ff49e650b43afbbcc6b",
    symbol: "FNX",
    url: "https://finnexus.io/",
    description:
      "FinNexus Options makes it easy to buy and exercise BTC, ETH, LINK, SNX, and MKR options in a secure and decentralized way on Ethereum & Wanchain.",
    chain: "Multi-Chain",
    logo: `${baseIconsUrl}/fShXtXh-_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Options",
    tvlFunction: finnexus,
  },
  {
    id: "171",
    name: "SynLev",
    address: "0x1695936d6a953df699c38ca21c2140d497c08bd9",
    symbol: "SYN",
    url: "https://synlev.com/",
    description: "DeFi synthetic leveraged asset tokens.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ckvE1JTJ_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: null,
    tvlFunction: synlev,
  },
  {
    id: "172",
    name: "Index Coop",
    address: "0x0954906da0Bf32d5479e25f46056d22f08464cab",
    symbol: "INDEX",
    url: "https://www.indexcoop.com/",
    description:
      "Index Coop creates and maintains the world's best crypto index products.\r\n\r\nAll index products are always fully collateralized.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/c7w3TmXs_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "index-cooperative",
    cmcId: "7336",
    category: "Indexes",
    tvlFunction: dpi,
  },
  {
    id: "173",
    name: "Badger DAO",
    address: "0x3472A5A71965499acd81997a54BBA8D852C6E53d",
    symbol: "BADGER",
    url: "https://badger.finance/",
    description:
      "DAO dedicated to building products and infrastructure to bring Bitcoin to DeFi.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/3_dd6SJB_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: badgerdao,
  },
  {
    id: "174",
    name: "BT.Finance",
    address: "0x76c5449f4950f6338a393f53cda8b53b0cd3ca3a",
    symbol: "BT",
    url: "https://bt.finance/",
    description:
      "The best and sustainable yield from other excellent DeFi yield aggregator and platforms.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/cOYS4CCl_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: btfinance,
  },
  {
    id: "175",
    name: "N3RD Finance",
    address: "0x32c868f6318d6334b2250f323d914bc2239e4eee",
    symbol: "N3RDz",
    url: "https://n3rd.finance/",
    description: "High Yield, Deflationary Farming.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ChNmBBtq_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: nerd,
  },
  {
    id: "176",
    name: "Mushrooms Finance",
    address: "0xa283aa7cfbb27ef0cfbcb2493dd9f4330e0fd304",
    symbol: "MM",
    url: "https://www.mushrooms.finance/",
    description:
      "Mushrooms Finance is yet another crypto earning vault with focus on seeking sustainable profit in DeFi universe",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/tkO-K5_1_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: mushrooms,
  },
  {
    id: "177",
    name: "DefiSaver",
    address: null,
    symbol: "-",
    url: "https://defisaver.com/",
    description:
      "DeFi Saver is a one-stop management solution for decentralized finance with advanced leverage management tools and unique automated management features.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/VDvnjUE7_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: null,
    tvlFunction: defisaver,
  },
  {
    id: "178",
    name: "DefiChain",
    address: null,
    symbol: "DFI",
    url: "https://defichain.com/",
    description:
      "A blockchain dedicated to fast, intelligent and transparent financial services, accessible by everyone.",
    chain: "DefiChain",
    logo: `${baseIconsUrl}/nQdI8k_n_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    tvlFunction: defichain,
  },
  {
    id: "179",
    name: "YF Link",
    address: "0x28cb7e841ee97947a86B06fA4090C8451f64c0be",
    symbol: "YFL",
    url: "https://yflink.io/",
    description:
      "LINKSWAP is an Automated Market Maker focused on empowering the Chainlink community.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/KRddVLzb_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: linkswap,
  },
  {
    id: "180",
    name: "Demex",
    address: null,
    symbol: "-",
    url: "https://app.dem.exchange/",
    description:
      "The first fully decentralized DEX that supports any type of financial market.\r\n",
    chain: "Tradehub",
    logo: `${baseIconsUrl}/2rOYmzj7_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: demex,
  },
  {
    id: "181",
    name: "MANTRA DAO",
    address: "0x3593d125a4f7849a1b059e64f4517a86dd60c95d",
    symbol: "OM",
    url: "https://mantradao.com",
    description:
      "Mantra DAO leverages the wisdom of the crowd to give financial control back to the people to grow wealth together.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/l2RmvEyc_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: null,
    tvlFunction: mantradao,
  },
  {
    id: "182",
    name: "Lido",
    address: "0x5a98fcbea516cf06857215779fd812ca3bef1b32",
    symbol: "LDO",
    url: "https://www.lido.fi/",
    description:
      "Stake your ETH with Lido and receive liquid stETH with daily rewards.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/pGDedFg0_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Staking",
    tvlFunction: lido,
  },
  {
    id: "183",
    name: "Wing Finance",
    address: null,
    symbol: "WING",
    url: "https://wing.finance",
    description: "A Credit-based, cross-chain DeFi Platform.",
    chain: "Ontology",
    logo: `${baseIconsUrl}/unlUa5-__400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: wingfinance,
  },
  {
    id: "184",
    name: "Fuse",
    address: "0x970b9bb2c0444f5e81e9d0efb84c8ccdcdcaf84d",
    symbol: "FUSE",
    url: "https://fuse.io/",
    description:
      "Bringing the power of open-source money to millions globally. ",
    chain: "Multi-Chain",
    logo: `${baseIconsUrl}/s-SdhVYj_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    tvlFunction: fuse,
  },
  {
    id: "186",
    name: "WanSwap Dex",
    address: null,
    symbol: "WASP",
    url: "https://wanswap.finance/",
    description:
      "WanSwap is an innovative crosschain automatic market making (AMM) decentralized exchange (DEX) based on Wanchain.",
    chain: "Wanchain",
    logo: `${baseIconsUrl}/OWIhzGn8_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: wanswap,
  },
  {
    id: "187",
    name: "Unagii",
    address: null,
    symbol: "-",
    url: "https://www.unagii.com/",
    description: "The automated DeFi yield platform with staking services.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/YWZ68hSA_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: unagii,
  },
  {
    id: "188",
    name: "Indexed Finance",
    address: "0x86772b1409b61c639eaac9ba0acfbb6e238e5f83",
    symbol: "NDX",
    url: "https://indexed.finance/",
    description:
      "Indexed Finance is a project focused on the development of passive portfolio management strategies for the Ethereum network.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/kIv5abLc_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    tvlFunction: indexed,
  },
  {
    id: "189",
    name: "1inch",
    address: "0x111111111117dc0aa78b770fa6a738034120c302",
    symbol: "1INCH",
    url: "https://1inch.exchange/",
    description:
      "1inch offers the best rates by discovering the most efficient swapping routes across all leading DEXes.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/JWXLyjdz_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: oneinch,
  },
  {
    id: "190",
    name: "dHEDGE",
    address: "0xca1207647ff814039530d7d35df0e1dd2e91fa84",
    symbol: "DHT",
    url: "https://www.dhedge.org/",
    description: "Decentralized Hedge Funds on Ethereum",
    chain: "Ethereum",
    logo: null,
    audits: "2",
    audit_note: null,
    gecko_id: "dhedge-dao",
    cmcId: null,
    category: null,
    tvlFunction: dhedge,
  },
  {
    id: "191",
    name: "Opium",
    address: "0x888888888889c00c67689029d7856aac1065ec11",
    symbol: "OPIUM",
    url: "https://www.opium.network/",
    description:
      "Opium is a universal and robust protocol\r\nthat allows for creating, settling, and trading any decentralised derivative.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/klVuCa_9_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "opium",
    cmcId: null,
    category: "Insurance",
    tvlFunction: opium,
  },
  {
    id: "192",
    name: "Governor DAO",
    address: "0x515d7E9D75E2b76DB60F8a051Cd890eBa23286Bc",
    symbol: "GDAO",
    url: "https://governordao.org/",
    description:
      "All projects can benefit from decentralized governance. Governor DAO aids new and existing projects alike in transitioning to a DAO via Governance-as-a-Service.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/RiFq-4pn_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "governor-dao",
    cmcId: null,
    category: null,
    tvlFunction: gdao,
  },
  {
    id: "193",
    name: "Unit Protocol",
    address: "0x92e187a03b6cd19cb6af293ba17f2745fd2357d5",
    symbol: "DUCK",
    url: "https://app.unit.xyz/",
    description:
      "Unit protocol is a decentralized borrowing protocol that allows you to mint USDP stablecoin using a variety of tokens as collateral.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/2mzps092_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "unit-protocol-duck",
    cmcId: null,
    category: "Minting",
    tvlFunction: unitprotocol,
  },
  {
    id: "194",
    name: "PancakeSwap",
    address: null,
    symbol: "CAKE",
    url: "https://pancakeswap.finance/",
    description: "The #1 AMM and yield farm on Binance Smart Chain",
    chain: "Binance",
    logo: `${baseIconsUrl}/c6z3sWsY_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "pancakeswap",
    cmcId: null,
    category: "Dexes",
    tvlFunction: pancakeswap,
  },
  {
    id: "195",
    name: "DefiDollar",
    address: "0x20c36f062a31865bed8a5b1e512d9a1a20aa333a",
    symbol: "DFD",
    url: "https://dusd.finance/",
    description:
      "DefiDollar ($DUSD) aspires to be a risk-insured stablecoin layer for DeFi.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/sm66LRyq_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "defidollar-dao",
    cmcId: null,
    category: "Minting",
    tvlFunction: defidollar,
  },
  {
    id: "196",
    name: "Fantom",
    address: "0x4e15361fd6b4bb609fa63c81a2be19d873717870",
    symbol: "FTM",
    url: "https://fantom.foundation/",
    description:
      "Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.",
    chain: "Multi-Chain",
    logo: `${baseIconsUrl}/ftm.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "fantom",
    cmcId: null,
    category: "Chains",
    tvlFunction: fantom,
  },
  {
    id: "197",
    name: "bZx",
    address: "0x56d811088235F11C8920698a204A5010a788f4b3",
    symbol: "BZRX",
    url: "https://bzx.network/",
    description:
      "Build applications that empower lenders, borrowers, and traders with the most flexible decentralized finance protocol on Ethereum.",
    chain: "Ethereum",
    logo: "",
    audits: "2",
    audit_note: null,
    gecko_id: "bzx-protocol",
    cmcId: "5810",
    category: "Lending",
    tvlFunction: bzx,
  },
  {
    id: "198",
    name: "Incognito Chain",
    address: null,
    symbol: "PRV",
    url: "https://incognito.org/",
    description: "A privacy sidechain with a uniswap-like DEX.",
    chain: "Incognito Chain",
    logo: `${baseIconsUrl}/qLuA-qr9_400x400.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "privacy",
    cmcId: null,
    category: "Chain",
    tvlFunction: incognito,
  },
  {
    id: "199",
    name: "Sablier Finance",
    address: null,
    symbol: "-",
    url: "https://sablier.finance/",
    description: "The protocol for real-time finance.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/nlJtmWT1_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    tvlFunction: sablier,
  },
  {
    id: "200",
    name: "Bella Protocol",
    address: "0xa91ac63d040deb1b7a5e4d4134ad23eb0ba07e14",
    symbol: "BEL",
    url: "https://fs.bella.fi/",
    description:
      "Bella Flex Savings v2 is a smart-mining DApp where users can deposit stablecoins and supported tokens to earn attractive yields instantly. ",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ICnkTmMk_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "bella-protocol",
    cmcId: "6928",
    category: "Yield",
    tvlFunction: bella,
  },
  {
    id: "202",
    name: "Saddle Finance",
    address: "-",
    symbol: "-",
    url: "https://saddle.finance/",
    description:
      "Saddle is an automated market maker for pegged value crypto assets.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/yXSXL3Je_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: saddle,
  },
  {
    id: "203",
    name: "Siren",
    address: "0xD23Ac27148aF6A2f339BD82D0e3CFF380b5093de",
    symbol: "SI",
    url: "https://sirenmarkets.com/",
    description: "Decentralized option markets on Ethereum.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/VjJauAOJ_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "siren",
    cmcId: "8701",
    category: "Options",
    tvlFunction: siren,
  },
  {
    id: "204",
    name: "Alchemix",
    address: "0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF",
    symbol: "ALCX",
    url: "https://alchemix.fi/",
    description:
      "Alchemix is a DeFi protocol that allows for the creation of synthetic tokens that represent the future yield of a deposit. It enables users to retrieve near instant tokenized value against temporary* deposits of stablecoins.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/uS04dyYy_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "alchemix",
    cmcId: "8613",
    category: "Yield",
    tvlFunction: alchemix,
  },
  {
    id: "205",
    name: "Goose Finance",
    address: "-",
    symbol: "EGG",
    url: "https://www.goosedefi.com/",
    description: "2nd generation yield farming on binance smart chain",
    chain: "Binance",
    logo: `${baseIconsUrl}/50GNpXNs_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "goose-finance",
    cmcId: "8449",
    category: "Yield",
    tvlFunction: goose,
  },
  {
    id: "206",
    name: "xToken",
    address: "0x7f3edcdd180dbe4819bd98fee8929b5cedb3adeb",
    symbol: "XTK",
    url: "https://xtoken.market/",
    description: "Passive, Efficient ERC20 Staking Strategies.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/IqAiIiw9_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "xtoken",
    cmcId: "8599",
    category: "Yield",
    tvlFunction: xtoken,
  },
  {
    id: "207",
    name: "Unslashed",
    address: "0xe0e05c43c097b0982db6c9d626c4eb9e95c3b9ce",
    symbol: "USF",
    url: "https://unslashed.finance/",
    description: "Decentralized insurance for major DeFi protocols",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/7oDWGjlb_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "unslashed-finance",
    cmcId: null,
    category: "Insurance",
    tvlFunction: unslashed,
  },
  {
    id: "208",
    name: "ACryptoS",
    address: null,
    symbol: "ACS",
    url: "https://app.acryptos.com/",
    description:
      "Advanced Crypto Strategies, Yield Optimizer and StableSwap on BSC.",
    chain: "Binance",
    logo: `${baseIconsUrl}/WFncAyhA_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "acryptos",
    cmcId: "7844",
    category: "Yield",
    tvlFunction: acryptos,
  },
  {
    id: "209",
    name: "Autofarm",
    address: "0xa184088a740c695e156f91f5cc086a06bb78b827",
    symbol: "AUTO",
    url: "https://autofarm.network/",
    description:
      "AutoFarm is a yield farming aggregator running on both Binance Smart Chain (BSC) and Huobi ECO chain (HECO)",
    chain: "Multi-Chain",
    logo: `${baseIconsUrl}/wz6Vh6VM_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "auto",
    cmcId: "8387",
    category: "Yield",
    tvlFunction: autofarm,
  },
  {
    id: "210",
    name: "yAxis",
    address: "0xb1dc9124c395c1e97773ab855d66e879f053a289",
    symbol: "YAX",
    url: "https://www.yaxis.io",
    description:
      "yAxis MetaVault v2 is an aggregator of yield aggregators, allowing crypto holders to earn interest on their assets through a versatile, multi-strategy vault.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zzRHMkND_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "yaxis",
    cmcId: "7222",
    category: "Yield",
    tvlFunction: yaxis,
  },
  {
    id: "211",
    name: "Smoothy",
    address: "-",
    symbol: "-",
    url: "https://smoothy.finance/",
    description:
      "Smoothy is a novel single pool liquidity protocol specialized in same backed assets with low-cost zero-slippage swapping and maximized interest earning.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/dDxKgwPN_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: smoothy,
  },
  {
    id: "212",
    name: "Venus",
    address: "0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63",
    symbol: "XVS",
    url: "https://venus.io/",
    description:
      "A Decentralized Marketplace for Lenders and Borrowers with Borderless Stablecoins.",
    chain: "Binance",
    logo: `${baseIconsUrl}/51QQ7Pj4_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "venus",
    cmcId: "7288",
    category: "Lending",
    tvlFunction: venus,
  },
  {
    id: "213",
    name: "OnX.Finance",
    address: "0xE0aD1806Fd3E7edF6FF52Fdb822432e847411033",
    symbol: "ONX",
    url: "https://onx.finance",
    description: "OnX Finance, the first DeFi hub for collateralized tokens.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/jSYPaL65_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "onx-finance",
    cmcId: "8071",
    category: "Lending",
    tvlFunction: onx,
  },
  {
    id: "214",
    name: "Raydium",
    address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    symbol: "RAY",
    url: "https://raydium.io",
    description: "An on-chain order book AMM powering the evolution of DeFi.",
    chain: "Solana",
    logo: `${baseIconsUrl}/5EXqzHKc_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "raydium",
    cmcId: "8526",
    category: "Dexes",
    tvlFunction: raydium,
  },
  {
    id: "215",
    name: "Strudel Finance",
    address: "0x297d33e17e61c2ddd812389c2105193f8348188a",
    symbol: "TRDL",
    url: "https://strudel.finance",
    description:
      "Strudel Finance provides the first one-way, trustless bridge linking Bitcoin and Ethereum.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/qr1swZ5r_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "strudel-finance",
    cmcId: "8390",
    category: "Assets",
    tvlFunction: strudel,
  },
  {
    id: "216",
    name: "Auctus",
    address: "0xc12d099be31567add4e4e4d0d45691c3f58f5663",
    symbol: "AUC",
    url: "https://auctus.org/",
    description: "Auctus brings on-chain options to the ecosystem.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/vCRHqgMD_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "auctus",
    cmcId: "2653",
    category: "Options",
    tvlFunction: auctus.tvl,
  },
  {
    id: "217",
    name: "Connext",
    address: "-",
    symbol: "-",
    url: "https://connext.network/",
    description: "Fast, non-custodial L1-L2 and cross-L2 communication.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ZSU1xz91_400x400.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Layer2",
    tvlFunction: connext.tvl,
  },
  {
    id: "218",
    name: "cVault.finance",
    address: "0x62359ed7505efc61ff1d56fef82158ccaffa23d7",
    symbol: "CORE",
    url: "https://cvault.finance/",
    description: "First high yield farmable deflationary DeFi token.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/SUA_ZSP5_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "cvault-finance",
    cmcId: "7242",
    category: "Assets",
    tvlFunction: core.tvl,
  },
  {
    id: "219",
    name: "DDEX",
    address: "-",
    symbol: "-",
    url: "https://ddex.io/",
    description:
      "A decentralized margin exchange built on Ethereum. Trade ETH and BTC with up to 5x leverage. Lend to earn interest.\r\n",
    chain: null,
    logo: `${baseIconsUrl}/Cd-ILEu6_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: ddex.tvl,
  },
  {
    id: "220",
    name: "Vesper",
    address: "0x1b40183efb4dd766f11bda7a7c3ad8982e998421",
    symbol: "VSP",
    url: "https://vesper.finance/",
    description: "Vesper is a platform for easy-to-use DeFi products.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/fixLEyWp_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "vesper-finance",
    cmcId: "8492",
    category: "Yield",
    tvlFunction: vesper.tvl,
  },
  {
    id: "221",
    name: "Defi Swap",
    address: "0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b",
    symbol: "CRO",
    url: "https://crypto.com/defi/swap",
    description:
      "Crypto.com DeFi Swap is a fork of Uniswap V2 designed to be the best place to swap and farm DeFi coins.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/oCw2s3GI_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "crypto-com-chain",
    cmcId: "1776",
    category: "Dexes",
    tvlFunction: defiswap.tvl,
  },
  {
    id: "222",
    name: "DeFiner",
    address: "0x054f76beed60ab6dbeb23502178c52d6c5debe40",
    symbol: "FIN",
    url: "https://definer.org/",
    description:
      "DeFiner empowers users to embrace the new digital economy and unlock instant value from their crypto assets through earning, lending, and borrowing.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/GsXovABD_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "definer",
    cmcId: "7225",
    category: "Yield",
    tvlFunction: definer.tvl,
  },
  {
    id: "223",
    name: "DerivaDEX",
    address: "0x3a880652f47bfaa771908c07dd8673a787daed3a",
    symbol: "DDX",
    url: "http://derivadex.com",
    description: "The next generation of derivatives trading.  \r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ewU6BDbn_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "derivadao",
    cmcId: "7228",
    category: "Dexes",
    tvlFunction: derivadex.tvl,
  },
  {
    id: "224",
    name: "DEXTF Protocol",
    address: "0x5f64ab1544d28732f0a24f4713c2c8ec0da089f0",
    symbol: "DEXTF",
    url: "https://dextf.com/",
    description:
      "Empowering anyone to mint, trade and redeem non-custodial oracle-less tokenized portfolios.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/8PSknVU3_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "dextf",
    cmcId: "8691",
    category: "Minting",
    tvlFunction: dextf.tvl,
  },
  {
    id: "225",
    name: "Enzyme Finance",
    address: "0xec67005c4e498ec7f55e092bd1d35cbc47c91892",
    symbol: "MLN",
    url: "https://enzyme.finance/",
    description:
      "Fast & cost-effective way to build, scale and monetize investment strategies.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/Vq61HUnN_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "melon",
    cmcId: "1552",
    category: "Yield",
    tvlFunction: enzyme.tvl,
  },
  {
    id: "226",
    name: "Erasure",
    address: "0x1776e1f26f98b1a5df9cd347953a26dd3cb46671",
    symbol: "NMR",
    url: "https://erasure.world/",
    description:
      "A new kind of hedge fund built by a network of data scientists",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/1h7VM_cL_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "numeraire",
    cmcId: "1732",
    category: "Derivatives",
    tvlFunction: erasure.tvl,
  },
  {
    id: "227",
    name: "CreamSwap",
    address: "0x2ba592f78db6436527729929aaf6c908497cb200",
    symbol: "CREAM",
    url: "https://app.cream.finance/swap",
    description:
      "C.R.E.A.M. Finance Swap is a blockchain agnostic, dimensional market-maker built on Ethereum. It allows user to provide liquidity to pools and earn trading fees/reserves.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/so8jjWOm_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "cream-2",
    cmcId: "6193",
    category: "Dexes",
    tvlFunction: creamswap.tvl,
  },
  {
    id: "228",
    name: "FutureSwap",
    address: "-",
    symbol: "-",
    url: "https://www.futureswap.com/",
    description:
      "Futureswap is a decentralized perpetuals exchange governed by the community.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/f5BrWYY8_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: futureswap.tvl,
  },
  {
    id: "229",
    name: "Gnosis DEX",
    address: "0x6810e776880c02933d47db1b9fc05908e5386b96",
    symbol: "GNO",
    url: "https://gnosis.io/",
    description:
      "Gnosis builds new market mechanisms for decentralized finance.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/Zbiz-s07_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "gnosis",
    cmcId: "1659",
    category: "Dexes",
    tvlFunction: gnosis.tvl,
  },
  {
    id: "230",
    name: "IDEX",
    address: "0xb705268213d593b8fd88d3fdeff93aff5cbdcfae",
    symbol: "IDEX",
    url: "https://idex.io/",
    description: "The fastest, most secure decentralized exchange.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/wEdsOzW9_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "aurora-dao",
    cmcId: "310",
    category: "Dexes",
    tvlFunction: idex.tvl,
  },
  {
    id: "231",
    name: "Lightning Network",
    address: "-",
    symbol: "-",
    url: "https://lightning.network/",
    description: " Scalable, Instant Bitcoin/Blockchain Transactions\r\n",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/7S25hk9V_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    tvlFunction: lightningNetwork.tvl,
  },
  {
    id: "232",
    name: "MCDEX",
    address: "0x4e352cf164e64adcbad318c3a1e222e9eba4ce42",
    symbol: "MCB",
    url: "https://mcdex.io/",
    description:
      "MCDEX is a fully decentralized perpetual swap exchange based on Mai Protocol,\r\nallowing anyone to create any perpetual market.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zcVXi_vV_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "mcdex",
    cmcId: "5956",
    category: "Dexes",
    tvlFunction: mcdex.tvl,
  },
  {
    id: "233",
    name: "Metronome ",
    address: "0xa3d58c4e56fedcae3a7c43a725aee9a71f0ece4e",
    symbol: "MET",
    url: "https://metronome.io/",
    description:
      "Metronome is the world’s first autonomous cryptocurrency.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/jBzKQdVq_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "metronome",
    cmcId: "2873",
    category: "Assets",
    tvlFunction: metronome.tvl,
  },
  {
    id: "234",
    name: "Notional",
    address: "-",
    symbol: "-",
    url: "https://notional.finance/",
    description: "Fixed rate lending on Ethereum\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zk8nf4kv_400x400.jpg`,
    audits: "2",
    audit_note: "",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: notional.tvl,
  },
  {
    id: "235",
    name: "PEAKDEFI",
    address: "0x630d98424efe0ea27fb1b3ab7741907dffeaad78",
    symbol: "PEAK",
    url: "https://www.peakdefi.com/",
    description:
      "A decentralized asset management fund created to grow your wealth",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/WjP0_QsY_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "marketpeak",
    cmcId: "5354",
    category: "Yield",
    tvlFunction: peakdefi.tvl,
  },
  {
    id: "236",
    name: "Perlin ",
    address: "0xeca82185adce47f39c684352b0439f030f860318",
    symbol: "PERL",
    url: "https://perlinx.finance/",
    description:
      "Democratizing the trading of real-world assets through decentralized liquidity pools and synthetic asset generation\r\n\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/V5IWp_bW_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "perlin",
    cmcId: "4293",
    category: "Dexes",
    tvlFunction: perlinx.tvl,
  },
  {
    id: "237",
    name: "Swipe",
    address: "0x8ce9137d39326ad0cd6491fb5cc0cba0e089b6a9",
    symbol: "SXP",
    url: "https://swap.swipe.org",
    description:
      "Swipe Swap enables a cross-chain automated market maker protocol on Binance Smart Chain & Ethereum.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/sx3_36MY_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "swipe",
    cmcId: "4279",
    category: "Dexes",
    tvlFunction: swipeswap,
  },
  {
    id: "238",
    name: "Ellipsis Finance",
    address: "0xA7f552078dcC247C2684336020c03648500C6d9F",
    symbol: "EPS",
    url: "https://ellipsis.finance/",
    description: "Secure low-slippage stable swapping on BSC.",
    chain: "Binance",
    logo: `${baseIconsUrl}/TAnJJCcT_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    tvlFunction: ellipsis,
  },
  {
    id: "239",
    name: "PoolTogether",
    address: "0x0cec1a9154ff802e7934fc916ed7ca50bde6844e",
    symbol: "POOL",
    url: "https://pooltogether.com/",
    description:
      "PoolTogetheris an open source and decentralized protocol for no-loss prize games",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/MtjyDDDh_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "pooltogether",
    cmcId: "8508",
    category: "Others",
    tvlFunction: pooltogether.tvl,
  },
  {
    id: "240",
    name: "Polygon",
    address: "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0",
    symbol: "MATIC",
    url: "https://polygon.technology/",
    description: "Ethereum sidechain\r\n",
    chain: "Polygon",
    logo: `${baseIconsUrl}/0VLj4wmd_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "matic-network",
    cmcId: "3890",
    category: "Chain",
    tvlFunction: polygon.tvl,
  },
  {
    id: "241",
    name: "PowerPool",
    address: "0x26607ac599266b21d13c7acf7942c7701a8b699c",
    symbol: "PIPT",
    url: "https://powerpool.finance/",
    description:
      "PowerPool is a decentralized protocol for automatically managed token portfolios, and smart indices",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/kw0NiP0c_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "power-index-pool-token",
    cmcId: "7368",
    category: "Indexes",
    tvlFunction: powerindex.tvl,
  },
  {
    id: "242",
    name: "Energiswap",
    address: "0x1416946162b1c2c871a73b07e932d2fb6c932069",
    symbol: "NRG",
    url: "https://www.energiswap.org",
    description:
      "A fully decentralized protocol for automated liquidity provision on Energi.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/qqXDg-cd_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "energi",
    cmcId: "3218",
    category: "Others",
    tvlFunction: energiswap,
  },
  {
    id: "243",
    name: "Flamincome",
    address: "0x57dD84042ec9507963016596A34EdaD42F7e4CCE ",
    symbol: "FLAG",
    url: "https://flamincome.finance",
    description: "Yield aggregator for flamingo finance",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/DSoLq_x5_400x400.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: flamincome,
  },
  {
    id: "244",
    name: "WePiggy",
    address: "0x4C78015679FabE22F6e02Ce8102AFbF7d93794eA",
    symbol: "WPC",
    url: "https://www.wepiggy.com/",
    description:
      "WePiggy is an open source, non-custodial crypto asset lending market protocol.\r\n",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/AAH4Qi9v_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    tvlFunction: wepiggy,
  },
  {
    id: "245",
    name: "Secret Network",
    address: "-",
    symbol: "SCRT",
    url: "https://scrt.network/",
    description:
      "Secret is the native coin of the Secret Network, a decentralized network for private / secure computation.",
    chain: "Secret Network",
    logo: `${baseIconsUrl}/TGwlZlS__400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "secret",
    cmcId: "5604",
    category: "Chain",
    tvlFunction: secretNetwork,
  },
  {
    id: "246",
    name: "Pangolin ",
    address: "0x60781C2586D68229fde47564546784ab3fACA982 ",
    symbol: "PNG",
    url: "https://pangolin.exchange",
    description: "Pangolin is a community-driven DEX that runs on Avalanche. ",
    chain: "Avalanche",
    logo: `${baseIconsUrl}/zsmWYqWb_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: "pangolin",
    cmcId: "8422",
    category: "Dexes",
    tvlFunction: pangolin,
  },
  {
    id: "247",
    name: "Jarvis Network",
    address: "0x8a9c67fee641579deba04928c4bc45f66e26343a ",
    symbol: "JRT",
    url: "https://jarvis.network/",
    description:
      "Jarvis Network is a set of protocols to gain exposure to the price of any asset against liquidity pools.",
    chain: null,
    logo: `${baseIconsUrl}/s2VuUdS-_400x400.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "jarvis-reward-token",
    cmcId: "5187",
    category: "Derivatives",
    tvlFunction: jarvis.tvl,
  },
  {
    id: "248",
    name: "ForceDAO ",
    address: "-",
    symbol: "-",
    url: "https://forcedao.com/",
    description: "Your portal for cross-chain yield ",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/Z9CnMRH0_400x400.png`,
    audits: "3",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    tvlFunction: forcedao.tvl,
  },
  {
    id: "249",
    name: "StakeDAO",
    address: "0x73968b9a57c6e53d41345fd57a6e6ae27d6cdb2f",
    symbol: "SDT",
    url: "https://stakedao.org/",
    description:
      "Stake Capital DAO is a revenue sharing DAO which tokenizes Stake Capital's DeFi services and uses staking derivatives to unlock additional decentralized products. The Stake Capital DAO distributes value generated by a basket of DeFi services to stakeholders.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/6uqFPXny_400x400.jpg`,
    audits: "3",
    audit_note: null,
    gecko_id: "stake-dao",
    cmcId: "8299",
    category: "Yield",
    tvlFunction: stakedao.tvl,
  },
  {
    id: "250",
    name: "BasketDAO",
    address: "-",
    symbol: "-",
    url: "https://basketdao.org/",
    description:
      "A community controlled no fee token basket that you are PAID to hold.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/eq0vIOD1_400x400.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    tvlFunction: basketdao.tvl,
  },
] as Protocol[];
