const abi = {
  vestingAmount: {
    constant: true,
    inputs: [],
    name: "vestingAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  vestingBegin: {
    constant: true,
    inputs: [],
    name: "vestingBegin",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  vestingCliff: {
    constant: true,
    inputs: [],
    name: "vestingCliff",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  vestingEnd: {
    constant: true,
    inputs: [],
    name: "vestingEnd",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  recipient: {
    inputs: [],
    name: "recipient",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  token: {
    inputs: [],
    name: "",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
};
export default abi;
