export default {
  aave: require("./aave.json"),
  apecoin: require("./apecoin.json"),
  aptos: require("./aptos.json"),
  // aura: require("./aura.json"),
  benddao: require("./benddao.json"),
  blur: require("./blur.json"),
  convex: require("./convex.json"),
  curve: require("./curve.json"),
  dydx: require("./dydx.json"),
  // euler: require("./euler.json"),
  forta: require("./forta.json"),
  stargate: require("./stargate.json"),
  sushi: require("./sushi.json"),
  tornado: require("./tornado.json"),
  uniswap: require("./uniswap.json"),
  velodrome: require("./velodrome.json"),
  yearn: require("./yearn.json"),
  zyberswap: require("./zyberswap.json"),
};
