export default {
  aave: require("./moneyMarkets/aave/index"),
  geist: require("./moneyMarkets/aave/index"),
  radiant: require("./moneyMarkets/aave/index"),
  //klap: require("./moneyMarkets/aave/index"),
  //valas: require("./moneyMarkets/aave/index"),
  compound: require("./moneyMarkets/compound/index"),
  venus: require("./moneyMarkets/compound/index"),
  ironbank: require("./moneyMarkets/compound/index"),
  benqi: require("./moneyMarkets/compound/index"),
  traderjoe: require("./moneyMarkets/compound/index"),
  rari: require("./moneyMarkets/compound/index"),
  aurigami: require("./moneyMarkets/compound/index"),
  cream: require("./moneyMarkets/compound/index"),
  scream: require("./moneyMarkets/compound/index"),
  yearn: require("./yield/yearn/index"),
  curve1: require("./lps/curve/index"),
  curve2: require("./lps/curve/index"),
  curve3: require("./lps/curve/index"),
  curve4: require("./lps/curve/index"),
  curve5: require("./lps/curve/index"),
  ellipsis: require("./lps/curve/index"),
  balancer: require("./lps/balancer/index"),
  gauges: require("./lps/curve/index"),
  ankr: require("./liquidStaking/ankr/index"),
  synthetix: require("./other/index"),
  uniswap: require("./lps/uniswap/index")
  // traderJoe: require("./lps/uniswap/index"),
  // vvsFinance: require("./lps/uniswap/index"),
  // quickswap: require("./lps/uniswap/index"),
  // biswap: require("./lps/uniswap/index"),
  // mmFinance: require("./lps/uniswap/index"),
  // trisolaris: require("./lps/uniswap/index"),
  // pangolin: require("./lps/uniswap/index"),
  // spiritswap: require("./lps/uniswap/index"),
  // pancakeswap: require("./lps/uniswap/index")
};
