interface ICex {
  name: string;
  slug?: string;
  coin?: string | null;
  coinSymbol?: string | null;
  walletsLink?: string | null;
  url?: string | null;
  cgId?: string | null;
  cgDeriv?: string | null;
  cgSpotId?: string | null;
  lastAuditDate?: number;
  auditor?: string | null;
  auditLink?: string | null;
  ownTokens?: string[] | null;
}

export const cexsData: Array<ICex> = [
  {
    name: "Binance",
    slug: "Binance-CEX",
    coin: "BNB",
    coinSymbol: "BNB",
    walletsLink: "https://www.binance.com/en/blog/community/our-commitment-to-transparency-2895840147147652626",
    cgId: "binance",
    cgDeriv: "binance_futures",
    url: "https://www.binance.com",
  },
  {
    name: "OKX",
    slug: "okx",
    coin: "OKB",
    coinSymbol: "OKB",
    walletsLink: "https://twitter.com/okx/status/1590812545346330624",
    cgId: "okex",
    cgDeriv: "okex_swap",
    url: "https://www.okx.com",
  },
  {
    name: "Bitfinex",
    slug: "bitfinex",
    coin: "LEO",
    coinSymbol: "LEO",
    walletsLink: "https://github.com/bitfinexcom/pub/blob/main/wallets.txt",
    cgId: "bitfinex",
    cgDeriv: "bitfinex_futures",
    url: "https://www.bitfinex.com",
  },
  {
    name: "Robinhood",
    slug: "robinhood",
    coin: null,
    walletsLink: null,
    cgId: null,
    url: "https://robinhood.com",
  },
  {
    name: "Gemini",
    slug: "gemini",
    coin: null,
    cgId: "gemini",
    walletsLink: "https://www.gemini.com/trust-center/",
    url: "https://www.gemini.com",
  },
  {
    name: "Bybit",
    slug: "Bybit",
    coin: "BIT",
    coinSymbol: "BIT",
    walletsLink: "https://twitter.com/benbybit/status/1592797790518018048",
    cgId: "bybit_spot",
    cgDeriv: "bybit",
    ownTokens: ['MNT'],
    url: "https://www.bybit.com",
  },
  /* */
	{
		name: 'Kraken',
		slug: 'kraken',
		coin: null,
		walletsLink: null,
		cgId: 'kraken',
		cgDeriv: 'kraken_futures',
		url: 'https://www.kraken.com/',
	},
	/**/
  {
    name: "Crypto.com",
    slug: "Crypto-com",
    coin: "CRO",
    coinSymbol: "CRO",
    walletsLink: "https://crypto.com/document/proof-of-reserves",
    cgId: "crypto_com",
    cgDeriv: "crypto_com_futures",
    url: "https://crypto.com",
  },
  {
    name: "HTX",
    slug: "htx",
    coin: "HT",
    coinSymbol: "HT",
    walletsLink: "https://www.huobi.com/support/en-us/detail/24922606430831",
    cgId: "huobi",
    cgDeriv: "huobi_dm",
    url: "https://www.htx.com/",
  },
  {
    name: "KuCoin",
    slug: "kucoin",
    coin: "KCS",
    coinSymbol: "KCS",
    walletsLink: "https://www.kucoin.com/blog/transparency-and-trust-a-detailed-list-of-kucoin-s-wallets",
    cgId: "kucoin",
    cgDeriv: "kumex",
    url: "https://www.kucoin.com",
  },
  {
    name: "Bitstamp",
    slug: "bitstamp",
    coin: null,
    walletsLink: null,
    cgId: "bitstamp",
    url: "https://www.bitstamp.net",
  },
  {
    name: "Deribit",
    slug: "deribit",
    coin: null,
    walletsLink: "https://insights.deribit.com/exchange-updates/proof-of-reserves-deribit/",
    cgDeriv: "deribit",
    url: "https://www.deribit.com",
  },
  {
    name: "Bitkub",
    slug: "bitkub",
    coin: "KUB",
    coinSymbol: "KUB",
    cgId: "bitkub",
    url: "https://www.bitkub.com/",
  },
  {
    name: "Gate", // Used to be 'Gate.io'
    slug: "Gate",
    coin: "GT",
    coinSymbol: "GT",
    walletsLink: "https://github.com/gateio/proof-of-reserves",
    cgId: "gate",
    cgDeriv: "gate_futures",
    url: "https://www.gate.com",
  },
  {
    name: "Bitget",
    slug: "bitget",
    coin: "BGB",
    coinSymbol: "BGB",
    walletsLink: "https://twitter.com/bitgetglobal/status/1602256957376794624",
    cgId: "bitget",
    cgDeriv: "bitget_futures",
    url: "https://www.bitget.com",
  },
  {
    name: "MEXC",
    slug: "mexc",
    coin: "MX",
    coinSymbol: "MX",
    cgId: "mxc",
    cgDeriv: "mxc_futures",
    url: "https://www.mexc.com",
  },
  {
    name: "Bitmex",
    slug: "bitmex",
    coin: null,
    walletsLink: "https://github.com/BitMEX/proof-of-reserves-liabilities",
    cgId: "bitmex_spot",
    cgDeriv: "bitmex",
    url: "https://www.bitmex.com",
  },
  {
    name: "SwissBorg",
    slug: "swissborg",
    coin: "BORG",
    coinSymbol: "BORG",
    walletsLink: "https://github.com/swissborg/pub",
    url: "https://swissborg.com",
  },
  {
    name: "MaskEX",
    slug: "maskex",
    coin: null,
    walletsLink: "https://blog.maskex.com/news/announcements/embracing-transparency-maskex-reveals-wallet-addresses",
    url: "https://www.maskex.com",
  },
  {
    name: "Korbit",
    slug: "korbit",
    coin: null,
    walletsLink: "https://korbit.co.kr/reserve",
    url: "https://korbit.co.kr",
  },
  {
    name: "Phemex",
    slug: "phemex",
    coin: null,
    walletsLink: "https://phemex.com/proof-of-reserves",
    cgId: "phemex",
    cgDeriv: "phemex_futures",
    url: "https://phemex.com",
  },
  {
    name: "Firi",
    slug: "firi",
    coin: null,
    walletsLink: null,
    url: "https://firi.com",
  },
  {
    name: "ProBit Global",
    slug: "probit-global",
    coin: "PROB",
    coinSymbol: "PROB",
    walletsLink: null,
    url: "https://www.probit.com",
  },
  {
    name: "WOO X",
    slug: "woo-x",
    coin: "WOO",
    coinSymbol: "WOO",
    walletsLink: "https://woo.org/proof-of-reserves",
    url: "https://x.woo.org/en/trade",
  },
  {
    name: "Bake.io",
    slug: "bake.io",
    coin: null,
    walletsLink: "https://blog.bake.io/proof-of-reserves/",
    url: "https://www.bake.io",
  },
  {
    name: "BingX",
    slug: "bingx",
    coin: null,
    walletsLink: "https://bingx.com/en/balance-reserve/",
    cgId: "bingx",
    url: "https://bingx.com",
  },
  {
    name: "Coinsquare",
    slug: "coinsquare",
    coin: null,
    walletsLink: "https://twitter.com/Coinsquare/status/1594176519986810881",
    url: "https://coinsquare.com",
  },
  {
    name: "Toobit",
    slug: "toobit",
    coin: null,
    walletsLink:
      "https://support.toobit.com/hc/en-us/articles/35739879881881-Toobit-Asset-Transparency-Report-Safeguarding-User-Assets",
    url: "https://www.toobit.com",
  },
  {
    name: "CoinW",
    slug: "coinw",
    coin: null,
    walletsLink: null,
    url: "https://www.coinw.com",
  },

  {
    name: "CoinDCX",
    slug: "coindcx",
    coin: null,
    walletsLink: "https://twitter.com/smtgpt/status/1595745395787071497",
    url: "https://coindcx.com",
  },
  {
    name: "Fastex",
    slug: "fastex",
    coin: "FTN",
    coinSymbol: "FTN",
    walletsLink: "https://www.fastex.com/proof-of-reserves",
    cgId: "fastex",
    url: "https://exchange.fastex.com",
  },
  {
    name: "NBX",
    slug: "nbx",
    coin: null,
    walletsLink: "https://nbx.com/en/proof-of-reserves",
    url: "https://nbx.com",
  },
  {
    name: "Okcoin",
    slug: "okcoin",
    coin: null,
    walletsLink: "https://www.okcoin.com/proof-of-reserves/download",
    url: "https://www.okcoin.com",
  },
  {
    name: "BitVenus",
    slug: "bitvenus",
    coin: null,
    walletsLink: null,
    url: "https://www.bvox.com/",
  },
  {
    name: "Coin8",
    slug: "coin8",
    coin: null,
    walletsLink: null,
    url: "https://www.coin8.co",
  },
  {
    name: "Exmo",
    slug: "exmo",
    coin: null,
    walletsLink: null,
    url: "https://exmo.com",
  },
  {
    name: "Flipster",
    slug: "flipster",
    coin: null,
    walletsLink: "https://flipster.io/support/proof-of-reserves",
    url: "https://flipster.io",
  },
  {
    name: "NonKYC",
    slug: "nonkyc",
    coin: "NKYC",
    coinSymbol: "NKYC",
    walletsLink: "https://nonkyc.io/allreserves",
    cgId: "nonkyc_io",
    url: "https://nonkyc.io",
  },
  {
    name: "Bitrue",
    slug: "bitrue",
    coin: "BTR",
    cgId: "bitrue",
    cgDeriv: "bitrue_futures",
    url: "https://www.bitrue.com",
  },
  {
    name: "Latoken",
    slug: "latoken",
    coin: null,
    walletsLink: null,
    url: "https://latoken.com",
  },
  {
    name: "BitMart",
    slug: "bitMart",
    coin: "BMX",
    coinSymbol: "BMX",
    cgId: "bitmart",
    cgDeriv: "bitmart_futures",
    url: "https://www.bitmart.com",
  },
  {
    name: "Klever Exchange",
    slug: "klever-exchange",
    coin: "KLV",
    coinSymbol: "KLV",
    cgId: "klever_io",
    url: "https://klever.io/",
  },
  {
    name: "BTSE",
    slug: "btse",
    coin: "BTSE",
    coinSymbol: "BTSE",
    cgId: "btse",
    url: "https://www.btse.com",
  },
  {
    name: "HashKey Exchange",
    slug: "hashkey-exchange",
    coin: null,
    walletsLink: null,
    url: "https://www.hashkey.com",
  },
  {
    name: "Biconomy.com",
    slug: "biconomy.com",
    coin: null,
    walletsLink: null,
    url: "https://www.biconomy.com",
  },
  {
    name: "Pionex",
    slug: "pionex",
    coin: null,
    walletsLink: null,
    url: "https://www.pionex.com/en",
  },
  {
    name: "Bitunix",
    slug: "bitunix",
    coin: null,
    walletsLink:
      "https://support.bitunix.com/hc/en-us/articles/36928276763289-Bitunix-Launching-Proof-or-Reserve-to-Improve-Transparency",
    url: "https://www.bitunix.com",
  },
  {
    name: "BloFin",
    slug: "blofin",
    coin: null,
    walletsLink: null,
    url: "https://www.blofin.com",
  },
  {
    name: "Backpack",
    slug: "backpack",
    coin: null,
    coinSymbol: null,
    walletsLink: "https://dune.com/21co/backpack-exchange",
    url: "https://backpack.exchange",
  },
  {
    name: "Hotcoin",
    slug: "hotcoin",
    coin: null,
    walletsLink: null,
    url: "https://www.hotcoin.com",
  },
  {
    name: "Ourbit",
    slug: "ourbit",
    coin: null,
    coinSymbol: null,
    walletsLink: "https://www.ourbit.com/assets/reserve-proof",
    url: "https://www.ourbit.com",
  },
  {
    name: "Indodax",
    slug: "indodax",
    coin: null,
    walletsLink: null,
    url: "https://www.indodax.com",
  },
  {
    name: "Tothemoon",
    slug: "tothemoon",
    coin: null,
    walletsLink: null,
    url: "https://tothemoon.com",
  },
  {
    name: "HashKey Global",
    slug: "hashkey-global",
    coin: null,
    coinSymbol: null,
    url: "https://www.hashkey.com",
  },
  {
    name: "P2PB2B",
    slug: "p2pb2b",
    coin: null,
    walletsLink: null,
    url: "https://p2pb2b.com/",
  },
  {
    name: "Tapbit",
    slug: "tapbit",
    coin: null,
    walletsLink: null,
    url: "https://www.tapbit.com",
  },
  {
    name: "OrangeX",
    slug: "orangex",
    coin: null,
    walletsLink: null,
    url: "https://www.orangex.com",
  },
  {
    name: "Bitcointry",
    slug: "bitcointry",
    coin: "BTTY",
    coinSymbol: "BTTY",
    url: "https://www.bitcointry.com",
  },
  {
    name: "BigONE",
    slug: "bigone",
    coin: null,
    walletsLink: null,
    cgId: "bigone",
    url: "https://big.one",
  },
  {
    name: "BitMake",
    slug: "bitmake",
    coin: null,
    walletsLink: null,
    url: "https://www.bitmake.com",
  },
  {
    name: "Arkham Exchange",
    slug: "arkham-exchange",
    coin: "ARKM",
    coinSymbol: "ARKM",
    url: "https://arkm.com/",
  },
  {
    name: "Hibt",
    slug: "hibt",
    coin: null,
    walletsLink: null,
    url: "https://hibt.com",
  },
  {
    name: "LBank",
    slug: "lbank",
    cgId: "lbank",
    url: "https://www.lbank.com",
  },
  {
    name: "TradeOgre",
    slug: "tradeogre",
    coin: null,
    walletsLink: null,
    url: "https://tradeogre.com/markets",
  },
  {
    name: "Hotbit",
    slug: "hotbit",
    coin: "HTB",
    coinSymbol: "HTB",
  },
  {
    name: "BiTomato",
    slug: "bitomato",
    coin: null,
    walletsLink: null,
    url: "https://bitomato.com/",
  },
  {
    name: "Zoomex",
    slug: "zoomex",
    coin: null,
    walletsLink: null,
    url: "https://www.zoomex.com",
  },
  {
    name: "CoinEx",
    slug: "coinex",
    coin: "CET",
    coinSymbol: "CET",
    walletsLink: null,
    cgId: "coinex",
    cgDeriv: "coinex_futures",
    url: "https://www.coinex.com/en",
  },
  /*
	{
		name: 'Binance US',
		slug: 'binance-us',
		coin: 'BNB',
		coinSymbol: 'BNB',
		cgId: 'binance_us'
	},
	*/
  {
    name: "Coinbase",
    lastAuditDate: 1640908800,
    auditor: "Deloitte",
    auditLink: "https://d18rn0p25nwr6d.cloudfront.net/CIK-0001679788/8e5e0508-da75-434d-9505-cba99fa00147.pdf",
    cgId: "gdax",
    url: "https://www.coinbase.com",
  },
  {
    name: "Coinone",
    lastAuditDate: 1666369050,
    auditor: null,
    auditLink: "https://coinone.co.kr/info/notice/1967",
    cgId: "coinone",
  },
  {
    name: "NEXO",
    url: "https://nexo.com/",
  },
  {
    name: "Coincheck",
    cgId: "coincheck",
  },
  {
    name: "Bithumb",
    cgId: "bithumb",
  },
  {
    name: "Poloniex",
    cgId: "poloniex",
  },
  {
    name: "Upbit",
    cgId: "upbit",
  },
  {
    name: "Bittrex",
    cgId: "bittrex",
  },
  {
    name: "AscendEX",
    cgId: "bitmax",
    cgDeriv: "bitmax_futures",
  },
  {
    name: "bitFlyer",
    cgId: "bitflyer",
    cgDeriv: "bitflyer_futures",
  },
  {
    name: "BKEX",
    cgId: "bkex",
  },
  {
    name: "BTCEX",
    cgId: "btcex",
    cgDeriv: "btcex_futures",
  },
  {
    name: "BTCC",
    cgId: "btcc",
    cgDeriv: "btcc_futures",
  },
  {
    name: "Deepcoin",
    cgId: "deepcoin",
  },
  {
    name: "CEX.IO",
    cgId: "cex",
    slug: "cex.io",
    coin: null,
    walletsLink: null,
    url: "http://cex.io/",
  },
  {
    name: "Bitlo",
    cgId: "bitlo",
    slug: "bitlo",
    coin: null,
    walletsLink: null,
    url: "https://www.bitlo.com/",
  },
  {
    name: "VALR",
    cgId: "valr",
    slug: "valr",
    coin: null,
    walletsLink: null,
    url: "https://valr.com/",
  },
  {
    name: "BitKan",
    cgId: "bitkan",
    slug: "bitkan",
    coin: "KAN",
    coinSymbol: "KAN",
    walletsLink: null,
    url: "https://bitkan.com/",
  },
  {
    name: "OSL",
    slug: "osl",
    coin: null,
    walletsLink: null,
    url: "https://www.osl.com/en",
  },
  {
    name: "Voyager",
    slug: "voyager",
    coin: null,
    walletsLink: null,
    url: "https://www.investvoyager.com",
  },
  {
    name: "Gate US",
    cgId: "gate-us",
    slug: "gate-us",
    coin: null,
    walletsLink: null,
    url: "https://www.gate.com/en-us",
  },
  {
    name: "LeveX",
    cgId: "levex",
    slug: "levex",
    coin: null,
    walletsLink: null,
    cgDeriv: "levex-futures",
    url: "https://levex.com/",
  },
  {
    name: "WEEX",
    cgId: "weex",
    slug: "weex",
    coin: "weex-token",
    walletsLink: null,
    cgDeriv: "weex-futures",
    url: "https://www.weex.com/",
  },
  {
    name: "BYDFi",
    cgId: "bydfi",
    slug: "bydfi",
    coin: null,
    walletsLink: null,
    cgDeriv: "bydfi-futures",
    url: "https://www.bydfi.com/en",
  },
  {
    name: "OSL HK",
    slug: "osl-hk",
    coin: null,
    walletsLink: null,
    url: "https://www.osl.com/en",
  },
  {
    name: "Byte Exchange",
    slug: "byte-exchange",
    coin: null,
    walletsLink: null,
    url: "https://bexc.io/",
  },
  {
    name: "GroveX",
    slug: "grovex",
    coin: null,
    walletsLink: null,
    url: "https://grovex.io/en_US/",
  },
];

const cgNameListingIdMap: { [name: string]: string } = {
  "Bybit": "bybit-spot",
  "Coinbase": "gdax",
  "Huobi": "huobi",
  "KuCoin": "kucoin",
  "Kraken": "kraken",
  "Binance": "binance",
  "Binance US": "binance_us",
  "Crypto.com Exchange": "crypto_com",
  "Bitfinex": "bitfinex",
  "Gate.io": "gate",
  "Bitget": "bitget",
  "OKX": "okex",
  "BingX": "bingx",
  "Phemex": "phemex",
  "Gemini": "gemini",
  "MEXC Global": "mxc",
  "WhiteBIT": "whitebit",
  "Upbit": "upbit",
  "BitMart": "bitmart",
  "BTSE": "btse",
  "EXMO": "exmo",
  "CoinEx": "coinex",
  "Bitbank": "bitbank",
  "WOO X": "wootrade",
  "Bitso": "bitso",
  "Coins.ph": "coinspro",
  "LBank": "lbank",
  "DigiFinex": "digifinex",
  "Coinsbit": "coinsbit",
  "XT.COM": "xt",
  "BTCEX": "btcex",
  "P2B": "p2pb2b",
  "Tidex": "tidex",
  "Bithumb": "bithumb",
  "Bitrue": "bitrue",
  "BigONE": "bigone",
  "Dex-Trade": "dextrade",
  "Coinstore": "coinstore",
  "Poloniex": "poloniex",
  "Paribu": "paribu",
  "AscendEX (BitMax)": "bitmax",
  "Bitstamp": "bitstamp",
  "bitFlyer": "bitflyer",
  "BtcTurk PRO": "btcturk",
  "QMall": "qmall",
  "Cryptology": "cryptology",
  "Bitkub": "bitkub",
  "C-Patex": "c_patex",
  "LATOKEN": "latoken",
  "Max Maicoin": "max_maicoin",
  "Kanga": "kanga",
  "Luno": "luno",
  "Indodax": "indodax",
  "BTCMarkets": "btcmarkets",
  "Korbit": "korbit",
  "BitoPro": "bitopro",
  "Bittrex Global": "bittrex",
  "VALR": "valr",
  "CEX.IO": "cex",
  "Bitpanda Pro": "bitpanda",
  "Delta Exchange": "delta_spot",
  "Blockchain.com": "blockchain_com",
  "Coinmetro": "coin_metro",
  "NiceHash": "nice_hash",
  "BitMEX": "bitmex_spot",
  "Okcoin": "okcoin",
  "Toobit": "toobit",
  "Bitforex": "bitforex",
  "DIFX": "difx",
  "Bitvavo": "bitvavo",
  "Coincheck": "coincheck",
  "FMFW.io": "bitcoin_com",
  "PointPay": "pointpay",
  "GMO Japan": "gmo_japan",
  "Bitazza": "bitazza",
  "Independent Reserve": "independent_reserve",
  "Nominex": "nominex",
  "Coinlist": "coinlist",
  "Fastex": "fastex",
  "CoinJar Exchange": "coinjar",
  "Zaif": "zaif",
  "WazirX": "wazirx",
  "Bitlo": "bitlo",
  "Bitcoin.me": "klever_exchange",
  "CoinTR Pro": "cointr",
  "Pionex": "pionex",
  "Deepcoin": "deepcoin",
  "ProBit Global": "probit",
  "CoinDCX": "coindcx",
  "Coinone": "coinone",
  "Bitci TR": "bitci",
  "BIT": "bit_com",
  "Stormgain": "stormgain",
  "BitBNS": "bitbns",
  "Bullish": "bullish_com",
  "TokoCrypto": "toko_crypto",
  "Currency.com": "currency",
  "Bilaxy": "bilaxy",
  "Tokenize": "tokenize",
  "Coinzoom": "coinzoom",
  "NovaDAX": "novadax",
  "Deribit Spot": "deribit_spot",
  "Deribit": "deribit",
  "Emirex": "emirex",
  "Bitbuy": "bitbuy",
  "Foxbit": "foxbit",
  "ZBX": "zbx",
  "zipmex": "zipmex",
  "OSL": "osl",
  "Gate US": "gate-us",
  "OSL HK": "osl-hk",
}

cexsData.forEach(c => {
  if (cgNameListingIdMap[c.name]) {
    c.cgSpotId = cgNameListingIdMap[c.name];
  }
})

export const cg_volume_cexs = Object.values(cgNameListingIdMap);
