import { baseIconsUrl } from "../constants";
import type { Protocol } from "./types";
/*
{
  id: string;
  name: string;
  address: string;
  symbol: string;
  url: string;
  description: string;
  chain: string;
  logo: null | string;
  audits: null | "0" | "1" | "2" | "3";
  audit_note: null;
  gecko_id: string;
  cmcId: string;
  category: string;
  chains: string[];
  oracles: string[];
  forkedFrom: string[];
  module: string;
  twitter: string;
  language?: string;
  treasury?: string;
  tokensExcludedFromParent: {
      Avalanche: ["GPC"],    // ADD ALL TIME WITH BIG LETTER, NOT SMALL LETTER
    },
  excludeTvlFromParent?: boolean;
},
*/
/* Audits: Please follow this legend
0 -> No audits
1 -> Part of this protocol may be unaudited
2 -> Yes
3 -> This protocol is a fork of an existing audited protocol
*/
/*
`chain` is the first chain of a protocol we tracked at defillama,
  so if a protocol launches on Ethereum and we start tracking it there, and then it launches on polygon and
  we start tracking it on both polygon and ethereum, then `chain` should be set to `Ethereum`.
`chains` is not used by the current code, but good to fill it out because it is used in our test to detect errors
*/
const data5: Protocol[] = [
  {
    id: "6894",
    name: "Rho X",
    address: null,
    symbol: "-",
    url: "https://x.rho.trading/",
    description: `Rho Protocol is a cryptonative interest rates market. The platform uniquely offers trading of staking, lending, and perpetual future funding rates all in one venue, as well as allowing users to passively earn yield by depositing into Rho's vaults`,
    chain: "Ethereum",
    logo: `${baseIconsUrl}/rho-x.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Ethereum"],
    forkedFrom: [],
    module: "rho-x/index.js",
    twitter: "Rho_Labs",
    audit_links: [],
    parentProtocol: "parent#rho",
    listedAt: 1761100587,
    dimensions: {
      derivatives: "rho-x",
      "open-interest": "rho-trading"
    }
  },
  // { duplicate listing: Counts LPs for Skate AMM on 0G
  //   id: "6895",
  //   name: "Skatechain",
  //   address: null,
  //   symbol: "-",
  //   url: "https://amm.skatechain.org/swap",
  //   description: `Interact with applications from any VM while staying on your favorite chain`,
  //   chain: "0G",
  //   logo: `${baseIconsUrl}/skatechain.jpg`,
  //   audits: "0",
  //   audit_note: null,
  //   gecko_id: null,
  //   cmcId: null,
  //   category: "Dexs",
  //   chains: ["0G"],
  //   forkedFrom: [],
  //   module: "skatechain/index.js",
  //   twitter: "skate_chain",
  //   audit_links: [],
  //   listedAt: 1761111387,
  // },
  {
    id: "6896",
    name: "TradeGPT",
    address: null,
    symbol: "-",
    url: "https://tradegpt.finance/",
    description: `Prompt to trade with TradeGPT, a natural language DEX native to 0G`,
    chain: "0G",
    logo: `${baseIconsUrl}/tradegpt.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["0G"],
    forkedFrom: ["2198"],
    module: "tradegpt/index.js",
    twitter: "zia_finance",
    audit_links: [],
    listedAt: 1761111395,
  },
  {
    id: "6897",
    name: "BEND",
    address: null,
    symbol: "-",
    url: "https://bend.berachain.com",
    description: `Bend is a decentralized lending protocol forked from Morpho, designed to enable efficient lending and borrowing with native Proof-of-Liquidity (PoL) on Berachain. As a lending primitive layer, Bend allows the creation of immutable and efficient lending markets in a permissionless way`,
    chain: "Berachain",
    logo: `${baseIconsUrl}/bend.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Berachain"],
    forkedFrom: ["4025"],
    module: "berachain-bend/index.js",
    twitter: "berachain",
    audit_links: ["https://github.com/berachain/security-audits"],
    listedAt: 1761111893,
    dimensions: {
      fees: "bend"
    }
  },
  {
    id: "6898",
    name: "Elix.fi",
    address: null,
    symbol: "-",
    url: "https://www.elix.fi/",
    description: `Capital-efficient and modular CLOB DEX`,
    chain: "Somnia",
    logo: `${baseIconsUrl}/elix.fi.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Somnia"],
    forkedFrom: ["4610"],
    module: "elix-fi/index.js",
    twitter: "elix_fi",
    audit_links: [],
    listedAt: 1761170279,
    dimensions: {
      dexs: "elix-fi",
      fees: "elix-fi"
    }
  },
  {
    id: "6899",
    name: "Marquee",
    address: null,
    symbol: "-",
    url: "https://marquee.fi/",
    description: `Marquee is a decentralized insurance protocol that allows users to both purchase cover for digital-assets and provide liquidity to backing pools, while earning real-premiums and governance exposure via its MARQ token`,
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/marquee.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Insurance",
    chains: ["Arbitrum"],
    forkedFrom: [],
    module: "marquee/index.js",
    twitter: "Marquee_fi",
    audit_links: ["https://docs.marquee.fi/audit"],
    listedAt: 1761170602,
    dimensions: {
      fees: "marquee",
    }
  },
  {
    id: "6900",
    name: "Phi",
    address: "0xfb3ad5550ca5730a6f91350032c4da1efdfde3e8",
    symbol: "PHI",
    url: "https://phi.box",
    description: `An open credentialing protocol for on-chain identity that revolutionizes how users build, visualize, and showcase their on-chain identity`,
    chain: "Base",
    logo: `${baseIconsUrl}/phi.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "phi",
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    forkedFrom: [],
    module: "phi/index.js",
    twitter: "phi_xyz",
    audit_links: ["https://docs.phi.box/explore-phi/others/audit"],
    listedAt: 1761171731,
  },
  {
    id: "6901",
    name: "Shift Protocol",
    address: null,
    symbol: "-",
    url: "https://shiftprotocol.xyz/",
    description: `Shift is a DeFi protocol offering a suite of yield products built on top of leading on-chain perpetual futures exchanges (Perp DEXs). Our mission is to make high-yield strategies available to anyone through transparent, on-chain vaults`,
    chain: "Base",
    logo: `${baseIconsUrl}/shift-protocol.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Base"],
    forkedFrom: [],
    module: "shift-protocol/index.js",
    twitter: "shiftprotocol_",
    audit_links: ["https://github.com/SHIFT-NebulaLabs/shift-contracts/blob/main/audits/shift-sbsecurity-audit-2025.pdf"],
    listedAt: 1761171899,
  },
  {
    id: "6902",
    name: "Pyth Entropy",
    address: "solana:HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    symbol: "PYTH",
    url: "https://www.pyth.network/",
    description: `Pyth Entropy allows developers to quickly and easily generate secure random numbers on the blockchain`,
    chain: "Ethereum",
    logo: `${baseIconsUrl}/pyth-entropy.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Oracle",
    chains: ["Ethereum", "Base", "ZetaChain", "Unichain", "Optimism", "Hyperliquid L1", "Blast", "Abstract", "Sonic", "Soneium", "Berachain", "Klaytn", "ApeChain"],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "PythNetwork",
    audit_links: [],
    parentProtocol: "parent#pyth",
    dimensions: {
      fees: "pyth-entropy"
    }
  },
  {
    id: "6903",
    name: "Credit Coop",
    address: null,
    symbol: "-",
    url: "https://www.creditcoop.xyz/",
    description: `Credit Coop is transforming credit markets with blockchain-powered infrastructure that turns business cash flows into programmable collateral. Credit Coop is building the foundation for a new generation of credit markets that are transparent, programmable, and settle 24/7/365`,
    chain: "Ethereum",
    logo: `${baseIconsUrl}/credit-coop.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA Lending",
    chains: ["Ethereum","Base"],
    forkedFrom: [],
    module: "credit-coop/index.js",
    twitter: "creditcoop_xyz",
    listedAt: 1761266372,
  },
  {
    id: "6904",
    name: "Isle Finance",
    address: null,
    symbol: "-",
    url: "https://app.isle.finance/",
    description: `RWA PayFi - Isle Finance is the first on-chain credit marketplace for supply chain finance. Isle Finance is the decentralized protocol for globally accessible supply chain finance, with a mission to bring the world's supply chain activity on-chain while expanding capital access and increasing supply chain resilience`,
    chain: "Hedera",
    logo: `${baseIconsUrl}/isle-finance.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA Lending",
    chains: ["Hedera", "Plume Mainnet"],
    forkedFrom: [],
    module: "isle-finance/index.js",
    twitter: "IsleFinance",
    audit_links: ["https://github.com/isle-labs/isle-contract/tree/main/audits"],
    github: ["isle-labs"],
    listedAt: 1761266487,
  },
  {
    id: "6905",
    name: "Avant avETH",
    address: null,
    symbol: "-",
    url: "https://app.avantprotocol.com/products",
    description: `avETH is a stable-value token that can be staked to earn yield with savETH`,
    chain: "Ethereum",
    logo: `${baseIconsUrl}/avant-aveth.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Ethereum"],
    forkedFrom: [],
    module: "avant-aveth/index.js",
    twitter: "avantprotocol",
    audit_links: ["https://docs.avantprotocol.com/security/contract-and-opsec-audits"],
    parentProtocol: "parent#avant-protocol",
    listedAt: 1761266699,
  },
  {
    id: "6906",
    name: "Nivela Finance",
    address: "bsc:0x56fc995646ab92a5128ceb2124721d122b3b9d90",
    symbol: "NIV",
    url: "https://www.nivela.finance/",
    description: `Sovereign borrowing protocol on BNB Smart Chain (BSC). High-LTV lending, over-collateralized nUSD stablecoin, revenue sharing via stnUSD, governance via veNIV`,
    chain: "Binance",
    logo: `${baseIconsUrl}/nivela-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Binance"],
    forkedFrom: [],
    module: "Nivela/index.js",
    twitter: "nivelafi",
    audit_links: [],
    listedAt: 1761284787,
  },
  {
    id: "6907",
    name: "Mantle Index Four Fund",
    address: "mantle:0x671642Ac281C760e34251d51bC9eEF27026F3B7a",
    symbol: "MI4",
    url: "https://www.mantle.xyz/",
    description: `This fund offers diversified exposure to leading cryptocurrencies by tracking a market-cap-weighted index of top Layer 1 and Layer 2 tokens, including assets like BTC, ETH, and SOL. Designed to function as the crypto equivalent of the S&P 500, it allows investors to access broad crypto beta without managing wallets or selecting individual assets. The portfolio is rebalanced quarterly and includes a fixed USD allocation, while the remaining assets are weighted by market cap within set limits. Enhanced yield potential is achieved through the use of staked instruments such as mETH, bbSOL, and sUSDe. Structured for institutional investors, the fund features traditional administration, a 1% management fee, and simplified access to digital assets and stablecoins`,
    chain: "Mantle",
    logo: `${baseIconsUrl}/mantle-index-four-fund.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    chains: ["Mantle"],
    forkedFrom: [],
    module: "mi4/index.js",
    twitter: "Mantle_Official",
    audit_links: [],
    oraclesBreakdown: [
      {
        name: "RedStone",
        type: "Primary",
        proof: ["https://app.redstone.finance/app/feeds/mantle/mi4_mantle_fundamental/"]
      }
    ],
    listedAt: 1761284792,
  },
  {
    id: "6908",
    name: "FOOM Cash",
    address: null,
    symbol: "-",
    url: "https://foom.cash",
    description: `FOOM Cash is a privacy-focused game built on Ethereum and Base. It uses advanced zk-SNARK cryptography to allow users to play for three simultaneous prizes—without revealing the user's identity`,
    chain: "Ethereum",
    logo: `${baseIconsUrl}/foom-cash.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Privacy",
    chains: ["Ethereum", "Base"],
    forkedFrom: [],
    module: "foom-cash/index.js",
    twitter: "FOOMCASH",
    audit_links: [],
    github: ["Terrestrials"],
    listedAt: 1761284804,
    dimensions: {
      fees: "foom-cash"
    }
  },
  {
    id: "6909",
    name: "CRIPTO NO PIX",
    address: "0xBe96fcF736AD906b1821Ef74A0e4e346C74e6221",
    symbol: "NIX",
    url: "https://criptonopix.app.br",
    description: `Cripto no Pix is a Brazil-based crypto brokerage platform that allows purchases of crypto via PIX, backed by the NIX token as a utility/reward mechanism`,
    chain: "Binance",
    logo: `${baseIconsUrl}/crypto-no-pix.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "nix",
    cmcId: "27220",
    category: "CeDeFi",
    chains: ["Binance"],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "criptonopix",
    audit_links: [],
    treasury: "cryptonopix.js"
  },
  {
    id: "6910",
    name: "Ethereal DEX",
    address: null,
    symbol: "USDe",
    url: "https://app.ethereal.trade/",
    description: `Ethereal is a non-custodial DEX for spot and perpetual contracts built on the Ethena Network, using USDe as the primary collateral and engineered for CEX-level performance with DeFi security`,
    chain: "Ethereal",
    logo: `${baseIconsUrl}/ethereal-dex.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Ethereal"],
    forkedFrom: [],
    oraclesBreakdown: [
      { name: "Pyth", type: "Primary", proof: ["https://docs.ethereal.trade/trading/perpetual-futures/price-oracles"] },
    ],
    module: "ethereal-dex/index.js",
    twitter: "etherealdex",
    audit_links: ["https://docs.ethereal.trade/protocol-reference/audits"],
    listedAt: 1761325469,
    dimensions: {
      derivatives: "ethereal-dex",
      fees: "ethereal-dex",
      "open-interest": "ethereal-oi",
    }
  },
  {
    id: "6911",
    name: "DFS V2",
    address: null,
    symbol: "-",
    url: "https://dfs.fun/swap",
    description: `DFS V2 is a decentralized exchange built on the XLayer Network.`,
    chain: "XLayer",
    logo: `${baseIconsUrl}/dfs-v2.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["XLayer"],
    forkedFrom: [],
    module: "dfs-v2/index.js",
    twitter: "dfsdotfun",
    audit_links: [],
    parentProtocol: "parent#dfs.fun",
    listedAt: 1761326214,
  },
  {
    id: "6912",
    name: "DFS V3",
    address: null,
    symbol: "-",
    url: "https://dfs.fun/swap",
    description: `DFS V3 is a decentralized exchange built on the XLayer Network.`,
    chain: "XLayer",
    logo: `${baseIconsUrl}/dfs-v3.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["XLayer"],
    forkedFrom: [],
    module: "dfs-v3/index.js",
    twitter: "dfsdotfun",
    audit_links: [],
    parentProtocol: "parent#dfs.fun",
    listedAt: 1761326219,
  },
  {
    id: "6913",
    name: "Feather",
    address: null,
    symbol: "-",
    url: "https://app.feather.zone/",
    description: `Feather delivers risk-adjusted, permissionless lending at scale. Its on-chain risk engine continuously calibrates collateral factors, liquidation thresholds, and oracle feeds—engineering capital efficiency without compromising safety`,
    chain: "Sei",
    logo: `${baseIconsUrl}/feather.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Sei"],
    forkedFrom: [],
    module: "feather/index.js",
    twitter: "Featherlend",
    audit_links: [],
    listedAt: 1761326231,
    dimensions: {
      fees: "feather"
    }
  },
  {
    id: "6914",
    name: "UltraYield by Edge",
    address: null,
    symbol: "-",
    url: "https://ultrayield.app/",
    description: "UltraYield, created by leading crypto hedge fund Edge Capital, offers sophisticated yield-generating vaults that make institutional-grade strategies accessible to everyone.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ultrayield-by-edge.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Ethereum", "TAC", "Base", "Optimism", "Hyperliquid L1", "Plume Mainnet", "Etherlink"],
    module: "ultrayield-by-edge-capital/index.js",
    oraclesBreakdown: [
      {
        name: "eOracle",
        type: "Primary",
        proof: ["https://github.com/DefiLlama/defillama-server/pull/10777"],
        chains: [{ chain: "TAC" }],
      },
    ],
    forkedFromIds: [],
    twitter: "ultrayieldapp",
    listedAt: 1761342069,
    dimensions: {
      fees: "edge-capital"
    },
  },
  {
    id: "6915",
    name: "PumpBase",
    address: null,
    symbol: "-",
    url: "https://pumpbase.site/",
    description: "PumpBase makes it effortless for anyone to create, trade, and grow onchain tokens. Every token launched through PumpBase follows a fair-launch model, ensuring equal access for all users — no insider allocations, no pre-mines, and no unfair advantages.",
    chain: "Base",
    logo: `${baseIconsUrl}/pumpbase.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    module: "PumpBase/index.js",
    forkedFromIds: [],
    twitter: "PumpBase_HQ",
    audit_links: ["https://spywolf.co/audits/Pumpbase_0x19798E390E69a36814B25BbBC7e75530E8a0A101.pdf"],
    github: ["PumpBase-Launchpad"],
    listedAt: 1761581949,
  },
  {
    id: "6916",
    name: "Collex",
    address: null,
    symbol: "-",
    url: "https://collex.fun/",
    description: "Collex utilizes DeFi with real-world collectibles, offering a seamless platform for tokenizing, trading, and leveraging your assets by staking. Collex empowers collectors with liquidity, transparency, and innovative DeFi opportunities.",
    chain: "Aptos",
    logo: `${baseIconsUrl}/collex.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Physical TCG",
    chains: ["Aptos"],
    module: "collex/index.js",
    forkedFromIds: [],
    twitter: "collexdotfun",
    listedAt: 1761581955,
    dimensions: {
      fees: "collex"
    }
  },
  {
    id: "6917",
    name: "Credible Finance",
    address: null,
    symbol: "-",
    url: "https://credible.finance/",
    description: "Credible Finance is a decentralized finance (DeFi) platform pioneering the integration of real-world assets (RWA) with blockchain technology. It enables users to borrow and lend crypto assets, primarily backed by tokenized real-world collateral, bridging traditional finance with the efficiency and transparency of decentralized ledgers. The platform focuses on providing access to capital for real-world entities while offering attractive yields to lenders, all within a permissioned and secure environment. Credible Finance leverages AI-powered credit scoring and ZK oracle nodes for real-time monitoring and underwriting.",
    chain: "0G",
    logo: `${baseIconsUrl}/credible-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA Lending",
    chains: ["0G"],
    module: "credible-finance/index.js",
    forkedFromIds: [],
    twitter: "crediblefin",
    listedAt: 1761584407,
  },
  {
    id: "6918",
    name: "Enosys Governance",
    address: null,
    symbol: "-",
    url: "https://enosys.global/products/governance",
    description: "Stake governance tokens to influence the platform's future, and earn yield from the APYCloud.",
    chain: "Songbird",
    logo: `${baseIconsUrl}/enosys-governance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Governance Incentives",
    chains: ["Songbird"],
    module: "enosys-governance/index.js",
    forkedFromIds: [],
    twitter: "enosys_global",
    parentProtocol: "parent#enosys",
    listedAt: 1761584412,
  },
  {
    id: "6919",
    name: "Wrapped HLP",
    address: "hyperliquid:0x1359b05241ca5076c9f59605214f4f84114c0de8",
    symbol: "wHLP",
    url: "https://www.loopingcollective.org/wrapped-hlp",
    description: "wHLP is a wrapped version of HyperLiquidity Provider (HLP), allowing users to earn trading fees from Hyperliquid while retaining full liquidity and DeFi composability on HyperEVM.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/wrapped-hlp.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "wrapped-hlp",
    cmcId: null,
    category: "Yield",
    chains: ["Hyperliquid L1"],
    module: "wrapped-hlp/index.js",
    forkedFromIds: [],
    twitter: "looping_col",
    audit_links: ["https://github.com/Ion-Protocol/nucleus-boring-vault/tree/master/audit"],
    listedAt: 1761584418,
    parentProtocol: "parent#looping-collective",
    dimensions: {
      fees: "wrapped-hlp",
    },
  },
  {
    id: "6920",
    name: "Exotic Markets",
    address: "solana:EXoMAHnw2Gw5fXJTektedLJDVn9vn8tLTEQX7gHccQKR",
    symbol: "EXO",
    url: "https://exotic.markets/",
    description: "Option and Derivatives infrastructure on Solana.",
    chain: "Solana",
    logo: `${baseIconsUrl}/exotic-markets.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Exotic Options",
    chains: ["Solana"],
    module: "exotic-markets/index.js",
    forkedFromIds: [],
    twitter: "exotic_markets_",
    listedAt: 1761584433,
  },
  {
    id: "6921",
    name: "Palomino Finance",
    address: null,
    symbol: "-",
    url: "https://palomino.fi/",
    description: "Palomino is Saga's native lending market, built to maximize capital velocity. By combining overcollateralized borrowing with Colt's subsidy mechanism, Palomino creates a lending environment where lenders earn more and borrowers pay less.",
    chain: "Saga",
    logo: `${baseIconsUrl}/palomino-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Saga"],
    module: "palomino-finance/index.js",
    forkedFromIds: ["1599"],
    oraclesBreakdown: [
      {
        name: "Tellor",
        type: "Primary",
        proof: ["https://github.com/DefiLlama/DefiLlama-Adapters/pull/16859"],
      },
    ],
    twitter: "PalominoFi",
    listedAt: 1761585807,
  },
  {
    id: "6922",
    name: "fomo",
    address: null,
    symbol: "-",
    url: "https://fomo.family/",
    description: "Fomo is a social trading app that enables self-custodial, gasless token swaps on mobile, combining social feeds and copy-trading features.",
    chain: "Solana",
    logo: `${baseIconsUrl}/fomo.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Trading App",
    chains: ["Solana"],
    module: "dummy.js",
    forkedFromIds: [],
    twitter: "tryfomo",
    dimensions: {
      fees: "fomo",
    }
  },
  {
    id: "6923",
    name: "Asseto CASH+",
    address: null,
    symbol: "-",
    url: "https://asseto.finance/#invest",
    description: "CASH+ is a 1:1 asset-backed token collateralized by the CMS USD Money Market Fund, which invests in high-quality short-term USD instruments. It offers both individual and institutional investors instant stablecoin liquidity combined with low-risk yields that track money-market rates.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/cash+.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    tags: ["Money Market Funds"],
    chains: ["Ethereum", "Binance"],
    module: "asseto-cashsplus/index.js",
    forkedFromIds: [],
    audit_links: ["https://reale-assets.gitbook.io/reale/smart-contract-audit"],
    twitter: "AssetoFinance",
    listedAt: 1761691834,
  },
  {
    id: "6924",
    name: "Rain",
    address: "arbitrum:0x25118290e6A5f4139381D072181157035864099d",
    symbol: "RAIN",
    url: "https://www.rain.one/",
    description: "Rain | Decentralized Prediction markets Protocol. Predict anything. Create markets. Trade options. Own the future!.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/rain.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "rain",
    cmcId: "38341",
    category: "Prediction Market",
    chains: ["Arbitrum"],
    module: "rain-one/index.js",
    forkedFromIds: [],
    audit_links: ["https://hacken.io/audits/rain/sca-rain-token-aug2025/"],
    twitter: "Rain__Protocol",
    github: ["rain1-labs"],
    listedAt: 1761692153,
    dimensions: {
      fees: "rain-one",
    }
  },
  {
    id: "6925",
    name: "Milkyway Restaking",
    address: null,
    symbol: "-",
    url: "https://app.milkyway.zone/restake",
    description: "Milkyway Restaking is a protocol that allows users to restake their assest.",
    chain: "Milkyway",
    logo: `${baseIconsUrl}/milkyway-restaking.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Restaking",
    chains: ["Milkyway"],
    module: "milky-way-restaking/index.js",
    forkedFromIds: [],
    twitter: "milkywayzone",
    parentProtocol: "parent#milkyway-protocol",
    tokensExcludedFromParent: {
      milkyway:["milkTIA"],
    },
    listedAt: 1761692463,
  },
  {
    id: "6926",
    name: "OPINION",
    address: null,
    symbol: "-",
    url: "https://app.opinion.trade?code=hV0KVj",
    referralUrl: "https://app.opinion.trade?code=hV0KVj",
    description: "Opinion is building a prediction exchange that enables direct trading of macroeconomic data, predictions, and news as standardized assets, leveraging proprietary on-chain infrastructure, AI Oracle, and trading tools to create new opportunities for retail users, institutions, and global decision makers in democratizing economic insights and risk management.",
    chain: "Binance",
    logo: `${baseIconsUrl}/opinion.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Prediction Market",
    chains: ["Binance"],
    module: "opinion/index.js",
    forkedFromIds: [],
    audit_links: [
      "https://static.opinion.trade/opinion-v1-scalebit.pdf",
      "https://static.opinion.trade/opinion-v1-zellic.pdf",
    ],
    twitter: "opinionlabsxyz",
    listedAt: 1761694223,
    dimensions: {
      dexs: "opinion",
      fees: "opinion"
    }
  },
  {
    id: "6927",
    name: "Juris Protocol",
    address: "terra:terra1vhgq25vwuhdhn9xjll0rhl2s67jzw78a4g2t78y5kz89q9lsdskq2pxcj2",
    symbol: "JURIS",
    url: "https://www.jurisprotocol.com",
    description: "A comprehensive DeFi protocol on Terra Classic offering staking and lending services with a focus on LUNC ecosystem development.",
    chain: "Terra",
    logo: `${baseIconsUrl}/juris-protocol.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "juris-protocol",
    cmcId: null,
    category: "Yield",
    chains: ["Terra"],
    module: "jurisprotocol/index.js",
    forkedFromIds: [],
    audit_links: [
      "https://app.solidproof.io/projects/juris-protocol?audit=963e1452-fcff-4a08-9618-72cf949c9419",
    ],
    twitter: "JurisProtocol",
    github: ["jurisprotocol"],
    listedAt: 1761694872,
  },
  {
    id: "6928",
    name: "Titan Exchange",
    address: null,
    symbol: "-",
    url: "https://titan.exchange/",
    description: "Meta DEX Aggregator on Solana.",
    chain: "Solana",
    logo: `${baseIconsUrl}/titan-exchange.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "Titan_Exchange",
    dimensions: {
      aggregators: "titan-exchange",
    },
  },
  {
    id: "6929",
    name: "KFC DEX",
    address: "kasplex:0xf87e587AB945F7B111329a6ace6dc497D34f098B",
    symbol: "KFC",
    url: "https://app.kaspafinance.io/swap",
    description: "Discover the most used AMM on KASPLEX and IGRA Caravel! Farm KFC tokens, take part in innovative token launches through Initial Farm Offerings by Kaspa Finance, collect unique NFTs, and enjoy a reliable, community-driven platform.",
    chain: "Kasplex",
    logo: `${baseIconsUrl}/kfc-dex.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Kasplex"],
    forkedFromIds: ["2198"],
    module: "kfc.js",
    twitter: "KaspaFinance",
    listedAt: 1761765898
  },
  {
    id: "6930",
    name: "TaoFi",
    address: null,
    symbol: "-",
    url: "https://www.taofi.com/swap",
    description: "CLMM Dex on Bittensor EVM.",
    chain: "Bittensor EVM",
    logo: `${baseIconsUrl}/taofi.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Bittensor EVM"],
    module: "taofi/index.js",
    forkedFromIds: ["2198"],
    twitter: "_taofi_",
    listedAt: 1761770951
  },
  {
    id: "6931",
    name: "MoneyX",
    address: "bsc:0x4ffe5ec4d8b9822e01c9e49678884baec17f60d9",
    symbol: "MONEY",
    url: "https://moneyxpro.com",
    description: "MoneyX is a derivatives and perpetuals exchange under the BESC ecosystem, offering 100x leveraged trading, swap markets, and yield vaults powered by BESC infrastructure.",
    chain: "Binance",
    logo: `${baseIconsUrl}/moneyx.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Binance"],
    oraclesBreakdown: [
      {
        name: "Chainlink",
        type: "Primary",
        proof: ["https://github.com/DefiLlama/dimension-adapters/pull/4544"],
      },
      {
        name: "BESC Oracle",
        type: "Secondary",
        proof: ["https://github.com/DefiLlama/dimension-adapters/pull/4544"],
      },
    ],
    module: "dummy.js",
    twitter: "BESCLLC",
    dimensions: {
      fees: "moneyx-pro",
      derivatives: "moneyx-pro",
    },
  },
  {
    id: "6932",
    name: "FlowSwap V2",
    address: null,
    symbol: "-",
    url: "https://flowswap.io",
    description: "Uniswap V2 fork",
    chain: "Flow",
    logo: `${baseIconsUrl}/flowswap-v2.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Flow"],
    module: "flow-swap-v2/index.js",
    twitter: "flow_blockchain",
    forkedFromIds: ["2197"],
    parentProtocol: "parent#flow-swap",
    listedAt: 1761871975,
    dimensions: {
      dexs: "flowswap-v2"
    },
  },
  {
    id: "6933",
    name: "FlowSwap V3",
    address: null,
    symbol: "-",
    url: "https://flowswap.io",
    description: "Uniswap V3 fork",
    chain: "Flow",
    logo: `${baseIconsUrl}/flowswap-v3.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Flow"],
    module: "flow-swap-v3/index.js",
    twitter: "flow_blockchain",
    forkedFromIds: ["2198"],
    parentProtocol: "parent#flow-swap",
    listedAt: 1761871981,
    dimensions: {
      dexs: "flowswap-v3",
      fees: "flowswap-v3",
    }
  },
  {
    id: "6934",
    name: "Tanken Capital",
    address: null,
    symbol: "-",
    url: "https://tankencapital.notion.site/Tanken-Capital-1841505ced0680d88c31feb5f6f83433",
    description: "Tanken Capital operates on-chain vaults that allocate assets across multiple DeFi protocols. Strategies follow risk and allocation frameworks based on on-chain data and quantitative analysis.",
    chain: "Base",
    logo: `${baseIconsUrl}/tanken-capital.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Base", "Ethereum"],
    module: "tanken-capital/index.js",
    twitter: "tankencapital",
    forkedFromIds: [],
    listedAt: 1761880281,
  },
  {
    id: "6935",
    name: "Binance Wallet",
    address: null,
    symbol: "-",
    url: "https://web3.binance.com/",
    description: "Binance Wallet is a self-custody (non-custodial) crypto wallet built by Binance.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/binance-wallet.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Wallets",
    chains: ["Ethereum", "Arbitrum", "Polygon", "Optimism", "Base", "Avalanche", "Binance", "Solana", "Linea", "Sonic", "zkSync Era", "Plasma"],
    module: "dummy.js",
    twitter: "BinanceWallet",
    dimensions: {
      aggregators: "binancewallet",
    }
  },
  {
    id: "6936",
    name: "Superstack",
    address: null,
    symbol: "-",
    url: "https://superstack.xyz/",
    description: "Superstack is a custom-built trading platform, bringing institutional-grade tools and capital efficiency to everyone.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/superstack.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    module: "dummy.js",
    twitter: "superstackxyz",
    forkedFromIds: [],
    dimensions: {
      fees: "superstack",
      derivatives: "superstack",
    }
  },
  {
    id: "6937",
    name: "Shroomy Protocol Swap",
    address: "ink:0x0c5e2d1c98cd265c751e02f8f3293bc5764f9111",
    symbol: "SHROOMY",
    url: "https://app.shroomy.io/",
    description:
      "Shroomy Protocol is a decentralized, non-custodial liquidity protocol where users can participate as suppliers or borrowers. Suppliers provide liquidity to the market to earn passive income, while borrowers can borrow in an overcollateralized manner.",
    chain: "Ink",
    logo: `${baseIconsUrl}/shroomy-protocol-swap.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Ink"],
    forkedFromIds: ["2116"],
    module: "dummy.js",
    twitter: "ShroomyProject",
    parentProtocol: "parent#shroomy-protocol",
    dimensions: {
      dexs: "shroomy-protocol",
      fees: "shroomy-protocol",
    }
  },
  {
    id: "6938",
    name: "Movement Bridge",
    address: "0x3073f7aaa4db83f95e9fff17424f71d4751a3073",
    symbol: "MOVE",
    url: "https://bridge.movementnetwork.xyz/",
    description:
      "Movement Bridge is a bridge that allows you to move your tokens between the Movement and Ethereum chains.",
    chain: "Movement",
    logo: `${baseIconsUrl}/movement-bridge.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Movement"],
    forkedFromIds: [],
    module: "dummy.js",
    twitter: "MoveIndFDN",
  },
  {
    id: "6939",
    name: "DoubleZero Network",
    address: "solana:J6pQQ3FAcJQeWPPGppWRb4nM8jU3wLyYbRrLh7feMfvd",
    symbol: "2Z",
    url: "https://doublezero.xyz/",
    description:
      "DoubleZero is a permissionless global infrastructure network for blockchains and distributed systems, enabling contributors to stake assets and provide high-performance bandwidth/fiber links in exchange for utility tokens that power the network.",
    chain: "Solana",
    logo: `${baseIconsUrl}/doublezero-network.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Developer Tools",
    chains: ["Solana"],
    forkedFromIds: [],
    module: "dummy.js",
    twitter: "doublezero",
    parentProtocol: "parent#doublezero",
    dimensions: {
      fees: "doublezero"
    }
  },
  {
    id: "6940",
    name: "Volo LST",
    address: "sui:0xa99b8952d4f7d947ea77fe0ecdcc9e5fc0bcab2841d6e2a5aa00c3044e5544b5::navx::NAVX",
    symbol: "NAVX",
    assetToken: "vSUI",
    url: "https://www.volo.fi/",
    description:
      "Volo is the go-to Earn Hub for all your assets on Sui that offers much more than its established status in offering its fully decentralized LST Sui (vSui). Volo is expanding to offering vaults of all major assets on Sui especially BTCFi-related token that allows users to simply earn yield on their assets with one click.",
    chain: "Sui",
    logo: `${baseIconsUrl}/volo-lst.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Sui"],
    forkedFromIds: [],
    module: "volo-lst/index.js",
    parentProtocol: "parent#navi-protocol",
    twitter: "volo_sui",
  },
  {
    id: "6941",
    name: "THORSwap",
    address: "0xa5f2211b9b8170f694421f2046281775e8468044",
    symbol: "THOR",
    url: "https://www.thorswap.finance/",
    description:
      "Established in 2021, THORSwap is the leading multi-chain Bitcoin decentralized exchange (DEX) aggregator. Swap cross-chain to and from Native Bitcoin in a non-KYC and non-custodial manner.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/thorswap.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "thorswap",
    cmcId: "12942",
    category: "DEX Aggregator",
    chains: ["Ethereum"],
    forkedFromIds: [],
    audit_links: ["https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-THORSwap-v1.0.pdf"],
    module: "thorswap/index.js",
    twitter: "thorswap",
    listedAt: 1762192599
  },
  {
    id: "6942",
    name: "Aerodrome Ignition",
    address: "base:0x940181a94A35A4569E4529A3CDfB74e38FD98631",
    symbol: "AERO",
    url: "https://aerodrome.finance/",
    description: "Aerodrome Ignition is a DEX-native token launch mechanism on Base that bootstraps liquidity by depositing 10-20% of a project's token supply into Aerodrome pools, allowing veAERO holders to direct emissions incentives and enabling fair, market-driven price discovery and distribution without presales or private allocations",
    chain: "Base",
    logo: `${baseIconsUrl}/aerodrome-ignition.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    forkedFromIds: [],
    module: "aerodrome-ignition/index.js",
    twitter: "aerodromefi",
    parentProtocol: "parent#aerodrome",
    listedAt: 1762203887
  },
  {
    id: "6943",
    name: "Brotocol",
    address: null,
    symbol: "-",
    url: "https://brotocol.xyz/bridge/cross-bridge",
    description: "Brotocol Bridge is a MPC-based hybrid bi-directional bridge that acts as a 'connector' between Bitcoin and other blockchains, enabling seamless asset transfers and swaps between Bitcoin and its Layer 2 networks (L2s) as well as other blockchain ecosystems",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/brotocol.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Bridge Aggregator",
    chains: ["Bitcoin", "AILayer", "Arbitrum", "Aurora", "Avalanche", "Base", "Bitlayer", "Binance", "BOB", "Bsquared", "CORE", "Ethereum", "Linea", "Manta", "Merlin", "Mezo", "Mode", "Solana", "Stacks", "X Layer"],
    forkedFromIds: [],
    audit_links: ["https://docs.brotocol.xyz/developers/brotocol-contracts/security-audits"],
    module: "brotocol/index.js",
    twitter: "Brotocol_xyz",
    dimensions: {
      "bridge-aggregators": "brotocol"
    }
  },
  {
    id: "6944",
    name: "Kensei",
    address: null,
    symbol: "-",
    url: "https://www.kensei.one/",
    description: "Reputation-powered memecoin launchpad on Katana.",
    chain: "Katana",
    logo: `${baseIconsUrl}/kensei.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Katana"],
    forkedFromIds: [],
    audit_links: ["https://github.com/kenseionkatana/home/tree/main/audit"],
    module: "dummy.js",
    twitter: "kenseionkatana",
    dimensions: {
      fees: "kensei",
      dexs: "kensei",
    }
  },
  {
    id: "6945",
    name: "Unlock Protocol",
    address: null,
    symbol: "-",
    url: "https://unlock-protocol.com/",
    description: "Unlock is an open source protocol for onchain memberships & subscriptions",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/unlock-protocol.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    chains: ["Ethereum", "Optimism", "Binance", "xDai", "Polygon", "Base", "Arbitrum", "Celo", "Avalance", "Linea", "zkSync Era", "Polygon zkEVM", "Scroll"],
    forkedFromIds: [],
    module: "dummy.js",
    twitter: "UnlockProtocol",
    dimensions: {
      fees: "unlock-protocol"
    }
  },
  {
    id: "6946",
    name: "Carina Aggregator",
    address: null,
    symbol: "-",
    url: "https://app.carina.finance/",
    description: "Carina is an intent-based DEX aggregator that turns routing into a solver competition — delivering best execution, and no platform fees",
    chain: "Sei",
    logo: `${baseIconsUrl}/carina-aggregator.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Sei"],
    forkedFromIds: [],
    audit_links: [
      "https://github.com/CODESPECT-security/audit-reports/blob/main/038_CODESPECT_CARINA.pdf",
      "https://github.com/Zellic/publications/blob/master/Carina%20Smart%20Contracts%20-%20Zellic%20Audit%20Report.pdf"
    ],
    module: "dummy.js",
    twitter: "carina_finance",
    dimensions: {
      aggregators: "carina-aggregator"
    }
  },
  {
    id: "6947",
    name: "P2P.me",
    address: null,
    symbol: "-",
    url: "https://www.p2p.me/en",
    description: "P2P.me is a decentralized, non-custodial platform that enables users to swap fiat and USDC using QR codes",
    chain: "Polygon",
    logo: `${baseIconsUrl}/p2p.me.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    chains: ["Polygon"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "P2Pdotme",
    dimensions: {
      fees: "p2pme"
    }
  },
  {
    id: "6948",
    name: "Obol",
    address: "0x0b010000b7624eb9b3dfbc279673c76e9d29d5f7",
    symbol: "OBOL",
    url: "https://obol.org/",
    description: "The Obol Collective is the largest Decentralized Operator Ecosystem. Powered by Obol Distributed Validators, the end game of Ethereum staking.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/obol.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "obol-2",
    cmcId: "36278",
    category: "Staking Pool",
    chains: ["Ethereum"],
    forkedFromIds: [],
    audit_links: [],
    module: "obol/index.js",
    twitter: "Obol_Collective",
    listedAt: 1762287672
  },
  {
    id: "6949",
    name: "Vaultedge",
    address: null,
    symbol: "-",
    url: "https://www.vaultedge.fi/",
    description: "Vaultedge is a decentralized borrowing protocol built around yield-generating vaults that optimize returns across the deployed chain. Users can borrow the protocol’s stablecoin, USDVE, against crypto collateral with 0% interest and a one-time borrow fee, while their assets continue to earn yield",
    chain: "Plasma",
    logo: `${baseIconsUrl}/vaultedge.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Plasma"],
    forkedFromIds: ["270"],
    oraclesBreakdown: [
      {
        name: "Chainlink",
        type: "Primary",
        proof: ["https://github.com/DefiLlama/DefiLlama-Adapters/pull/16915", "https://docs.vaultedge.fi/the-protocol/info-and-security/oracles"]
      },
      {
        name: "RedStone",
        type: "Fallback",
        proof: ["https://github.com/DefiLlama/DefiLlama-Adapters/pull/16915"]
      }
    ],
    audit_links: [
      "https://www.gravitaprotocol.com/audits/gravita-audit-report-dedaub-apr-23-2023.pdf",
      "https://www.gravitaprotocol.com/audits/gravita-audit-report-omniscia-may-17-2023.pdf"
    ],
    module: "vaultedge/index.js",
    twitter: "VaultedgeFi",
    listedAt: 1762287949
  },
  {
    id: "6950",
    name: "BESCSWAP DEX",
    address: null,
    symbol: "-",
    url: "https://bescswap.com/",
    description: "BESCSWAP DEX is a decentralized exchange on BESC Hyperchain that allows users to swap tokens with low fees and high liquidity.",
    chain: "BESC Hyperchain",
    logo: `${baseIconsUrl}/bescswap-dex.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["BESC Hyperchain"],
    forkedFromIds: ["2197"],
    audit_links: [],
    module: "bescswap/index.js",
    twitter: "BESCLLC",
    listedAt: 1762288314
  },
  {
    id: "6951",
    name: "Dreamcash",
    address: null,
    symbol: "-",
    url: "https://www.dreamcash.xyz/",
    description: "Dreamcash is a decentralized exchange on Hyperliquid L1 that allows users to swap tokens with low fees and high liquidity.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/dreamcash.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "Dreamcash",
    dimensions: {
      fees: "dreamcash",
      derivatives: "dreamcash"
    }
  },
  {
    id: "6952",
    name: "HyperSignals",
    address: null,
    symbol: "-",
    url: "https://hypersignals.ai/",
    description: "HyperSignals is an on-chain trading analytics platform built on Hyperliquid and powered by Biconomy. It aggregates trader activity and market data to generate actionable trading signals, allowing users to track top traders, monitor whale positions, and analyze performance profiles, with upcoming support for strategy copying and risk controls.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/hypersignals.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "HyperSignals_ai",
    dimensions: {
      fees: "hypersignals",
      derivatives: "hypersignals"
    }
  },
  {
    id: "6953",
    name: "Liminal Perps",
    address: null,
    symbol: "-",
    url: "https://liminal.money/",
    description: "Liminal Perps allows users to trade via on-chain perpetual futures on Hyperliquid L1.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/liminal-perps.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "liminalmoney",
    dimensions: {
      fees: "liminal-perps",
      derivatives: "liminal-perps"
    }
  },
  {
    id: "6954",
    name: "Supercexy",
    address: null,
    symbol: "-",
    url: "https://supercexy.com/",
    description: "Supercexy is a decentralized exchange built on Hyperliquid L1 that allows users to trade via on-chain perpetual futures.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/supercexy.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "try_supercexy",
    dimensions: {
      fees: "supercexy",
      derivatives: "supercexy"
    }
  },
  {
    id: "6955",
    name: "Bullpen",
    address: null,
    symbol: "-",
    url: "https://app.bullpen.fi/",
    description: "Trade anything onchain.  Powered by Hyperliquid, Solana, and (Redacted).",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/bullpen.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "BullpenFi",
    dimensions: {
      fees: "bullpenfi-perps",
      derivatives: "bullpenfi-perps"
    }
  },
  {
    id: "6956",
    name: "Infinex",
    address: null,
    symbol: "-",
    url: "https://infinex.xyz/",
    description: "The most CEX-like trading experience onchain. Powered by Hyperliquid.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/infinex.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "infinex",
    dimensions: {
      fees: "infinex-perps",
      derivatives: "infinex-perps"
    }
  },
  {
    id: "6957",
    name: "Clarity",
    address: "cardano:1e76aaec4869308ef5b61e81ebf229f2e70f75a50223defa087f807b",
    symbol: "CLARITY",
    url: "https://www.clarity.community/",
    description: "Clarity is a DAO tooling platform on Cardano.",
    chain: "Cardano",
    logo: `${baseIconsUrl}/clarity.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "clarity-2",
    cmcId: null,
    category: "DAO Service Provider",
    chains: ["Cardano"],
    forkedFromIds: [],
    audit_links: ["https://github.com/Liqwid-Labs/agora/blob/staging/Agora%20audit%20report-v1.0.pdf"],
    module: "clarity/index.js",
    twitter: "clarity_dao",
    github: ["ClearContracts"],
    listedAt: 1762301111,
  },
  {
    id: "6958",
    name: "PotatoSwap V3",
    address: null,
    symbol: "-",
    url: "https://potatoswap.finance",
    description: "Discover Liquidity. Or Potatoes. Or a DEX + Launchpad natively built for the XLayerOfficial ecosystem.",
    chain: "X Layer",
    logo: `${baseIconsUrl}/potatoswap-v3.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["X Layer"],
    forkedFromIds: ["2198"],
    audit_links: [],
    module: "potatoswap-v3/index.js",
    twitter: "PotatoSwap_Fi",
    listedAt: 1762301497,
    parentProtocol: "parent#potatoswap",
    dimensions: {
      dexs: "potatoswap-v3",
      fees: "potatoswap-v3",
    }
  },
  {
    id: "6959",
    name: "Lucky Peaches",
    address: null,
    symbol: "-",
    url: "http://luckypeach.xyz/",
    description: "Lucky Peaches is a fun decentralized lending protocol where you can lend your assets and win Peaches.",
    chain: "Hemi",
    logo: `${baseIconsUrl}/lucky-peaches.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Hemi"],
    forkedFromIds: ["111"],
    audit_links: [],
    module: "luckypeaches/index.js",
    twitter: "luckypeachxyz",
    github: ["luckypeachxyz"],
    listedAt: 1762301789,
  },
  {
    id: "6961",
    name: "OroSwap",
    address: null,
    symbol: "-",
    url: "https://www.oroswap.org",
    description: "OroSwap is an AI-powered automated market maker (AMM) DEX on ZigChain with multiple pool types and fee tiers.",
    chain: "ZIGChain",
    logo: `${baseIconsUrl}/oroswap.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["ZIGChain"],
    forkedFromIds: [],
    audit_links: ["https://www.halborn.com/audits/oroswap/cosmwasm-contracts-632648"],
    module: "oroswap/index.js",
    twitter: "oroswap",
    github: ["oroswap"],
    listedAt: 1762322081,
  },
  {
    id: "6962",
    name: "DFlow",
    address: null,
    symbol: "-",
    url: "https://dflow.net/",
    description: "High-precision, low-latency Solana DEX aggregator.",
    chain: "Solana",
    logo: `${baseIconsUrl}/dflow.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Solana"],
    forkedFromIds: [],
    audit_links: [],
    module: "dummy.js",
    twitter: "DFlowProtocol",
    dimensions: {
      aggregators: "dflow"
    }
  },
  {
    id: "6963",
    name: "RockSolid Network",
    address: null,
    symbol: "-",
    url: "https://rocksolid.network/",
    description: "RockSolid is a single-click integrated DeFi Vault platform that makes it simple for users to access the best DeFi rewards.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/rocksolid-network.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    forkedFromIds: [],
    audit_links: [],
    module: "RockSolid/index.js",
    twitter: "rocksolidhq",
    listedAt: 1762370739,
  },
  {
    id: "6964",
    name: "Makina",
    address: null,
    symbol: "-",
    url: "https://app.makina.finance/",
    description: "Makina the most advanced DeFi Execution Engine empowering sophisticated Operators to execute onchain yield strategies which maximize risk-adjusted return.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/makina-finance.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Ethereum"],
    forkedFromIds: [],
    audit_links: ["https://docs.makina.finance/concepts/security/audits"],
    module: "makina-finance/index.js",
    twitter: "makinafi",
    github: ["MakinaHQ"],
    listedAt: 1762370744,
  },
  {
    id: "6965",
    name: "KaspaCom Dex",
    address: null,
    symbol: "-",
    url: "https://defi.kaspa.com/swap",
    description: "KaspaCom, The Leading Kaspa DEX & Token Launchpad for the Community, by the Community.",
    chain: "Kasplex",
    logo: `${baseIconsUrl}/kaspacom-dex.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Kasplex"],
    forkedFromIds: ["2197"],
    audit_links: ["https://drive.google.com/file/d/1et35wfvZXSblkG1tF9OPwmdZ9ix7Jxp8/view"],
    module: "kaspacom-dex/index.js",
    twitter: "KaspaCom",
    github: ["KASPACOM"],
    listedAt: 1762370751,
  },
  {
    id: "6966",
    name: "TurboFlow",
    address: null,
    symbol: "-",
    url: "https://www.turboflow.xyz/home",
    description: "The most retail-friendly PerpDEX, where retail trades like pros.",
    chain: "Binance",
    logo: `${baseIconsUrl}/turboflow.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Binance", "Solana"],
    forkedFromIds: [],
    audit_links: [],
    module: "turboflow/index.js",
    twitter: "TurboFlow_xyz",
    listedAt: 1762370757,
  },
  {
    id: "6967",
    name: "DipCoin Perps",
    address: null,
    symbol: "-",
    url: "https://www.dipcoin.io/perp/",
    description:
      "Dipcoin is the next-generation decentralized exchange (DEX) built on Sui, combining the speed and simplicity of a centralized exchange (CEX) with the transparency and control of DeFi. It’s designed to make crypto trading fast, human, and confidence-driven, offering guided perpetuals, sub-second execution, and true self-custody - all in one seamless platform. Confidence in Every Trade. True self-custody. Fast, simple, and human - trade smarter, win bigger.",
    chain: "Sui",
    logo: `${baseIconsUrl}/dipcoin-perps.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Sui"],
    module: "dipcoin-perps/index.js",
    forkedFrom: [],
    audit_links: ["https://www.dipcoin.io/doc/DipCoin_Audit_Report.pdf"],
    twitter: "DipCoinOfficial",
    parentProtocol: "parent#dipcoin",
    listedAt: 1762461479,
    dimensions: {
      fees: "dipcoin-perps",
      derivatives: "dipcoin-perps",
    }
  },
  {
    id: "6968",
    name: "PumpSpace",
    address: null,
    symbol: "-",
    url: "https://pumpspace.io/",
    description: "PumpSpace is a decentralized liquidity platform on Avalanche supporting both V2 and V3 (Trident) AMM models, offering multi-token farms and on-chain yield optimization for community-driven tokens.",
    chain: "Avalanche",
    logo: `${baseIconsUrl}/pumpspace.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Avalanche"],
    oracles: [],
    forkedFromIds: ["2197"],
    module: "pumpspace/index.js",
    twitter: "pumpspace10000",
    audit_links: [
      "https://www.cyberscope.io/audits/pumpspace?assessmentIndex=1https://github.com/cyberscope-io/audits/blob/main/pumpspace/dexAudit.pdf",
      "https://github.com/cyberscope-io/audits/blob/main/pumpspace/audit.pdf"
    ],
    listedAt: 1762462075,
  },
  {
    id: "6969",
    name: "AquaBank",
    address: null,
    symbol: "-",
    url: "https://aquabank.io/",
    description: "AquaBank is a USDT deposit and yield system on Avalanche that automatically generates returns through trusted DeFi protocols like Benqi and Euler.",
    chain: "Avalanche",
    logo: `${baseIconsUrl}/aquabank.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Avalanche"],
    module: "aquabank/index.js",
    twitter: "Aquabank2025",
    audit_links: ["https://github.com/cyberscope-io/audits/blob/main/ab/audit.pdf"],
    listedAt: 1762462187,
  },
  {
    id: "6970",
    name: "Utopia",
    address: "bsc:0xd83c128e7498be555845a6dc331a99e1524c1777",
    symbol: "UTOPIA",
    url: "https://www.utopiabnb.com",
    description: "Hire Explorers to seek out the Utopia universe and earn daily BNB rewards.",
    chain: "Binance",
    logo: `${baseIconsUrl}/utopia.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "utopia-3",
    cmcId: "38851",
    category: "Ponzi",
    chains: ["Binance"],
    module: "utopia/index.js",
    twitter: "UtopiaBNB",
    audit_links: ["https://github.com/cyberscope-io/audits/blob/main/1-utopia/miner.pdf"],
    listedAt: 1762462477,
  },
  {
    id: "6971",
    name: "Rocky",
    address: null,
    symbol: "-",
    url: "https://rocky.cash/",
    description: "Rocky is an over-collateralized, decentralized, modular & capital-efficient stablecoins protocol deployed on several chains. Each stablecoin can be minted against an approved basket of yield generating correlated assets at the oracle price and redeemed for it without cooldown.",
    chain: "Sei",
    logo: `${baseIconsUrl}/rocky.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Sei"],
    module: "rocky/index.js",
    twitter: "rockydotcash",
    forkedFromIds: ["756"],
    audit_links: ["https://docs.rocky.cash/security/audits"],
    github: ["rocky-protocol"],
    listedAt: 1762462631,
  },
  {
    id: "6972",
    name: "InSwap",
    address: null,
    symbol: "-",
    url: "https://app.inswap.ai/",
    description: "Decentralized exchange on X Layer.",
    chain: "X Layer",
    logo: `${baseIconsUrl}/inswap.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["X Layer"],
    forkedFromIds: ["2197"],
    module: "inswap/index.js",
    twitter: "INSWAPxlayer",
    audit_links: [],
    listedAt: 1762463492,
  },
  {
    id: "6973",
    name: "Zenrock Bridge",
    address: "solana:5VsPJ2EG7jjo3k2LPzQVriENKKQkNUTzujEzuaj4Aisf",
    symbol: "ROCK",
    url: "https://www.zenrocklabs.io/",
    description: "Zenrock is building the decentralized custody standard for the onchain economy, replacing centralized vaults with distributed multi-party computation (dMPC) that eliminates single points of failure. Through its Decentralized Custody Token (DCT) standard and purpose-built zrChain Layer 1, Zenrock creates secure, yield-bearing wrapped assets like zenBTC and zenZEC that are issued on Solana. By anchoring custody to simple wallet infrastructure secured by cryptography rather than trusted intermediaries, Zenrock transforms custody from crypto's most fragile layer into its strongest.",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/zenrock.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Bitcoin"],
    forkedFromIds: [],
    module: "zenrock/index.js",
    twitter: "zenrock",
    audit_links: [],
    listedAt: 1762582037,
  },
  {
    id: "6974",
    name: "Lombard BTC.b",
    address: null,
    symbol: "-",
    url: "https://www.lombard.finance/products-btcb/",
    description:
      "BTC.b — is Bitcoin, bridged — decentralized, non-custodial, permissionless Bitcoin for DeFi",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/lombard-btc.b.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Bitcoin"],
    forkedFromIds: [],
    module: "lombard-btcb/index.js",
    audit_links: [],
    twitter: "Lombard_Finance",
    parentProtocol: "parent#lombard-finance",
    listedAt: 1762584613, 
   },
  //  {
  //   id: "6975",
  //   name: "Astros Perp",
  //   address: null,
  //   symbol: "-",
  //   url: "https://astros.ag/perp",
  //   description:
  //     "Astros Perp DEX is the next-generation on-chain perp dex on the Sui Network to deliver unmatched performance and scalability.",
  //   chain: "Sui",
  //   logo: `${baseIconsUrl}/astros-perp.jpg`,
  //   audits: "2",
  //   audit_note: null,
  //   gecko_id: null,
  //   cmcId: null,
  //   category: "Derivatives",
  //   chains: ["Sui"],
  //   module: "astros-perp/index.js",
  //   twitter: "astros_ag",
  //   forkedFromIds: [],
  //   audit_links: ["https://files.gitbook.com/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FEagmjVMVJsuZQ0TvRYt7%2Fuploads%2Fg2IKp2ER5qhU3uX1Nr85%2F20250311-Navi-Perp-Vault-Final-Audit-Report.pdf?alt=media&token=34b676be-3da6-4be3-bce5-7a31bd214d5f"],
  //   listedAt: 1762584873,
  //   parentProtocol: "parent#navi-protocol",
  // },
  {
    id: "6975",
    name: "B-Lucky",
    address: "bsc:0x67b47971426bb2180453b3993ff2ec319e704444",
    symbol: "LUCKY",
    url: "https://b-lucky.gg/",
    description:
      "B-Lucky is revolutionizing the lottery industry by bringing it fully on-chain. Unlike traditional lotteries that operate behind closed doors, our protocol is completely transparent, trustless, and permissionless. Built on the Binance Smart Chain, B-Lucky leverages blockchain technology to ensure fairness, transparency, and instant payouts. Every draw, every ticket, and every prize is verifiable on-chain.",
    chain: "Binance",
    logo: `${baseIconsUrl}/b-lucky.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "lucky",
    cmcId: null,
    category: "Luck Games",
    chains: ["Binance"],
    module: "b-lucky/index.js",
    twitter: "BLuckygg",
    forkedFromIds: [],
    audit_links: ["https://b-lucky.gg/audit/bailsec.pdf"],
    listedAt: 1762585347,
  },
  {
    id: "6976",
    name: "DoubleZero Staked SOL",
    address: "solana:J6pQQ3FAcJQeWPPGppWRb4nM8jU3wLyYbRrLh7feMfvd",
    symbol: "2Z",
    assetToken: "dzSOL",
    url: "https://doublezero.xyz/",
    description:
      "DoubleZero Staked SOL is a staking pool on the Solana network that allows users to stake their SOL and earn rewards.",
    chain: "Solana",
    logo: `${baseIconsUrl}/doublezero-staked-sol.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Solana"],
    module: "dz-sol/index.js",
    twitter: "doublezero",
    forkedFromIds: [],
    parentProtocol: "parent#doublezero",
    audit_links: [],
    dimensions: {
      fees: "doublezero-staked-sol",
    },
    listedAt: 1762996533,
  },
  {
    id: "6977",
    name: "Astros Perp",
    address: null,
    symbol: "-",
    url: "https://astros.ag/perp",
    description:
      "Astros Perp DEX is the next-generation on-chain perp dex on the Sui Network to deliver unmatched performance and scalability.",
    chain: "Sui",
    logo: `${baseIconsUrl}/astros-perp.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Sui"],
    module: "astros-perp/index.js",
    twitter: "astros_ag",
    forkedFromIds: [],
    oraclesBreakdown: [
      { name: "Pyth", type: "Primary", proof: ["https://naviprotocol.gitbook.io/astros/astros-perpetual/perpetual-trading/index-and-mark-price#aggregation-sources"] }, 
    ],
    audit_links: ["https://files.gitbook.com/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FEagmjVMVJsuZQ0TvRYt7%2Fuploads%2Fg2IKp2ER5qhU3uX1Nr85%2F20250311-Navi-Perp-Vault-Final-Audit-Report.pdf?alt=media&token=34b676be-3da6-4be3-bce5-7a31bd214d5f"],
    listedAt: 1762584873,
    parentProtocol: "parent#navi-protocol",
  },
  {
    id: "6978",
    name: "BounceBit Prime",
    address: null,
    symbol: "-",
    url: "https://prime.bouncebit.io/",
    description:
      "Build structured positions in Franklin's Benji & BlackRock BUIDL. Holdings remain in custody while Prime deploys them as collateral and runs delta-neutral strategies for you across approved venues.",
    chain: "Binance",
    logo: `${baseIconsUrl}/bouncebit-prime.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Basis Trading",
    chains: ["Binance", "Ethereum"],
    module: "bouncebit-prime/index.js",
    twitter: "bounce_bit",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762794529,
  },
  {
    id: "6979",
    name: "Aerostrategy",
    address: "base:0x1A85b97F8b0E1CEE4D5500E093F5970a2aeB3fB8",
    symbol: "AEROSTRAT",
    url: "https://www.aerostrategy.finance/",
    description:
      "Aerostrategy channels trading volume into permanent veAERO and converts its weekly voting rewards into an accelerating AEROSTRAT burn.",
    chain: "Base",
    logo: `${baseIconsUrl}/aerostrategy.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "ve-Incentive Automator",
    chains: ["Base"],
    module: "aerostrategy/index.js",
    twitter: "AEROstrategyFi",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762801662,
  },
  {
    id: "6980",
    name: "HyperLoan",
    address: null,
    symbol: "-",
    url: "https://www.hyperloan.app/",
    description:
      "HyperLoan is a decentralised non-custodial lending protocol built on BESC HyperChain where users can participate as suppliers or borrowers. Suppliers provide liquidity to the market while earning interest, and borrowers can access liquidity by providing collateral that exceeds the borrowed amount.",
    chain: "BESC",
    logo: `${baseIconsUrl}/hyperloan.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["BESC"],
    module: "hyperloan/index.js",
    twitter: "hyperloanapp",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762801829,
  },
  {
    id: "6981",
    name: "Mr. Lightspeed Creator Coin",
    address: "base:0xf0cb96a4011a0a6f73d100c7080bf8020d10f87a",
    symbol: "MRLIGHTSPEED",
    url: "https://zora.co/mr_lightspeed",
    description:
      "Mr Lightspeed is a creator-issued token on the Zora Coins Protocol (on the Base network) where the creator issues a fixed 1 billion supply, splits it into a tradable pool and a five-year vesting schedule, and integrates with Uniswap v4 liquidity pools so that trades generate fees, deepen liquidity, and provide community access and content-linked incentives.",
    chain: "Base",
    logo: `${baseIconsUrl}/mr.-lightspeed-creator-coin.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "mr-lightspeed-creator-coin",
    cmcId: "38857",
    category: "SoFi",
    chains: ["Base"],
    module: "mr-lightspeed/index.js",
    twitter: "Mr_Lightspeed",
    forkedFromIds: [],
    audit_links: ["https://github.com/ourzora/zora-token/blob/main/audit/Zora%20Token%20-%20Zellic%20Audit%20Report.pdf"],
    listedAt: 1762822889,
  },
  {
    id: "6982",
    name: "Perpmate",
    address: null,
    symbol: "-",
    url: "https://perpmate.com/",
    description:
      "Trade on-chain perpetuals. Stake, trade and earn. Powered by Hyperliquid.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/perpmate.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Hyperliquid L1"],
    module: "dummy.js",
    twitter: "perpmate",
    forkedFromIds: [],
    audit_links: [],
    dimensions: {
      fees: "perpmate",
    }
  },
  {
    id: "6983",
    name: "Luna.fun",
    address: "bsc:0x55cD6469F597452B5A7536e2CD98fDE4c1247ee4",
    symbol: "LUNA",
    url: "https://luna.fun/",
    description:
      "Luna.fun is a meme launchpad with built-in AI-generated content (AIGC). Each token includes its own AI content engine, where agents automatically create and post memes across X to promote on-chain engagement. Powered by Virtuals Protocol’s Agent Commerce Protocol (ACP), Luna.fun connects token minting, AI content generation, and social distribution in one workflow on BNB Chain.",
    chain: "Binance",
    logo: `${baseIconsUrl}/luna.fun.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Binance"],
    module: "dummy.js",
    twitter: "luna_virtuals",
    forkedFromIds: [],
    audit_links: [],
    treasury: "luna-fun.js",
    dimensions: {
      fees: "luna-fun",
      dexs: "luna-fun", 
    }
  },
  {
    id: "6984",
    name: "iDos Games",
    address: null,
    symbol: "-",
    url: "https://idosgames.com/en/",
    description:
      "Multichain Web3 games/apps launchpad. It is a decentralized platform of the new generation that allows developers to launch their cross-platform Web3 games and AI applications with just one click. We provide a complete set of technologies and ready-to-use infrastructure, including blockchain integration, NFT support, cryptocurrency payments, cross-platform compatibility, analytics, and LiveOps services.",
    chain: "Binance",
    logo: `${baseIconsUrl}/idos-games.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Binance"],
    module: "idos-games/index.js",
    twitter: "iDosGamesEngine",
    forkedFromIds: [],
    audit_links: [],
    github: ["iDos-Games"],
    listedAt: 1762925465,
  },
  {
    id: "6985",
    name: "RHEA LST",
    address: null,
    symbol: "-",
    url: "https://www.rhea.finance/",
    description:
      "Liquid staking for the Rhea Finance ecosystem.",
    chain: "Near",
    logo: `${baseIconsUrl}/rhea-lst.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Near"],
    module: "rhealst.js",
    twitter: "rhea_finance",
    forkedFromIds: [],
    audit_links: ["https://guide.rhea.finance/developers/audits"],
    parentProtocol: "parent#rhea-finance",
    listedAt: 1762925473,
  },
  {
    id: "6986",
    name: "DewFinance",
    address: null,
    symbol: "-",
    url: "https://dew.finance/",
    description:
      "Dew Finance is a chain-abstracted vault infrastructure that enables curators and protocols to build and scale cross-chain yield products. It unifies yield opportunities across ecosystems while providing verifiable, policy-driven vaults with transparent on-chain accounting",
    chain: "Near",
    logo: `${baseIconsUrl}/dewfinance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Near"],
    module: "dew.js",
    twitter: "DewFinance",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762925479,
  },
  {
    id: "6987",
    name: "Corepilot",
    address: null,
    symbol: "-",
    assetToken: "pCORE",
    url: "https://www.corepilot.finance/",
    description:
      "Corepilot - Smart Staking for Smarter Rewards. Automatically delegate to the highest-APR validators and earn more with pCORE.",
    chain: "CORE",
    logo: `${baseIconsUrl}/corepilot.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["CORE"],
    module: "Corepilot/index.js",
    twitter: "CorepilotHQ",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762925487,
  },
  {
    id: "6988",
    name: "Baumz",
    address: null,
    symbol: "-",
    url: "https://baumz.com",
    description:
      "Baumz is a next-generation decentralized Perp Exchange with profit-based fees only (no maker/taker fees). Traders only pay when they win.",
    chain: "Orderly",
    logo: `${baseIconsUrl}/baumz.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Orderly"],
    module: "dummy.js",
    twitter: "Baumztrade",
    forkedFromIds: ["6647"],
    oraclesBreakdown: [ { name: "Chainlink", type: "Primary", proof: ["https://github.com/DefiLlama/dimension-adapters/pull/4620"]} ],
    audit_links: [],
    dimensions: {
      fees: "baumz",
      derivatives: "baumz",
    }
  },
  {
    id: "6989",
    name: "GTBTC",
    address: null,
    symbol: "-",
    url: "https://www.gate.com/staking/BTC",
    description:
      "Gate BTC Staking allows users to stake their BTC on the Gate platform in exchange for GTBTC (1:1 ratio), which accrues yield via Gate’s internal staking/earn mechanism; users can redeem GTBTC back into BTC at any time.",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/gate-btc.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Restaked BTC",
    chains: ["Bitcoin"],
    module: "gate-btc/index.js",
    twitter: "Gate",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762997847,
  },
  {
    id: "6990",
    name: "Etherfuse",
    address: null,
    symbol: "-",
    url: "https://www.etherfuse.com/",
    description:
      "Stablebonds are tokenized real-world assets (RWAs) backed by government-issued bonds from stable economies such as the USA, Mexico, and the European Union.",
    chain: "Solana",
    logo: `${baseIconsUrl}/etherfuse.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    tags: ["Treasury Bills"],
    chains: ["Solana"],
    module: "etherfuse/index.js",
    twitter: "etherfuse",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1762998317,
  },
  {
    id: "6991",
    name: "Valdora Finance",
    address: null,
    symbol: "-",
    assetToken: "stZIG",
    url: "https://www.valdora.finance/",
    description:
      "Valdora Finance is the liquid staking protocol built on ZIGChain, offering secure, non-custodial, and decentralized staking through its flagship token — stZIG.",
    chain: "ZIGChain",
    logo: `${baseIconsUrl}/valdora-finance.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["ZIGChain"],
    module: "valdora/index.js",
    twitter: "Valdora_finance",
    forkedFromIds: [],
    audit_links: ["https://docs.valdora.finance/security"],
    listedAt: 1762998474,
  },
  {
    id: "6992",
    name: "Definitive Yield Vaults",
    address: "base:0xED6E000dEF95780fb89734c07EE2ce9F6dcAf110",
    symbol: "EDGE",
    url: "https://www.definitive.fi",
    description:
      "Definitive is the premier non-custodial platform for advanced DeFi yield and on-chain trade execution.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/definitive-yield-vaults.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Arbitrum", "Polygon", "Optimism", "Base", "Avalanche"],
    module: "definitive/index.js",
    twitter: "DefinitiveFi",
    forkedFrom: [],
    github: [],
    audit_links: ["https://github.com/DefinitiveCo/definitive-public/tree/main/audits"],
    listedAt: 1709828870,
    deprecated: true,
  },
  {
    id: "6993",
    name: "Ramses HL",
    address: "hyperliquid:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "Ramses is a concentrated liquidity layer and exchange built on HyperEVM, powered by x(3,3)—a more fluid and accessible version of the popular ve(3,3) model",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/ramses-hl-cl.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Hyperliquid L1"],
    module: "ramses-hl-cl/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    audit_links: ["https://docs.ramses.xyz/pages/audits"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1763010949,
    dimensions: {
      fees: "ramses-hl-cl",
      dexs: "ramses-hl-cl",
    }
  },
  {
    id: "6994",
    name: "Ramses HL Legacy",
    address: "hyperliquid:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "Ramses is a concentrated liquidity layer and exchange built on HyperEVM, powered by x(3,3)—a more fluid and accessible version of the popular ve(3,3) model",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/ramses-hl-legacy.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Hyperliquid L1"],
    module: "ramses-hl-legacy/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1763010955,
    dimensions: {
      fees: "ramses-hl-legacy",
      dexs: "ramses-hl-legacy",
    }
  },
  {
    id: "6995",
    name: "0xRoulette Protocol",
    address: null,
    symbol: "-",
    url: "https://0xroulette.com",
    description:
      "0xRoulette is a a non-custodial on-chain game built on a roulette mechanic with liquidity providers earnings",
    chain: "Solana",
    logo: `${baseIconsUrl}/0xroulette-protocol.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Luck Games",
    chains: ["Solana"],
    module: "0xRoulette/index.js",
    twitter: "0xRoulette",
    forkedFromIds: [],
    listedAt: 1763085777,
  },
  {
    id: "6996",
    name: "Dnax",
    address: null,
    symbol: "-",
    url: "https://dnax.us/",
    description:
      "Empowering users with onchain automation and superior orderbook-like features",
    chain: "Binance",
    logo: `${baseIconsUrl}/dnax.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Binance"],
    module: "dnax/index.js",
    twitter: "ThisIsDNA",
    forkedFromIds: [],
    github: ["CarbonDeploy"],
    listedAt: 1763085852,
  },
  {
    id: "6997",
    name: "Yuzu Money",
    address: null,
    symbol: "-",
    url: "https://yuzu.money/",
    description:
      "An overcollateralized stablecoin backed by curated on-chain strategies that aims to offer some of the highest yields in DeFi. Users can stake yzUSD to obtain the yield-bearing syzUSD. Depositors in the yzPP accept first loss risk on the underlying strategies in exchange for higher target yield, funded partly by a Reserve Fund",
    chain: "Plasma",
    logo: `${baseIconsUrl}/yuzu-money.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Plasma"],
    module: "yuzu-money/index.js",
    twitter: "YuzuMoneyX",
    forkedFromIds: [],
    audit_links: [
      "https://yuzu-money.gitbook.io/yuzu-money/security-infrastructure/audits",
      "https://github.com/pashov/audits/blob/master/team/pdf/YuzuUSD-security-review_2025-08-28.pdf",
      "https://dedaub.com/audits/yuzu-money/yuzuusd-october-6-2025/",
    ],
    listedAt: 1763085858,
  },
  {
    id: "6998",
    name: "Fufuture V2",
    address: null,
    symbol: "-",
    url: "https://www.fufuture.io",
    description:
      "Decentralization Coin-based Perpetual Options Trading Agreement",
    chain: "Binance",
    logo: `${baseIconsUrl}/fufuture-v2.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Options",
    chains: ["Binance"],
    module: "fufuture-v2/index.js",
    twitter: "fufuture_io",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1763103007,
    parentProtocol: "parent#fufuture",
  },
  {
    id: "6999",
    name: "Fufuture Contract",
    address: null,
    symbol: "-",
    url: "https://www.fufuture.io",
    description:
      "Decentralization Coin-based Perpetual Options Trading Agreement",
    chain: "Binance",
    logo: `${baseIconsUrl}/fufuture-contract.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Binance"],
    module: "fufuture-contract/index.js",
    twitter: "fufuture_io",
    forkedFromIds: [],
    audit_links: [],
    listedAt: 1763103013,
    parentProtocol: "parent#fufuture",
  },
  {
    id: "7000",
    name: "Kodiak Perps",
    address: null,
    symbol: "-",
    url: "https://perps.kodiak.finance/",
    description: "Kodiak's Perps DEX",
    chain: "Orderly",
    logo: `${baseIconsUrl}/kodiak-perps.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["Orderly"],
    forkedFromIds: [],
    module: "dummy.js",
    twitter: "KodiakFi",
    parentProtocol: "parent#kodiak",
    dimensions: {
      fees: "kodiak-perps",
    }
  },
  {
    id: "7001",
    name: "RubyScore",
    address: null,
    symbol: "-",
    url: "https://rubyscore.io/",
    description: "RubyScore is a decentralized reputation and identity protocol that aggregates users' onchain activity across multiple networks and forms a unified reputation layer",
    chain: "Base",
    logo: `${baseIconsUrl}/rubyscore.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Services",
    chains: ["Abstract", "ApeChain", "Arbitrum", "Avalanche", "Base", "Berachain", "Binance", "BOB", "Boba", "Celo", "Corn", "Flare", "Flow", "Hemi", "Ink", "Katana", "Linea", "Mode", "Optimism", "Plasma", "Polygon", "Scroll", "Shape", "Somnia", "Sonic", "TAC", "Taiko", "Unichain", "zkSync Era"],
    forkedFromIds: [],
    module: "dummy.js",
    twitter: "rubyscore_io",
    dimensions: {
      fees: "rubyscore",
    }
  },
  {
    id: "7002",
    name: "GateFun",
    address: null,
    symbol: "-",
    url: "https://web3.gate.com/en/gatefun",
    description: "Gate Fun, built on Gate Layer, is a creator-friendly launchpad that offers no-code token issuance, low-cost deployment, and seamless liquidity building",
    chain: "GateLayer",
    logo: `${baseIconsUrl}/gatefun.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["GateLayer"],
    forkedFromIds: [],
    module: "gatefun/index.js",
    twitter: "Gate_Fun",
    listedAt: 1763158382,
  },
  {
    id: "7003",
    name: "Mining Tycoon",
    address: null,
    symbol: "-",
    url: "https://miningtycoon.fun",
    description: "Mining Tycoon is a dual-currency mining pool where users buy mining power with SOL or GPU tokens and earn proportional rewards from both vaults",
    chain: "Solana",
    logo: `${baseIconsUrl}/mining-tycoon.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Ponzi",
    chains: ["Solana"],
    forkedFromIds: [],
    module: "mining-tycoon/index.js",
    twitter: "MiningGPU",
    listedAt: 1763158389,
  },
  {
    id: "7004",
    name: "Rush",
    address: null,
    symbol: "-",
    url: "https://rushbot.io",
    description: "Trade any memecoin from your phone. Rush is an innovative Telegram trading bot built to be the fastest and most rewarding",
    chain: "Solana",
    logo: `${baseIconsUrl}/rush.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Telegram Bot",
    chains: ["Solana"],
    forkedFromIds: [],
    module: "dummy.js",
    twitter: "RushTradingBot",
    dimensions: {
      dexs: "rush",
    }
  },
  {
    id: "7005",
    name: "Neverland",
    address: "monad:0xAD96C3dffCD6374294e2573A7fBBA96097CC8d7c",
    symbol: "DUST",
    url: "https://neverland.money",
    description: "Neverland is a next-generation, Monad-native lending protocol fusing the most secure, battle-tested lending technology with proprietary veTokenomics that allow users to direct 100% of protocol revenue. Featuring self-repaying loans, flexible and tradable governance locks, and automated yield strategies, each designed to maximize capital efficiency and long-term alignment",
    chain: "Monad",
    logo: `${baseIconsUrl}/neverland.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Monad"],
    forkedFromIds: ["1599"],
    audit_links: ["https://github.com/Neverland-Money/security-audits"],
    oraclesBreakdown: [
      {
        name: "Chainlink",
        type: "Primary",
        proof: ["https://docs.neverland.money","https://github.com/DefiLlama/DefiLlama-Adapters/pull/17018"],
      }
    ],
    module: "dummy.js",
    twitter: "Neverland_Money",
    github: ["0xCatalyst"],
    dimensions: {
      fees: "neverland",
    }
  },
];
export default data5;
