import { baseIconsUrl } from "../constants";
import type { Protocol } from "./types";

/*
{
  id: string;
  name: string;
  address: string;
  symbol: string;
  url: string;
  description: string;
  chain: string;
  logo: null | string;
  audits: null | "0" | "1" | "2" | "3";
  audit_note: null;
  gecko_id: string;
  cmcId: string;
  category: string;
  chains: string[];
  oracles: string[];
  forkedFrom: string[];
  module: string;
  twitter: string;
  language?: string;
  treasury?: string;
},
*/
/* Audits: Please follow this legend
0 -> No audits
1 -> Part of this protocol may be unaudited
2 -> Yes
3 -> This protocol is a fork of an existing audited protocol
*/

/*
`chain` is the first chain of a protocol we tracked at defillama,
  so if a protocol launches on Ethereum and we start tracking it there, and then it launches on polygon and
  we start tracking it on both polygon and ethereum, then `chain` should be set to `Ethereum`.

`chains` is not used by the current code, but good to fill it out because it is used in our test to detect errors
*/
const data4: Protocol[] = [
  {
    id: "5580",
    name: "Latch",
    address: null,
    symbol: "-",
    url: "https://savings.latch.io/",
    description:
      "Deposit idle tokens, select a preferred vault, and earn yield and points",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/latch.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    oracles: [],
    forkedFrom: [],
    module: "latch/index.js",
    twitter: "UseLatch",
    audit_links: ["https://docs.latch.io/overview/contracts-audit"],
    listedAt: 1736110559
  },
  {
    id: "5581",
    name: "Aquadex",
    address: null,
    symbol: "-",
    url: "https://aquadex.co/swap",
    description:
      "Decentralized exchange on Waterfall Network",
    chain: "Waterfall",
    logo: `${baseIconsUrl}/aquadex.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Waterfall"],
    oracles: [],
    forkedFrom: [],
    module: "aquadex-v3/index.js",
    twitter: "waterfall_dag",
    github: ["AquaDEX"],
    listedAt: 1736174541
  },
  {
    id: "5582",
    name: "MANTRA Swap",
    address: null,
    symbol: "-",
    url: "https://mantra.zone/liquidity-pools",
    description:
      "Decentralized exchange on Mantra chain",
    chain: "Mantra",
    logo: `${baseIconsUrl}/mantra-swap.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Mantra"],
    oracles: [],
    forkedFrom: [],
    module: "mantra-amm/index.js",
    twitter: "MANTRA_Chain",
    listedAt: 1736174547
  },
  {
    id: "5583",
    name: "ILoop",
    address: null,
    symbol: "-",
    url: "https://app.iloop.finance/",
    description:
      "ILoop Protocol is a decentralized lending platform on the Solana blockchain, designed for secure and efficient leverage and capital optimization. ILoop stands out as an Automated DeFi protocol that integrates Lending, and Looping into a unified and secure DeFi product suite",
    chain: "Solana",
    logo: `${baseIconsUrl}/iloop.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Solana"],
    oracles: [],
    forkedFrom: [],
    module: "iloop/index.js",
    twitter: "iLoop_HQ",
    audit_links: ["https://github.com/user-attachments/files/18279096/Iloop-contract.-.SlowMist.Audit.Report.pdf"],
    listedAt: 1736175355
  },
  {
    id: "5584",
    name: "Astrol",
    address: null,
    symbol: "-",
    url: "https://astrol.io/",
    description:
      "Lend, Borrow & Earn with ease on Eclipse",
    chain: "Eclipse",
    logo: `${baseIconsUrl}/astrol.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Eclipse"],
    oracles: ["Pyth"], // https://doc.astrol.io/astrolend/oracle-usage
    forkedFrom: [],
    module: "astrolend/index.js",
    twitter: "AstrolFinance",
    audit_links: ["https://doc.astrol.io/astrolend/security"],
    github: ["Astrol-Finance"],
    listedAt: 1736175355
  },
  {
    id: "5585",
    name: "Omega",
    address: null,
    symbol: "-",
    url: "https://app.omega.xyz/",
    description:
      "Lending protocol that allows for a variety of assets to be used as collateral to access 6x leverage through various yield farming strategies across the Mantle Ecosystem",
    chain: "Mantle",
    logo: `${baseIconsUrl}/omega.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Leveraged Farming",
    chains: ["Mantle"],
    oracles: [], 
    forkedFrom: ["Juice Finance"],
    module: "omega/index.js",
    twitter: "omega_infra",
    listedAt: 1736176657
  },
  {
    id: "5586",
    name: "SatLayer",
    address: null,
    symbol: "-",
    url: "https://satlayer.xyz/",
    description:
      "SatLayer unleashes the possibilities of BTC, the world's best economic collateral, to secure any type of dApp or protocol as an Bitcoin Validated Service (BVS), fundamentally upgrading security for all of crypto",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/satlayer.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Restaked BTC",
    chains: ["Ethereum","Binance","Bitlayer"],
    oracles: [],
    forkedFrom: [],
    module: "satlayer/index.js",
    twitter: "satlayer",
    github: ["satlayer"],
    audit_links: [
      "https://github.com/satlayer/deposit-contract-public/blob/main/audits/Satlayer_audit_report_2024-08-15.pdf",
      "https://github.com/satlayer/deposit-contract-public/blob/main/audits/SatLayer%20Pool%20-%20Zellic%20Audit%20Report.pdf"
    ],
    listedAt: 1736176895
  },
  {
    id: "5587",
    name: "Coinbase Wallet",
    address: null,
    symbol: "-",
    url: "https://wallet.coinbase.com/",
    description:
      "Crypto wallet and dapp browser",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/coinbase-wallet.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Wallets",
    chains: ["Ethereum","Arbitrum","Optimism","Polygon","Base","Avalanche","Binance"],
    oracles: [],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "CoinbaseWallet",
  },
  {
    id: "5588",
    name: "YieldFi",
    address: null,
    symbol: "-",
    url: "https://yield.fi/",
    description:
      "YieldFi: The First Streamlined Asset Management Platform",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/yieldfi.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Ethereum","Optimism","BOB"],
    oracles: [],
    forkedFrom: [],
    module: "yield-fi/index.js",
    twitter: "getyieldfi",
    github: ["YieldFiLabs"],
    audit_links: [
      "https://docs.yield.fi/resources/audits"
    ],
    listedAt: 1736184965
  },
  {
    id: "5589",
    name: "dTRINITY dUSD",
    address: null,
    symbol: "-",
    url: "https://app.dtrinity.org/dusd/",
    description:
      "dTRINITY is a decentralized and community-governed on-chain replication of the US Federal Reserve, operating under a full-reserve model for enhanced stability and sustainability. It features three core DeFi primitives: a native stablecoin (dUSD) serving as a unified liquidity layer, money markets (dLEND), and integrations with external liquidity pools like Curve",
    chain: "Fraxtal",
    logo: `${baseIconsUrl}/dtrinity.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Partially Algorithmic Stablecoin",
    chains: ["Fraxtal"],
    oracles: [],
    forkedFrom: [],
    module: "dtrinity/index.js",
    twitter: "dtrinity_defi",
    parentProtocol: "parent#dtrinity",
    listedAt: 1736185537
  },
  {
    id: "5590",
    name: "dTRINITY dLEND",
    address: null,
    symbol: "-",
    url: "https://app.dtrinity.org/dlend/lending-borrow/",
    description:
      "dLEND is a Fraxtal-based fork of the Aave v3 protocol, designed for secure lending and borrowing of dUSD and other digital assets. By default, dUSD is the sole borrowable asset, and loans can only be taken against other supplied assets, excluding dUSD. This prevents rehypothecation of collateral, reducing protocol risks and subsidy arbitrage. Borrowing rates for dUSD are subsidized through regular interest rebates, encouraging demand and utilization while offering lower costs for borrowers and sustainable yields for lenders",
    chain: "Fraxtal",
    logo: `${baseIconsUrl}/dtrinity.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Fraxtal"],
    oracles: [],
    forkedFrom: ["AAVE V3"],
    module: "dtrinity-dlend/index.js",
    twitter: "dtrinity_defi",
    parentProtocol: "parent#dtrinity",
    listedAt: 1736185543
  },
  {
    id: "5591",
    name: "Aethir",
    address: "arbitrum:0xbe0Ed4138121EcFC5c0E56B40517da27E6c5226B",
    symbol: "ATH",
    url: "https://aethir.com/",
    description: "Powerful GPU compute solutions on-demand.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/aethir.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "aethir",
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    oracles: [],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "AethirCloud",
  },
  {
    id: "5592",
    name: "Prime Staking",
    address: null,
    symbol: "-",
    url: "https://primestaking.xyz/",
    description:
      "Liquid staking on XDC",
    chain: "XDC",
    logo: `${baseIconsUrl}/prime-staking.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["XDC"],
    oracles: [],
    forkedFrom: [],
    module: "primestaking-xyz/index.js",
    twitter: "PrimeNumbersFi",
    listedAt: 1736202245
  },
  {
    id: "5593",
    name: "InkySwap",
    address: null,
    symbol: "-",
    url: "https://inkyswap.com/",
    description:
      "The decentralized exchange on Ink, where InkyPump's tokens get their liquidity once they are bonded.",
    chain: "Ink",
    logo: `${baseIconsUrl}/inkyswap.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Ink"],
    oracles: [],
    forkedFrom: ["Uniswap V2"],
    module: "inkyswap/index.js",
    twitter: "inkyswap",
    github: ["InkySwap"],
    listedAt: 1736202627
  },
  {
    id: "5594",
    name: "MONSTRO",
    address: null,
    symbol: "-",
    url: "https://v2.monstro.fun",
    description:
      "Protocol on base chain",
    chain: "Base",
    logo: `${baseIconsUrl}/monstro.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Base"],
    oracles: [],
    forkedFrom: [],
    module: "monstro-fun/index.js",
    treasury: "monstro-fun.js",
    twitter: "monstrosuni",
    listedAt: 1736249582
  },
  {
    id: "5595",
    name: "GOLDSTATION DEX V3",
    address: null,
    symbol: "-",
    url: "https://goldstation.io",
    description:
      "Your Gateway to Decentralized Finance with Real Asset Integration",
    chain: "Avalanche",
    logo: `${baseIconsUrl}/goldstation-dex-v3.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Avalanche"],
    oracles: [],
    forkedFrom: ["Uniswap V3"],
    module: "goldstation-dex-v3/index.js",
    twitter: "goldstation_io",
    parentProtocol: "parent#goldstation",
    tokensExcludedFromParent: {
      Avalanche: ["GPC"],
    },
    listedAt: 1736249628
  },
  {
    id: "5596",
    name: "Neptune",
    address: null,
    symbol: "-",
    url: "https://nep.finance/",
    description:
      "The Premier DEX on Swellchain",
    chain: "Swellchain",
    logo: `${baseIconsUrl}/neptune.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Swellchain"],
    oracles: [],
    forkedFrom: ["Solidly"],
    module: "neptune/index.js",
    twitter: "NepFinance",
    listedAt: 1736278247
  },
  {
    id: "5597",
    name: "dappOS IntentEX", // previous dappOS 
    address: null,
    symbol: "-",
    url: "https://dappos.com/",
    description:
      "dappOS is an intent execution network",
    chain: "Op_Bnb",
    logo: `${baseIconsUrl}/dappos-intentex.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Op_Bnb"],
    oracles: [],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "dappOS_com",  
  },
  {
    id: "5598",
    name: "VolBoost",
    address: null,
    symbol: "-",
    url: "https://volboost.com/",
    description:
      "Boost your token's volume, liquidity and visibility in one click",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/volboost.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Volume Boosting",
    chains: ["Ethereum","Base","Binance"],
    oracles: [],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "volboost",  
  },
  {
    id: "5599",
    name: "GRVT",
    address: null,
    symbol: "-",
    url: "https://grvt.io",
    description:
      "World's first licensed DEX, redesigning finance. Building true CeDeFi. Mainnet Alpha LIVE.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/grvt.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Ethereum"],
    oracles: [],
    forkedFrom: [],
    module: "grvt-io/index.js",
    twitter: "grvt_io",
    listedAt: 1736334414
  },
  {
    id: "5600",
    name: "Creator Bid",
    address: null,
    symbol: "-",
    url: "https://creator.bid/agents",
    description:
      "Create and tokenize AI agents , AI Launchpad on base",
    chain: "Base",
    logo: `${baseIconsUrl}/creator-bid.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "AI Agents",
    chains: ["Base"],
    oracles: [],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "CreatorBid",
  },
  {
    id: "5601",
    name: "Verus Market",
    address: null,
    symbol: "-",
    url: "https://eth.verusbridge.io/",
    description:
      "Dex on Verus chain",
    chain: "Verus",
    logo: `${baseIconsUrl}/verus-market.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Verus"],
    oracles: [],
    forkedFrom: [],
    module: "verus-market/index.js",
    twitter: "VerusCoin",
    listedAt: 1736335147
  },
  {
    id: "5602",
    name: "NODO", // previously NODO Global
    address: null,
    symbol: "-",
    url: "https://nodo.xyz",
    description:
      "NODO is an omnichain AI-driven social copytrading ecosystem with real-time, instant-payout price prediction markets. Our flagship product NODO Trade is focused on DeFi interoperability, utilizing a robust cross-chain relayer and multi-brokerage AMM model to ensure capital efficiency and complete asset ownership for users. We're currently working to launch on SUI and Cardano. Powering our AI copytrading agent is aggregated trading data from top traders on NODO and across world-leading trading platforms, generating smart trading strategies devoid of the trappings of any emotional biases. Users can also safely farm yield from high-APY DeFi vaults via NODO Wallet, creating a robust and flexible social trading ecosystem with both high and low risk options",
    chain: "Avalanche",
    logo: `${baseIconsUrl}/nodo-global.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Trading App",
    chains: ["Avalanche", "Polygon", "Base", "Binance", "Celo"],
    oracles: [],
    forkedFrom: [],
    module: "nodo/index.js",
    twitter: "Official_NODO",
    github: ["NODO-xyz"],
    listedAt: 1736335147
  },
  {
    id: "5603",
    name: "2THICK", // previously Equalizer CL
    address: null,
    symbol: "ELITE",
    url: "https://eliteness.network/thick",
    description:
      "Protocol-agnostic Concentrated Liquidity Self-incentivizing AMM, now with Dynamic Trade Fee & Strategic TickSpacing based optimizations",
    chain: "Sonic",
    logo: `${baseIconsUrl}/2thick.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    oracles: [],
    forkedFrom: ["Uniswap V3"],
    module: "equalizer-cl/index.js",
    twitter: "FTM1337",
    parentProtocol: "parent#guru-network-dao",
    listedAt: 1736387589
  },
  {
    id: "5604",
    name: "Memebox",
    address: null,
    symbol: "-",
    url: "https://memebox.fi/#/swap",
    description:
      "A decentralized exchange on Sonic",
    chain: "Sonic",
    logo: `${baseIconsUrl}/memebox.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    oracles: [],
    forkedFrom: ["Uniswap V2"],
    module: "memebox-fi/index.js",
    twitter: "MemeboxFi",
    listedAt: 1736387595
  },
  {
    id: "5605",
    name: "MobiusDEX",
    address: "sonic:0xf3969639AE1f2716568eDBd0420153a6709f6e7b",
    symbol: "MDEX",
    url: "https://mobiusdex.xyz/",
    description:
      "A decentralized exchange on Sonic",
    chain: "Sonic",
    logo: `${baseIconsUrl}/mobiusdex.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    oracles: [],
    forkedFrom: ["Uniswap V2"],
    module: "mobiusdex-xyz/index.js",
    twitter: "planetmobiusfun",
    github: ["planetmobius"],
    listedAt: 1736387601
  },
  {
    id: "5606",
    name: "WavesBridge",
    address: null,
    symbol: "-",
    url: "https://wavesbridge.io/",
    description:
      "Connecting Waves assets across blockchains",
    chain: "UNIT0",
    logo: `${baseIconsUrl}/wavesbridge.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["UNIT0", "Waves", "Ethereum", "Binance", "Solana"],
    oracles: [],
    forkedFrom: [],
    module: "wavesbridge/index.js",
    twitter: "wavesbridge",
    github: ["WavesBridge"],
    listedAt: 1736387607
  },
  {
    id: "5607",
    name: "Marlin Protocol",
    address: "arbitrum:0xdA0a57B710768ae17941a9Fa33f8B720c8bD9ddD",
    symbol: "POND",
    url: "https://marlinprotocol.fi/relay/operator",
    description:
      "TEE coprocessors for decentralized AI",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/marlin-protocol.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "marlin",
    cmcId: "7497",
    category: "Farm",
    chains: ["Arbitrum"],
    oracles: [],
    forkedFrom: [],
    module: "marlinprotocol/index.js",
    twitter: "MarlinProtocol",
    listedAt: 1736432811
  },
  {
    id: "5608",
    name: "Navigator",
    address: "sonic:0x6881B80ea7C858E4aEEf63893e18a8A36f3682f3",
    symbol: "NAVI",
    url: "https://www.navigator.exchange/",
    description:
      "Decentralized Liquidity Marketplace. Effortless trading, continuous liquidity. Across Crypto, Forex, and beyond",
    chain: "Sonic",
    logo: `${baseIconsUrl}/navigator.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "navi-2",
    cmcId: null,
    category: "Derivatives",
    chains: ["Sonic"],
    oracles: ["Pyth"], // https://sonicscan.org/address/0xe9263682e837efabb145f8c632b9d2c518d90652#code
    forkedFrom: [],
    module: "navigator/index.js",
    twitter: "NaviExSonic",
    listedAt: 1736432817
  },
  {
    id: "5609",
    name: "Sophon Bridge",
    address: null,
    symbol: "-",
    url: "https://sophon.xyz/",
    description:
      "Sophon is a ZK chain",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/sophon.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    oracles: [], 
    forkedFrom: [],
    module: "sophon/index.js",
    twitter: "sophon",
    listedAt: 1736469229
  },
  {
    id: "5610",
    name: "Crypto Valley Exchange",
    address: null,
    symbol: "-",
    url: "https://cvex.xyz/",
    description:
      "Decentralized derivatives clearing protocol. Enabling traders to reduce margin and unlock capital by providing exchanges with a robust clearing mechanism. First Exchange offers Crypto Derivatives with full portfolio risk. Ready to unleash and empower crypto derivatives by unlocking collateral.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/crypto-valley-exchange.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: "30714",
    category: "Derivatives",
    chains: ["Arbitrum"],
    oracles: ["Internal"], // https://github.com/DefiLlama/DefiLlama-Adapters/pull/13046
    forkedFrom: [],
    module: "cvex/index.js",
    twitter: "cvex_xyz",
    listedAt: 1736469235
  },
  {
    id: "5611",
    name: "Silo V2",
    address: "0x6f80310ca7f2c654691d1383149fa1a57d8ab1f8",
    symbol: "SILO",
    url: "https://app.silo.finance",
    description: "Silo Finance creates permissionless and risk-isolated lending markets.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/silo-finance.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Arbitrum","Sonic"],
    oracles: [],
    forkedFrom: [],
    module: "silo-v2/index.js",
    twitter: "SiloFinance",
    audit_links: ["https://docs.silo.finance/audits-and-tests"],
    parentProtocol: "parent#silo-finance",
    listedAt: 1736470165,
  },
  {
    id: "5612",
    name: "Margin Zero",
    address: null,
    symbol: "-",
    url: "https://www.marginzero.xyz/",
    description:
      "MarginZero is an omni-chain, oracle-less and permission-less options & protected perpetual protocol",
    chain: "Sonic",
    logo: `${baseIconsUrl}/margin-zero.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Options",
    chains: ["Sonic"],
    oracles: [], 
    forkedFrom: [],
    module: "margin-zero/index.js",
    audit_links: ["https://github.com/marginzero-xyz/contracts/blob/main/audits/yAudits/MarginZero_yAudits_December2024_OptionsOTM.pdf"],
    twitter: "marginzero_xyz",
    github: ["marginzero-xyz"],
    listedAt: 1736470171
  },
  {
    id: "5613",
    name: "VinuNFT",
    address: null,
    symbol: "-",
    url: "VinuChain's premier NFT platform.",
    description:
      "MarginZero is an omni-chain, oracle-less and permission-less options & protected perpetual protocol",
    chain: "VinuChain",
    logo: `${baseIconsUrl}/vinunft.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "NFT Marketplace",
    chains: ["VinuChain"],
    oracles: [], 
    forkedFrom: [],
    module: "dummy.js",
    twitter: "VinuChain",
  },
  {
    id: "5614",
    name: "Pryzm Liquid Staking",
    address: null,
    symbol: "-", // preview only
    url: "https://app.pryzm.zone",
    description: "Liquid staking of native tokens for Cosmos-based chains",
    chain: "Pryzm",
    logo: `${baseIconsUrl}/pryzm-liquid-staking.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Pryzm"],
    module: "pryzm-liquid-staking/index.js",
    twitter: "Pryzm_Zone",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://skynet.certik.com/projects/PRYZM"],
    parentProtocol: "parent#pryzm",
    listedAt: 1736533711
  },
  {
    id: "5615",
    name: "Zoth ZeUSD", // previously Zoth
    address: null,
    symbol: "-",
    url: "https://app.zoth.io/zeusd",
    description: `Zoth is an RWA ecosystem bringing institutional-grade yield avenues onchain.`,
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zoth.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Ethereum"],
    oracles: [],
    module: "zoth-zeusd/index.js",
    twitter: "zothdotio",
    forkedFrom: [],
    audit_links: ["https://docs.zoth.io/zoth/resources/audits"],
    parentProtocol: "parent#zoth",
    listedAt: 1736774553
  },
  {
    id: "5616",
    name: "Republic Note", 
    address: null,
    symbol: "-",
    url: "https://republic.com/note",
    description: `One asset, broad exposure to venture & crypto`,
    chain: "Avalanche",
    logo: `${baseIconsUrl}/republic-note.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA",
    chains: ["Avalanche"],
    oracles: [],
    module: "republic/index.js",
    twitter: "republicnote",
    forkedFrom: [],
    audit_links: [],
    listedAt: 1736775042
  },
  {
    id: "5617",
    name: "Aurum", 
    address: "avax:0x7F144F8691CbA3d2EfD8e5bcf042f9303EE31a46",
    symbol: "AUR",
    url: "https://aurumfi.io/",
    description: `Aurum: Unlocking seamless DeFi lending with innovative yield strategies and community-driven rewards.`,
    chain: "Sonic",
    logo: `${baseIconsUrl}/aurum.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Sonic"],
    oracles: ["API3"], // https://aurum-finance.gitbook.io/docs
    module: "aurum/index.js",
    twitter: "AurumFi_Sonic",
    forkedFrom: ["AAVE V3"],
    audit_links: ["https://github.com/aave/aave-v3-core/tree/master/audits"],
    github: ["aurum-protocol"],
    listedAt: 1736775047
  },
  {
    id: "5618",
    name: "LFJ Aggregator",
    address: "avax:0x6e84a6216ea6dacc71ee8e6b0a5b7322eebc0fdd",
    symbol: "JOE",
    url: "https://lfj.gg/arbitrum/trade",
    description:
      "DEX Aggregator by LFJ",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/lfj-aggregator.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Avalanche", "Arbitrum"],
    module: "dummy.js",
    twitter: "LFJ_gg",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
    parentProtocol: "parent#trader-joe",
    listedAt: 1736793159,
  },
  {
    id: "5619",
    name: "SSI",
    address: null,
    symbol: "-",
    url: "https://ssi.sosovalue.com/",
    description:
      "The SoSoValue Index (SSI) Protocol is a cutting-edge spot index solution designed to make crypto investments simple and secured",
    chain: "Base",
    logo: `${baseIconsUrl}/ssi.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    chains: ["Base"],
    module: "ssi-protocol/index.js",
    twitter: "SoSoValueCrypto",
    forkedFrom: [],
    oracles: [],
    audit_links: [
      "https://github.com/blocksecteam/audit-reports/blob/main/solidity/blocksec_sosovaluelabs_ssi_v1.0-signed.pdf",
      "https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/smart-contract/SSI%20Protocol%20-%20SlowMist%20Audit%20Report.pdf",
      "https://github.com/slowmist/Knowledge-Base/blob/master/open-report-V2/smart-contract/SSI%20Protocol%20Phase2%20-%20SlowMist%20Audit%20Report.pdf"
    ],
    github: ["SoSoValueLabs"],
    listedAt: 1736793641,
  },
  {
    id: "5620",
    name: "Botto",
    address: "0x9DFAD1b7102D46b1b197b90095B5c4E9f5845BBA",
    symbol: "BOTTO",
    url: "https://www.botto.fi/",
    description:
      "Botto is a decentralized autonomous artist",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/botto.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "botto",
    cmcId: "14345",
    category: "AI Agents",
    chains: ["Ethereum", "Base"],
    module: "botto/index.js",
    twitter: "bottoproject",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
    listedAt: 1736793647,
  },
  {
    id: "5621",
    name: "Anqa",
    address: null,
    symbol: "-",
    url: "https://app.anqa.ag/",
    description:
      "DEX Aggregator on Aptos",
    chain: "Aptos",
    logo: `${baseIconsUrl}/anqa.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Aptos"],
    module: "dummy.js",
    twitter: "anqa_apt",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
    listedAt: 1736794279,
  },

  {
    id: "5622",
    name: "Kyo Finance",
    address: null,
    symbol: "-",
    url: "https://www.kyo.finance",
    description:
      "The Most Innovative Liquidity Hub on soneium",
    chain: "Soneium",
    logo: `${baseIconsUrl}/kyo-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Soneium"],
    module: "kyo-fi-v3/index.js",
    twitter: "kyofinance",
    forkedFrom: ["Uniswap V3"],
    oracles: [],
    audit_links: [],
    listedAt: 1736851067
  },
  {
    id: "5623",
    name: "SoneFi AMM",
    address: null,
    symbol: "-",
    url: "https://sonefi.xyz",
    description:
      "One-stop trading Dex soneium, offering  AMM, Perp, AI Agent, and Meme Launch.",
    chain: "Soneium",
    logo: `${baseIconsUrl}/sonefi.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Soneium"],
    module: "sonefi-xyz/index.js",
    twitter: "SoneFi_xyz",
    forkedFrom: ["SyncSwap"],
    oracles: [], 
    audit_links: [],
    parentProtocol: "parent#sonefi",
    listedAt: 1736851567
  },
  {
    id: "5624",
    name: "Soneium Bridge",
    address: null,
    symbol: "-",
    url: "https://superbridge.app/soneium",
    description:
      "Bridge between Ethereum and Soneium",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/soneium-bridge.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "soneium/index.js",
    twitter: "soneium",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
  },
  {
    id: "5625",
    name: "ParagonsDAO",
    address: "0x375abb85c329753b1ba849a601438ae77eec9893",
    symbol: "PDT",
    url: "https://app.paragonsdao.com",
    description:
      "A gaming community focused on simplifying web3 gaming for the masses and sharing the assets, analytics, and infrastructure that help you unleash your potential with premier games",
    chain: "Base",
    logo: `${baseIconsUrl}/paragonsdao.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "paragonsdao",
    cmcId: "17794",
    category: "Staking",
    chains: ["Base"],
    module: "paragons-dao/index.js",
    twitter: "ParagonsDAO",
    forkedFrom: [],
    oracles: [],
    audit_links: [
      "https://github.com/Zellic/publications/blob/master/PDT%20Staking%20V2%20-%20Zellic%20Audit%20Report.pdf",
      "https://hashlock.com/audits/paragonsdao"
    ],
    github: ["ParagonsDAO"],
    listedAt: 1736886545
  },
  {
    id: "5626",
    name: "Untangled Vault",
    address: null,
    symbol: "-",
    url: "https://superbridge.app/soneium",
    description:
      "A non-custodial, cross-chain portfolio management solution: a data-driven, automated vault designed to attract liquidity and invest in opportunities across any EVM network to match diverse risk/return appetites",
    chain: "Celo",
    logo: `${baseIconsUrl}/untangled.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Managed Token Pools",
    chains: ["Celo"],
    module: "untangled-yield/index.js",
    twitter: "UntangledFi",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
    parentProtocol: "parent#untangled",
    listedAt: 1736886549
  },
  {
    id: "5627",
    name: "SakeFinance",
    address: null,
    symbol: "-",
    url: "https://app.sakefinance.com/",
    description:
      "Sake Finance is an integrated liquidity protocol on Soneium. Sake is pioneering a new era of decentralized finance, where different modules work together seamlessly to provide the smoothest user experience",
    chain: "Soneium",
    logo: `${baseIconsUrl}/sakefinance.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Soneium"],
    module: "sake-finance/index.js",
    twitter: "sakefinance",
    forkedFrom: ["AAVE V3"],
    oracles: ["Chainlink"], // https://github.com/DefiLlama/DefiLlama-Adapters/pull/13098
    audit_links: ["https://github.com/Sake-Finance/Sake-Finance-Audit/blob/main/PeckShield-Audit-Report-Sake-v1.0.pdf"],
    listedAt: 1736960282
  },
  {
    id: "5628",
    name: "UntitledBank",
    address: null,
    symbol: "-",
    url: "https://untitledbank.co/",
    description:
      "Untitled Bank is a permissionless, and modular lending platform designed to provide a seamless and inclusive experience for all users",
    chain: "Soneium",
    logo: `${baseIconsUrl}/untitledbank.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Soneium"],
    module: "untitledbank/index.js",
    twitter: "BankUntitled",
    forkedFrom: [],
    oracles: ["Pyth"], // Pyth currently used for majority of deposited value, usdc.e, astr & weth // https://docs.untitledbank.co/
    audit_links: ["https://beosin.com/audits/Untitled-Bank_202501101523.pdf"],
    listedAt: 1736960289
  },
  {
    id: "5629",
    name: "SquidSwap",
    address: "ink:0xbf0cAfCbaaF0be8221Ae8d630500984eDC908861",
    symbol: "SQUIDS",
    url: "https://squidswap.ink",
    description:
      "SquidSwap is a revolutionary decentralized platform built on Kraken's Ink L2 network, designed to provide a secure and efficient way to launch, lock, and trade tokens. Our platform combines the best aspects of decentralized finance with innovative features to ensure fair and secure token launches",
    chain: "Ink",
    logo: `${baseIconsUrl}/squidswap.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Ink"],
    module: "squidswap/index.js",
    twitter: "squidswap_ink",
    forkedFrom: ["Uniswap V2"],
    oracles: [],
    audit_links: [],
    github: ["squidswap-ink"],
    listedAt: 1736960299
  },
  {
    id: "5630",
    name: "OOIA",
    address: null,
    symbol: "-",
    url: "https://ooia.art",
    description:
      "OOIA is a low-fee marketplace on TON, offering the opportunity to trade NFT assets both through traditional methods and with unique mechanics",
    chain: "TON",
    logo: `${baseIconsUrl}/ooia.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "NFT Marketplace",
    chains: ["TON"],
    module: "dummy.js",
    twitter: "OoiaTon",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
  },
  {
    id: "5631",
    name: "Cian Bera",
    address: null,
    symbol: "-",
    url: "https://cian.app",
    description:
      "Redistribute Yield Sources For Sustainable DeFi",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/cian-bera.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    module: "cian-bera/index.js",
    twitter: "CIAN_protocol",
    forkedFrom: [],
    oracles: [],
    audit_links: [],
    parentProtocol: "parent#cian-protocol",
    listedAt: 1737046884
  },
  {
    id: "5632",
    name: "Movement",
    address: "ethereum:0x3073f7aaa4db83f95e9fff17424f71d4751a3073",
    symbol: "MOVE",
    url: "https://www.movementnetwork.xyz/",
    description: "Bringing Move to Ethereum and beyond.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/movement.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: "movement",
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    oracles: [],
    forkedFrom: [],
    module: "dummy.js",
    twitter: "movementlabsxyz",
  },
  {
    id: "5633",
    name: "Momodrome",
    address: null,
    symbol: "-",
    url: "https://momodrome.io",
    description:
      "The exclusive and only ve33 DEX of the Morph ecosystem.",
    chain: "Morph",
    logo: `${baseIconsUrl}/momodrome.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Morph"],
    module: "momodrome/index.js",
    twitter: "momodrome_io",
    forkedFrom: [],
    oracles: [],
    listedAt: 1737059541
  },
  {
    id: "5634",
    name: "Neemo Finance",
    address: null,
    symbol: "-",
    url: "https://neemo.finance/",
    description:
      "Neemo Finance develops liquid staking and restaking protocols, offering nsASTR and nrETH, designed to optimize rewards and liquidity on Soneium. By bridging the gap between staking and DeFi, Neemo empowers users to unlock the full potential of their assets while contributing to a dynamic and sustainable multi-chain ecosystem.",
    chain: "Soneium",
    logo: `${baseIconsUrl}/neemo-finance.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Restaking",
    chains: ["Soneium"],
    module: "neemo-finance/index.js",
    twitter: "neemofinance",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://audits.hacken.io/neemo-finance/"],
    listedAt: 1737088474
  },
  {
    id: "5635",
    name: "OmniYield",
    address: null,
    symbol: "-",
    url: "https://omniyield.finance/",
    description:
      "OmniYield is an omnichain yield optimizer that maximizes returns by dynamically reallocating assets across networks, offering auto-compounding, low fees, and a seamless, secure DeFi experience.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/omniyield.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Arbitrum"],
    module: "omniyield/index.js",
    twitter: "OmniYield",
    forkedFrom: [],
    oracles: [],
    listedAt: 1737088481
  },
  {
    id: "5636",
    name: "Zarban",
    address: null,
    symbol: "-",
    url: "https://zarban.io/",
    description:
      "Zarban is an Open Source and Non-Custodial protocol to earn interest on deposits and borrow assets. It also gives you the opportunity to mint ZAR stablecoin.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/zarban.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Arbitrum"],
    module: "zarban/index.js",
    twitter: "ZarbanProtocol",
    forkedFrom: ["AAVE V2"],
    oracles: ["Chainlink"], // https://github.com/DefiLlama/DefiLlama-Adapters/pull/13111
    audit_links: ["https://www.auditone.io/audit-report/zarban"],
    treasury: "zarban.js",
    github: ["zarbanio"],
    listedAt: 1737088495
  },
  {
    id: "5637",
    name: "Symphony Exchange",
    address: null,
    symbol: "-",
    url: "https://symph.ag/",
    description:
      "Symphony Exchange aggregates decentralized exchanges on the Sei Network into a single, unified interface.",
    chain: "Sei",
    logo: `${baseIconsUrl}/symphony-exchange.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Sei"],
    module: "dummy.js",
    twitter: "SymphonyAg",
    forkedFrom: [],
    oracles: [], 
  },
  {
    id: "5638",
    name: "LN Exchange Spot",
    address: null,
    symbol: "-",
    url: "https://app.ln.exchange/",
    description:
      "Orderbook Exchange on Lightning Network",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/ln-exchange.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Bitcoin"],
    module: "dummy.js",
    twitter: "LNExchange",
    forkedFrom: [],
    oracles: [], 
    parentProtocol: "parent#ln-exchange",
  },
  {
    id: "5639",
    name: "LN Exchange Perps",
    address: null,
    symbol: "-",
    url: "https://app.ln.exchange/",
    description:
      "Spot & Perpetual Trading for Bitcoins TaprootAssets",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/ln-exchange.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Bitcoin"],
    module: "dummy.js",
    twitter: "LNExchange",
    forkedFrom: [],
    oracles: [], 
    parentProtocol: "parent#ln-exchange",
  },
  {
    id: "5640",
    name: "Sonex",
    address: null,
    symbol: "-",
    url: "https://sonex.so",
    description:
      "SONEX is built on a foundation of zk co-processors and decentralized storage and leverage an AI routing terminal to deliver investment strategies.Designed to meet diverse trading needs, SONEX is set to evolve into a comprehensive Alpha Hunting Ecosystem Aggregator, empowering users to stay ahead in the ever-evolving DeFi landscape",
    chain: "Soneium",
    logo: `${baseIconsUrl}/sonex.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Soneium"],
    module: "sonex/index.js",
    twitter: "OopsItsSONEX",
    forkedFrom: ["Uniswap V3"],
    oracles: [], 
    github: ["sonex-dex"],
    listedAt: 1737126167
  },
  {
    id: "5641",
    name: "Citrex Markets",
    address: null,
    symbol: "-",
    url: "https://app.citrex.markets/",
    description:
      "Citrex is a decentralised exchange offering low fee and fast CEX-like perpetual and spot trading from a self-custodial cross-margin account built on the Sei blockchain.Trade perps on your favourite assets like SEI, BTC, ETH, XRP or DOGE, with low fees.",
    chain: "Sei",
    logo: `${baseIconsUrl}/citrex-markets.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Sei"],
    module: "citrex-markets/index.js",
    twitter: "citrex_markets",
    forkedFrom: [],
    oracles: [], 
    listedAt: 1737129117
  },
  {
    id: "5642",
    name: "edBank",
    address: null,
    symbol: "-",
    url: "https://edbank.xyz/",
    description:
      "EdBankDAO is a DeFi platform for the EduChain ecosystem. By utilizing a CDP (Collateralized Debt Position) protocol, EdBankDAO empowers EDU token holders to issue stablecoins backed by their assets",
    chain: "EDU Chain",
    logo: `${baseIconsUrl}/edbank.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["EDU Chain"],
    module: "edbank-xyz/index.js",
    twitter: "edbankDao",
    forkedFrom: [],
    oracles: [], 
    audit_links: ["https://edbank.gitbook.io/edbank-docs/security/audit"],
    listedAt: 1737129301
  },
  {
    id: "5643",
    name: "SailFish Finance",
    address: null,
    symbol: "-",
    url: "https://sailfish.finance",
    description:
      "SailFish is the first DEX on Opencampus EDUCHAIN",
    chain: "EDU Chain",
    logo: `${baseIconsUrl}/sailfish-finance.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["EDU Chain"],
    module: "sailfish-v3/index.js",
    twitter: "SailFishFinance",
    forkedFrom: ["Uniswap V3"],
    oracles: [], 
    listedAt: 1737129307
  },
  {
    id: "5644",
    name: "Sologenic",
    address: null,
    symbol: "SOLO",
    url: "https://sologenic.org/",
    description:
      "Sologenic has created a fast & cost-effective decentralized ecosystem. Sologenic is committed to the asset trading industry by allowing users to trade different types of assets on the Sologenic’s DEX built on the XRP ledger",
    chain: "Ripple",
    logo: `${baseIconsUrl}/sologenic.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "solo-coin",
    cmcId: null,
    category: "Dexs",
    chains: ["Ripple"],
    module: "dummy.js",
    twitter: "realSologenic",
    forkedFrom: [],
    oracles: [], 
    github: ["sologenic"],
  },
  {
    id: "5645",
    name: "Metastable",
    address: null,
    symbol: "-",
    url: "https://mstable.io",
    description:
      "A decentralized stablecoin built on Sui",
    chain: "Sui",
    logo: `${baseIconsUrl}/metastable.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Sui"],
    module: "metastable-musd/index.js",
    twitter: "MetaStables",
    forkedFrom: [],
    oracles: ["Pyth"], // https://docs.mstable.io/developers/contracts, https://github.com/DefiLlama/DefiLlama-Adapters/pull/13154
    listedAt: 1737379687
  },
  {
    id: "5646",
    name: "SoneFi Perp",
    address: null,
    symbol: "-",
    url: "https://sonefi.xyz/#/trade",
    description:
      "One-stop trading Dex soneium, offering  AMM, Perp, AI Agent, and Meme Launch.",
    chain: "Soneium",
    logo: `${baseIconsUrl}/sonefi.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Soneium"],
    module: "sonefi-perp/index.js",
    twitter: "SoneFi_xyz",
    forkedFrom: [],
    oracles: ["Pyth"], //  https://docs.sonefi.xyz/overview/terminology#oracle-pricing
    audit_links: [],
    parentProtocol: "parent#sonefi",
    listedAt: 1737379697
  },
  {
    id: "5647",
    name: "Sailor",
    address: null,
    symbol: "-",
    url: "https://sailor.finance/",
    description:
      "High-Capital Efficiency AMM DEX & Launchpad built on Sei Network",
    chain: "Sei",
    logo: `${baseIconsUrl}/sailor.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sei"],
    module: "sailor-finance/index.js",
    twitter: "SailorFi",
    forkedFrom: ["Uniswap V3"],
    oracles: [], 
    audit_links: ["https://storage.googleapis.com/ktx-data/data/Verichains%20Public%20Report%20-%20Sailor%20Finance.pdf"],
    listedAt: 1737379699
  },
  {
    id: "5648",
    name: "O.LAB",
    address: null,
    symbol: "-",
    url: "https://www.olab.xyz/",
    description:
      "The World's Opinion Protocol, enabling anyone to create predictions using any token in a decentralized, permissionless way. The O.LAB product suite empower users to predict, trade, and verify truth like never before",
    chain: "Base",
    logo: `${baseIconsUrl}/o.lab.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Prediction Market",
    chains: ["Base"],
    module: "olab/index.js",
    twitter: "opinionlabsxyz",
    forkedFrom: ["Polymarket"],
    oracles: [], 
    audit_links: [],
    listedAt: 1737379705
  },
  {
    id: "5649",
    name: "Yoko",
    address: null,
    symbol: "-",
    url: "https://yoko.live/",
    description:
      "Yoko is a no-code platform for launching AI Agents",
    chain: "Sonic",
    logo: `${baseIconsUrl}/yoko.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "AI Agents",
    chains: ["Sonic"],
    module: "yoko-live/index.js",
    twitter: "yokodotlive",
    forkedFrom: [],
    oracles: [], 
    listedAt: 1737416137
  },
  {
    id: "5650",
    name: "Filament V1",
    address: null,
    symbol: "-",
    url: "https://filament.finance",
    description:
      "Filament is a super app for on-chain derivatives, built on Sei’s Parallelised EVM. It ensures high trading and capital efficiency, even in low liquidity situations, by using a hybrid model that combines a Central Limit Order Book (CLOB) and a Compartment-based Pool for order matching.",
    chain: "Sei",
    logo: `${baseIconsUrl}/filament-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Sei"],
    module: "filament-v2/index.js",
    twitter: "FilamentFinance",
    forkedFrom: [],
    oracles: [],
    parentProtocol: "parent#filament",
    listedAt: 1737482577
  },
  {
    id: "5651",
    name: "5ire Dapp Staking",
    address: null,
    symbol: "-",
    url: "https://www.5ire.org",
    description:
      "Stake 5ire tokens to earn a yield",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/5ire-dapp-staking.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    module: "5ire-dapp-staking/index.js",
    twitter: "5ireChain",
    forkedFrom: [],
    oracles: [],
    listedAt: 1737483187
  },
  {
    id: "5652",
    name: "Atoll",
    address: "sonic:0xd1DA314f7db27DbE3c61aC172bE13d86e67688B7",
    symbol: "ATOLL",
    url: "https://atoll.money/",
    description:
      "Atoll Protocol is a decentralized stable coin (peging coin) protocol built entirely of AMOs (Algorithmic Market Operations). We do our best effort to acquire more real yield for the protocol users",
    chain: "Sonic",
    logo: `${baseIconsUrl}/atoll.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Sonic"],
    module: "atoll/index.js",
    twitter: "atoll_protocol",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://github.com/Marvin051499/atoll-smart-contracts/blob/main/PeckShield-Audit-Report-Atoll-v1.0.pdf"],
    listedAt: 1737560233
  },
  {
    id: "5653",
    name: "VECTOR.FUN",
    address: null,
    symbol: "-",
    url: "https://www.vector.fun/",
    description:
      "APE MEMES WITH FRENS • LIVE ON APPLE + GOOGLE PLAY STORES",
    chain: "Solana",
    logo: `${baseIconsUrl}/vector.fun.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "VECTORDOTFUN",
    forkedFrom: [],
    oracles: [],
  },
  {
    id: "5654",
    name: "Umoja yBTC",
    address: null,
    symbol: "-",
    url: "https://umoja.xyz/smartcoins",
    description:
      "$yBTC is a multi-strategy, next-gen BTC yield vault token providing the lowest risk, highest yields for Bitcoin.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/umoja-ybtc.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Basis Trading",
    chains: ["Arbitrum"],
    module: "umoja-ybtc/index.js",
    twitter: "UmojaProtocol",
    forkedFrom: [],
    oracles: [],
    parentProtocol: "parent#umoja-protocol",
    listedAt: 1737625162
  },
  {
    id: "5655",
    name: "Resolv",
    address: null,
    symbol: "-",
    url: "https://resolv.xyz/",
    description:
      "Resolv is a protocol that maintains USR, a stablecoin fully backed by ETH and pegged to the US Dollar. The stablecoin’s delta-neutral design ensures price stability, and is backed by an innovative insurance pool (RLP) to provide additional security and overcollateralization.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/resolv.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Basis Trading",
    chains: ["Ethereum"],
    module: "resolv/index.js",
    twitter: "ResolvLabs",
    forkedFrom: [],
    oracles: ["Pyth"], // https://docs.resolv.xyz/litepaper/for-developers/smart-contracts
    stablecoins: ["resolv-usd"],
    github: ["resolv-im"],
    listedAt: 1737626553
  },
  {
    id: "5656",
    name: "Liquity V2",
    address: "0x6DEA81C8171D0bA574754EF6F8b412F2Ed88c54D",
    symbol: "LQTY",
    url: "https://www.liquity.org/",
    description:
      "Liquity is a decentralized borrowing protocol that allows you to draw 0% interest loans against Ether used as collateral.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/liquity-v2.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Ethereum"],
    module: "liquity-v2/index.js",
    twitter: "LiquityProtocol",
    forkedFrom: [],
    oracles: [],
    parentProtocol: "parent#liquity",
    audit_links: ["https://docs.liquity.org/v2-documentation/technical-resources"],
    listedAt: 1737631098
  },
  {
    id: "5657",
    name: "ZTLN-P",
    address: null,
    symbol: "-",
    url: "https://zoth.io/",
    description:
      "Zoth is a community-first restaking ecosystem for RWAFi.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ztln-p.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA",
    chains: ["Ethereum"],
    module: "zoth-ztlnp/index.js",
    twitter: "zothdotio",
    forkedFrom: [],
    oracles: [],
    parentProtocol: "parent#zoth",
    audit_links: [],
    listedAt: 1737640913
  },
  {
    id: "5658",
    name: "Moonlander",
    address: "cronos_zkevm:0xe8E4A973Bb36E1714c805F88e2eb3A89f195D04f",
    symbol: "MLP",
    url: "https://moonlander.trade/",
    description:
      "Moonlander is a decentralized perpetual trading platform on Cronos zkEVM chain that offers both a staking pool and on-chain perpetuals, primed to empower all traders and stakers with galactic opportunities. Leveraging on the latest layer 2 zk-technology, transactions on Moonlander are executed at higher speed and lower fees",
    chain: "Cronos zkEVM",
    logo: `${baseIconsUrl}/moonlander.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Cronos zkEVM"],
    module: "moonlander/index.js",
    twitter: "MoonlanderTrade",
    forkedFrom: ["APX Finance"],
    oracles: ["Pyth"], // https://docs.moonlander.trade/
    listedAt: 1737641003
  },
  {
    id: "5659",
    name: "Treble",
    address: "base:0xb96450dcb16e4a30b999cb5f4087bae9c0ffac4e",
    symbol: "TREB",
    url: "https://trebleswap.com",
    description:
      "Treble is the first modular V4 DEX on Base with a full-suite DeFi Hub offering cross-chain swaps, fiat on/off ramps, CEX onramps, no-KYC crypto spending, DeFAI integrations and passive income through farming and staking, bringing seamless accessibility to the Base ecosystem",
    chain: "Base",
    logo: `${baseIconsUrl}/treble.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Base"],
    module: "trebleswap/index.js",
    twitter: "TrebleSwap",
    forkedFrom: ["Algebra Integral"],
    oracles: [],
    github: ["trebleswap"],
    listedAt: 1737647275
  },
  {
    id: "5660",
    name: "Ethos Network",
    address: null,
    symbol: "-",
    url: "https://ethos.network/",
    description:
      "Ethos is a credibility platform that creates a more trusted web3 ecosystem",
    chain: "Base",
    logo: `${baseIconsUrl}/ethos-network.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "SoFi",
    chains: ["Base"],
    module: "ethos-network/index.js",
    twitter: "ethos_network",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://whitepaper.ethos.network/security/smart-contract-audits"],
    listedAt: 1737664915
  },
  {
    id: "5661",
    name: "Starbase",
    address: null,
    symbol: "-",
    url: "https://www.starbase.ag/",
    description:
      "Advanced DEX Aggregator on Base",
    chain: "Base",
    logo: `${baseIconsUrl}/starbase.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "starbase_ag",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://starbase-hub.gitbook.io/guides/trust-and-safety/how-secure-is-starbase"],
  },
  {
    id: "5662",
    name: "InfinityPools",
    address: null,
    symbol: "-",
    url: "https://infinitypools.finance/",
    description:
      "InfinityPools is a decentralized exchange that can offer unlimited leverage on any asset, with no liquidations, no counterparty risk & no oracles",
    chain: "Base",
    logo: `${baseIconsUrl}/infinitypools.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Base"],
    module: "infinityPools/index.js",
    twitter: "Infpools",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://docs.infinitypools.finance/protocol-overview/security#audits"],
    listedAt: 1737725805
  },
  {
    id: "5663",
    name: "EddyFinance V3",
    address: null,
    symbol: "-",
    url: "https://www.eddy.finance/",
    description:
      "EddyFinance is a dex built on top of ZetaChain",
    chain: "ZetaChain",
    logo: `${baseIconsUrl}/eddyfinance.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["ZetaChain"],
    module: "eddyfinance-v3/index.js",
    twitter: "eddy_protocol",
    forkedFrom: ["Uniswap V3"],
    oracles: [],
    audit_links: [],
    parentProtocol: "parent#eddyfinance",
    listedAt: 1737725817
  },
  {
    id: "5664",
    name: "Reti Pooling",
    address: null,
    symbol: "-",
    url: "https://reti.nodely.io/",
    description:
      "The Réti Pooling protocol is a decentralized, non-custodial solution that enables users to pool their Algorand stake, allowing anyone to trustlessly stake with Validators and earn rewards",
    chain: "Algorand",
    logo: `${baseIconsUrl}/reti-pooling.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Staking Pool",
    chains: ["Algorand"],
    module: "reti-openpooling/index.js",
    twitter: "txnlab",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://github.com/algorandfoundation/reti/tree/main/contracts/contracts/audit"],
    listedAt: 1737725853
  },
  {
    id: "5665",
    name: "ArtexSwap",
    address: null,
    symbol: "-",
    url: "https://app.artexswap.xyz/#/swap",
    description:
      "The Leading Native Artela_Network DEX Powered by Artela EVM++",
    chain: "Artela",
    logo: `${baseIconsUrl}/artexswap.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Artela"],
    module: "artexswap_xyz/index.js",
    twitter: "artexswap",
    forkedFrom: ["Uniswap V2"],
    oracles: [],
    listedAt: 1737725859
  },
  {
    id: "5666",
    name: "Babypie",
    address: null,
    symbol: "-",
    url: "https://www.babylon.magpiexyz.io/stake",
    description:
      "Babypie is a top-tier SubDAO launched by Magpie that concentrates on liquid staking services for Bitcoin using Babylon",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/babypie.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Anchor BTC",
    chains: ["Ethereum","Bitcoin"],
    module: "babypie/index.js",
    twitter: "Babypiexyz_io",
    forkedFrom: [],
    oracles: [],
    parentProtocol: "parent#magpie-ecosystem",
    listedAt: 1737725867
  },
  {
    id: "5667",
    name: "Sophon Farm",
    address: null,
    symbol: "-",
    url: "https://farm.sophon.xyz/",
    description:
      "Deposit tokens to start farming Sophon Points (SP) which can later be redeemed for $SOPH",
    chain: "Sophon",
    logo: `${baseIconsUrl}/sophon-farm.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Sophon"],
    module: "sophon-farm/index.js",
    twitter: "sophon",
    forkedFrom: [],
    oracles: [],
    audit_links: ["https://docs.sophon.xyz/links/audits"],
    listedAt: 1737831373
  },
  {
    id: "5668",
    name: "SuperSwap Ink",
    address: null,
    symbol: "-",
    url: "https://superswap.ink/",
    description:
      "SuperSwap is the first decentralized exchange (DEX) aggregator built on Ink, the Layer 2 blockchain developed by Kraken",
    chain: "Ink",
    logo: `${baseIconsUrl}/superswap-ink.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Ink"],
    module: "dummy.js",
    twitter: "SuperSwapINK",
    forkedFrom: [],
    oracles: [],
  },
  {
    id: "5669",
    name: "Tribe.run",
    address: null,
    symbol: "-",
    url: "https://www.tribe.run/",
    description:
      "Crypto social on Solana  ",
    chain: "Solana",
    logo: `${baseIconsUrl}/tribe.run.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "SoFi",
    chains: ["Solana"],
    module: "tribe-run/index.js",
    twitter: "tribedotrun",
    forkedFrom: [],
    oracles: [],
    listedAt: 1737921131
  },
  {
    id: "5670",
    name: "Nexion",
    address: "pulse:0xF2Da3942616880E52e841E5C504B5A9Fba23FFF0",
    symbol: "NEON",
    url: "https://nexionpulse.com/",
    description:
      "NEXION is a dApp ecosystem that offers users a variety of ways to participate and earn rewards",
    chain: "Pulse",
    logo: `${baseIconsUrl}/nexion.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Pulse"],
    module: "nexion/index.js",
    twitter: "nexionpulse",
    forkedFrom: [],
    oracles: [],
    listedAt: 1737921507
  },
  {
    id: "5671",
    name: "Hfun",
    address: "hyperliquid:0xbaf265ef389da684513d98d68edf4eae",
    symbol: "HFUN", 
    url: "https://hypurr.fun/",
    description:
      "Hfun is a Telegram trading bot and launchpad for launching and trading memecoins on Hyperliquid, tracking PnL, sniping new launches, accessing whale chats, and competing with others",
    chain: "Hyperliquid",
    logo: `${baseIconsUrl}/hfun.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "hypurr-fun",
    cmcId: "34624",
    category: "Launchpad",
    chains: ["Hyperliquid"],
    module: "dummy.js",
    twitter: "Hypurrfun",
    forkedFrom: [],
    oracles: [],
  },
  {
    id: "5672",
    name: "Vicuna Finance",
    address: null,
    symbol: "-",
    url: "https://vicunafinance.com",
    description:
      "Vicuna Finance operates as a native borrow/lending protocol, facilitating leveraged yield farming on the Sonic Blockchain. Lenders can earn yields on their tokens, while borrowers gain access to capital-efficient, undercollateralized loans for leveraged yield farming positions",
    chain: "Sonic",
    logo: `${baseIconsUrl}/vicuna-finance.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Leveraged Farming",
    chains: ["Sonic"],
    module: "vicuna/index.js",
    twitter: "VicunaFinance",
    forkedFrom: ["Beefy"],
    oracles: [],
    github: ["VicunaFinance-com"],
    listedAt: 1737981273
  },
  {
    id: "5673",
    name: "Coin8",
    address: null,
    symbol: "-",
    url: "https://www.coin8.co",
    description:
      "Coin8 Exchange is a cryptocurrency platform offering spot and futures trading with high-leverage options and AI-assisted trading features",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/coin8.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CEX",
    chains: ["Ethereum", "Bitcoin"],
    module: "coin8-cex/index.js",
    twitter: "Coin8_Exchange",
    forkedFrom: [],
    oracles: [],
    listedAt: 1737981973
  },
  {
    id: "5674",
    name: "Coffer Network",
    address: null,
    symbol: "-",
    url: "https://www.coffer.network",
    description:
      "Coffer Network is a decentralized programmable Smart Account infrastructure for Bitcoin",
    chain: "Bitcoin",
    logo: `${baseIconsUrl}/coffer-network.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Bitcoin"],
    module: "coffer-network/index.js",
    twitter: "CofferNetwork",
    forkedFrom: [],
    oracles: [],
    github: ["coffer-network"],
    listedAt: 1737988177
  },
  {
    id: "5675",
    name: "Sonus Exchange AMM",
    address: "soneium:0x12BE6BA8Deaa28BC5C2FD9cdfceB47EB4FDB0B35",
    symbol: "SONUS",
    url: "https://sonus.exchange",
    description:
      "Your All-in-One Trading Destination. Setting the Standard: The Native DEX on Soneium Chain, Shaping the Future of Trading and Liquidity. Join the prime ve(3,3) dex!",
    chain: "Soneium",
    logo: `${baseIconsUrl}/sonus-exchange-amm.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Soneium"],
    module: "sonusexchange/index.js",
    twitter: "SonusExchange",
    forkedFrom: ["Solidly"],
    oracles: [],
    parentProtocol: "parent#sonus",
    listedAt: 1738001611
  },
  {
    id: "5676",
    name: "Sonus Exchange CLMM",
    address: "soneium:0x12BE6BA8Deaa28BC5C2FD9cdfceB47EB4FDB0B35",
    symbol: "SONUS",
    url: "https://sonus.exchange",
    description:
      "Your All-in-One Trading Destination. Setting the Standard: The Native DEX on Soneium Chain, Shaping the Future of Trading and Liquidity. Join the prime ve(3,3) dex!",
    chain: "Soneium",
    logo: `${baseIconsUrl}/sonus-exchange-clmm.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Soneium"],
    module: "sonusexchange-cl/index.js",
    twitter: "SonusExchange",
    forkedFrom: ["Uniswap V3"],
    oracles: [],
    parentProtocol: "parent#sonus",
    listedAt: 1738001617
  },
  {
    id: "5677",
    name: "NOXA",
    address: null,
    symbol: "-",
    url: "https://dex.noxa.fi/#/swap",
    description:
      "Decentralized exchange on Abstract",
    chain: "Abstract",
    logo: `${baseIconsUrl}/noxa.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Abstract"],
    module: "noxa-fi/index.js",
    twitter: "Noxa_Fi",
    forkedFrom: ["Uniswap V2"],
    oracles: [],
    listedAt: 1738007747
  },
  {
    id: "5678",
    name: "Reservoir Tools AMM",
    address: null,
    symbol: "-",
    url: "https://swap.reservoir.tools/#/swap",
    description:
      "Uniswap V2 fork",
    chain: "Abstract",
    logo: `${baseIconsUrl}/reservoir-tools.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Zero Network","Abstract","Ink","Shape"],
    module: "reservoir-tools-v2/index.js",
    twitter: "reservoir0x",
    forkedFrom: ["Uniswap V2"],
    oracles: [],
    parentProtocol: "parent#reservoir-tools",
    listedAt: 1738007753
  },
  {
    id: "5679",
    name: "Reservoir Tools CLMM",
    address: null,
    symbol: "-",
    url: "https://swap.reservoir.tools/#/swap",
    description:
      "Uniswap V3 fork",
    chain: "Abstract",
    logo: `${baseIconsUrl}/reservoir-tools.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Zero Network","Abstract","Ink","Shape","Redstone"],
    module: "reservoir-tools-v3/index.js",
    twitter: "reservoir0x",
    forkedFrom: ["Uniswap V3"],
    oracles: [],
    parentProtocol: "parent#reservoir-tools",
    listedAt: 1738007759
  },
  {
    id: "5680",
    name: "Beets DEX V3", 
    address: "sonic:0x2d0e0814e62d80056181f5cd932274405966e4f0",
    symbol: "BEETS",
    url: "https://beets.fi",
    description:
      "The Flagship LST Hub on Sonic. From seamless staking to earning real yield on LST-focused liquidity pools, beets is the ultimate destination for your liquid-staked tokens.",
    chain: "Sonic",
    logo: `${baseIconsUrl}/beets-sml.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    module: "beethovenx-v3/index.js",
    twitter: "beets_fi",
    forkedFrom: ["Balancer V3"],
    parentProtocol: "parent#beethoven-x",
    listedAt: 1738009211
  },
  {
    id: "5681",
    name: "RaccoonSwap", 
    address: null,
    symbol: "-",
    url: "https://raccoonswap.finance/",
    description:
      "DEX Platform for the Parex Ecosystem",
    chain: "Parex",
    logo: `${baseIconsUrl}/raccoonswap.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Parex"],
    module: "raccoonswap/index.js",
    twitter: "raccoonswap",
    forkedFrom: ["Uniswap V2"],
    listedAt: 1738079995
  },
  {
    id: "5682",
    name: "Shadow Exchange Legacy", 
    address: "sonic:0x3333b97138D4b086720b5aE8A7844b1345a33333",
    symbol: "SHADOW",
    url: "https://www.shadow.so/",
    description:
      "Native DEX on Sonic",
    chain: "Sonic",
    logo: `${baseIconsUrl}/shadow-exchange.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    module: "shadow-legacy/index.js",
    twitter: "ShadowOnSonic",
    forkedFrom: ["Solidly"],
    parentProtocol: "parent#shadow-exchange",
    listedAt: 1738081015
  },
  {
    id: "5683",
    name: "Sonic Gateway", 
    address: null,
    symbol: "-",
    url: "https://gateway.soniclabs.com/ethereum/sonic/s",
    description:
      "Canonical Bridge for Sonic chain",
    chain: "Sonic",
    logo: `${baseIconsUrl}/sonic-gateway.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Sonic"],
    module: "sonic-gateway/index.js",
    twitter: "SonicLabs",
    forkedFrom: [],
    listedAt: 1738081153
  },
  {
    id: "5684",
    name: "ZOO.FUN", 
    address: null,
    symbol: "-",
    url: "https://www.zoo.fun/",
    description:
      "Platform for new coin launches on Abstract chain",
    chain: "Abstract",
    logo: `${baseIconsUrl}/zoo.fun.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Abstract"],
    module: "zoodotfun/index.js",
    twitter: "zoodotfun",
    forkedFrom: [],
    listedAt: 1738095359
  },
  {
    id: "5685",
    name: "Quill Finance", 
    address: null,
    symbol: "-",
    url: "https://app.quill.finance/",
    description:
      "Quill Finance: An over-collateralized stablecoin protocol on Scroll's zk-Rollup network",
    chain: "Scroll",
    logo: `${baseIconsUrl}/quill-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Scroll"],
    module: "quill-fi/index.js",
    twitter: "QuillFi",
    forkedFrom: ["Liquity V2"],
    listedAt: 1738101111
  },
  {
    id: "5686",
    name: "XPress Protocol", 
    address: null,
    symbol: "-",
    url: "https://xpressprotocol.com",
    description:
      "On-chain CLOB dex on Sonic.",
    chain: "Sonic",
    logo: `${baseIconsUrl}/xpress-protocol.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    module: "xpress/index.js",
    twitter: "XPRESSprotocol",
    forkedFrom: [],
    listedAt: 1738146854
  },
  {
    id: "5687",
    name: "Moose", 
    address: null,
    symbol: "-",
    url: "https://moose.market",
    description:
      "Moose is a decentralized protocol on the Solana blockchain, designed to provide users with opportunities to generate yield by depositing USDC into various vaults. These vaults utilize multiple sophisticated strategies, including delta-neutral, market making, and trading strategies, to optimize returns for depositors.",
    chain: "Solana",
    logo: `${baseIconsUrl}/moose.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Solana"],
    module: "moose/index.js",
    twitter: "moose_market",
    forkedFrom: [],
    listedAt: 1738147302
  },
  {
    id: "5688",
    name: "Origin Sonic", 
    address: null,
    symbol: "-",
    url: "https://www.originprotocol.com",
    description:
      "Liquid staking for Sonic with boosted yield and peg stability",
    chain: "Sonic",
    logo: `${baseIconsUrl}/origin-sonic.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Sonic"],
    module: "originsonic/index.js",
    twitter: "OriginProtocol",
    forkedFrom: [],
    parentProtocol: "parent#origin-defi",
    audit_links: ["https://docs.originprotocol.com/security-and-risk/audits"],
    listedAt: 1738147902
  },
  {
    id: "5689",
    name: "Libre Capital", 
    address: null,
    symbol: "-",
    url: "https://www.librecapital.com/",
    description:
      "Libre is building the investment infrastructure to enable asset managers to seamlessly connect with distributors and enable unparalleled access to global alternatives investment funds. In addition, Libre is working on enabling access to value-add services in the alternative assets ecosystem such as collateralized lending and automated rebalancing. Currently, Libre only makes its tokenized funds available to institutional and accredited investors",
    chain: "Polygon",
    logo: `${baseIconsUrl}/libre-capital.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA",
    chains: ["Polygon","Solana","Near","Injective","Sui"],
    module: "libre-capital/index.js",
    twitter: "librecap",
    forkedFrom: [],
    listedAt: 1738172664
  },
  {
    id: "5690",
    name: "Uniswap V4",
    address: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    symbol: "UNI",
    url: "https://uniswap.org/",
    description: "Uniswap v4 inherits all of the capital efficiency gains of Uniswap v3, but provides flexibility via hooks and gas optimizations across the entire lifecycle",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/uniswap-v4.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Ethereum","Optimism","Base","Arbitrum","Polygon","Blast","Zora","Ink","Soneium","Avalanche","Binance"],
    module: "uniswap-v4/index.js",
    twitter: "Uniswap",
    audit_links: [
      "https://github.com/Uniswap/v4-core/tree/main/docs/security/audits",
      "https://github.com/Uniswap/v4-periphery/tree/main/audits",
    ],
    oracles: [],
    parentProtocol: "parent#uniswap",
    listedAt: 1738172667,
  },
  {
    id: "5691",
    name: "Abstract",
    address: null,
    symbol: "-",
    url: "https://www.abs.xyz/",
    description: "Abstract is a Layer 2 on Ethereum using zero-knowledge (ZK) rollups to scale by batching off-chain transactions and verifying them on-chain with ZK proofs, while remaining EVM-compatible for easy smart contract deployment",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/abstract.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "abstract/index.js",
    twitter: "AbstractChain",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5692",
    name: "Ancient8",
    address: null,
    symbol: "-",
    url: "https://ancient8.gg/",
    description: "Ancient8 Chain is a gaming-focused community-driven Ethereum Layer 2, powered by the OP Stack and enhanced with Celestia, designed to address the scalability and adoption challenges faced by web3 gaming and consumer DApps",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ancient8.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "ancient8/index.js",
    twitter: "Ancient8_gg",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5693",
    name: "Cyber",
    address: null,
    symbol: "-",
    url: "https://cyber.co/",
    description: "Cyber is an L2 built on the OP stack, designed for social interactions. It offers native yield from Ethereum restaking, native smart accounts, seedless wallets, a social graph protocol and decentralized storage via CyberDB",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/cyber.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "cyber/index.js",
    twitter: "BuildOnCyber",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5694",
    name: "Fraxtal",
    address: null,
    symbol: "FXTL",
    url: "https://frax.finance",
    description: "Fraxtal, launched by Frax finance, is an L2 ETH scaling solution featuring a modular rollup design on the OP stack. It uses frxETH for gas, adds Blockspace Incentives (FLOX) for rewarding engagement, and offers a veFXS contract for cross-chain staking",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/fraxtal.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "fraxtal",
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "fraxtal/index.js",
    twitter: "fraxfinance",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5695",
    name: "Gravity",
    address: "0x9c7beba8f6ef6643abd725e45a4e8387ef260649",
    symbol: "G",
    url: "https://gravity.xyz/",
    description: "Gravity, built by Galxe, is an omnichannel settlement layer designed for mass adoption. It uses Zero-Knowledge Proofs, staking architecture, and advanced consensus mechanisms for high performance.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/gravity.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "g-token",
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "gravity/index.js",
    twitter: "GravityChain",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5696",
    name: "K2",
    address: null,
    symbol: "-",
    url: "https://karak.network/",
    description: "Karak Network is a universal restaking layer that enables the use of staked assets from various blockchains to secure new protocols, reducing the need for their own validator rewards",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/k2.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "karak_chain/index.js",
    twitter: "Karak_Network",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5697",
    name: "Kroma",
    address: "kroma:0x25500000d700bbe27104577cccce8eabcc96c8ad",
    symbol: "KRO",
    url: "https://kroma.network/",
    description: "Kroma is developing a universal ZK Rollup on the Optimism Bedrock architecture, currently using an Optimistic Rollup with ZK fault proofs and a Scroll-based zkEVM. It aims to switch to a ZK Rollup as proof generation becomes faster and cheaper",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/kroma.png`,
    audits: "0",
    audit_note: null,
    gecko_id: "kroma",
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "kroma/index.js",
    twitter: "kroma_network",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5698",
    name: "Orderly Chain",
    address: "0xabd4c63d2616a5201454168269031355f4764337",
    symbol: "ORDER",
    url: "https://orderly.network/",
    description: "Orderly Chain is a blockchain that uses the OP Stack to enable fast, secure, and scalable trading across multiple blockchains by recording and settling transactions",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/orderly-chain.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "orderly/index.js",
    twitter: "OrderlyNetwork",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5699",
    name: "Rari Chain",
    address: null,
    symbol: "-",
    url: "https://rarichain.org/",
    description: "RARI Chain is an EVM-equivalent Layer 3 blockchain powered by Arbitrum, featuring embedded royalties at the node level, low transaction costs, fast transaction times, and advanced developer tooling, designed to support NFT creators and their ecosystems",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/rari-chain.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Arbitrum"],
    module: "rari_chain/index.js",
    twitter: "RariChain",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5700",
    name: "Redstone",
    address: null,
    symbol: "-",
    url: "https://redstone.xyz/",
    description: "Redstone is an Optimistic Rollup on the OP Stack, reducing costs with Plasma mode for data availability, posting input commitments to Ethereum (L1) while ensuring data integrity via offchain availability, DA challenges, and fault-proof mechanisms",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/redstone.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "redstone/index.js",
    twitter: "redstonexyz",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5701",
    name: "World Chain",
    address: null,
    symbol: "-",
    url: "https://world.org/",
    description: "World Chain is a permissionless Layer 2 blockchain on Ethereum, built with the OP Stack, offering scalability, security, Sybil resistance, community governance, and is part of the OP Superchain ecosystem",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/world-chain.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "wc/index.js",
    twitter: "worldcoin",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5702",
    name: "Zero Network",
    address: null,
    symbol: "-",
    url: "https://zero.network/",
    description: "Zero Network is an EVM-compatible, gasless rollup built on the ZK Stack, enabling onchain interactions by using a custom paymaster to cover transaction costs and allowing dApps to be easily ported from Ethereum and other L2 networks",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zero-network.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "zero_network/index.js",
    twitter: "zerodotnetwork",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5703",
    name: "Zkfair",
    address: null,
    symbol: "-",
    url: "https://zkfair.io/",
    description: "ZKFair is the a community ZK-L2 based on Polygon CDK and Celestia DA, powered by Lumoz, a ZK-RaaS provider. ZKFair utilizes the stablecoin USDC as the gas token and is 100% EVM compatible, has minimal fees, and a robust security",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zkfair.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Chain",
    chains: ["Ethereum"],
    module: "zkfair/index.js",
    twitter: "ZKFCommunity",
    audit_links: [],
    oracles: [],
  },
  {
    id: "5704",
    name: "Rooster Protocol",
    address: null,
    symbol: "-", // none (pre-tge)
    url: "https://www.rooster-protocol.xyz/",
    description: "Rooster Protocol is the liquidity hub for real-world assets on Plume Network. Built with the innovative Dynamic Distribution AMM by Maverick Protocol and a ve(3,3) Flywheel, Rooster enables efficient liquidity with built-in on-chain rewards",
    chain: "Plume",
    logo: `${baseIconsUrl}/rooster-protocol.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Plume"],
    module: "rooster/index.js",
    twitter: "roosterprotocol",
    audit_links: ["https://github.com/shieldify-security/audits-portfolio/blob/main/reports/RoosterProtocol-Security-Review.pdf"],
    oracles: [],
    forkedFrom: ["Maverick V2"],
    listedAt: 1738203899 
  },
  {
    id: "5705",
    name: "Ethos Markets",
    address: null,
    symbol: "-",
    url: "https://ethos.markets/",
    description: "Ethos Markets provides reputation markets, allowing you to trade both trust and distrust on someone's reputation",
    chain: "Base",
    logo: `${baseIconsUrl}/ethos-markets.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "SoFi",
    chains: ["Base"],
    module: "ethos-markets/index.js",
    twitter: "ethos_network",
    audit_links: ["https://whitepaper.ethos.network/security/smart-contract-audits"],
    oracles: [],
    forkedFrom: [],
    listedAt: 1738204217
  },
  {
    id: "5706",
    name: "Sirio Finance",
    address: null,
    symbol: "-",
    url: "https://app.sirio.finance",
    description: "The DeFAI Lending & Borrowing Layer of hedera",
    chain: "Hedera",
    logo: `${baseIconsUrl}/sirio-finance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Hedera"],
    module: "sirio-fi/index.js",
    twitter: "SirioFinance",
    oracles: [],
    forkedFrom: [],
    listedAt: 1738233223
  },
  {
    id: "5707",
    name: "Bondlink Finance",
    address: null,
    symbol: "-",
    url: "https://www.bondlink.finance",
    description: "An Omnichain stable coin infrastructure that aggregates private lending opportunities in emerging economies combined with DeFi.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/bondlink-finance.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "RWA",
    chains: ["Ethereum"],
    module: "bondlink/index.js",
    twitter: "BondlinkFinance",
    oracles: [],
    forkedFrom: [],
    audit_links: ["https://beosin.com/audits/Bondlink_202412031841.pdf"],
    listedAt: 1738233515
  },
  {
    id: "5708",
    name: "Enclabs",
    address: null,
    symbol: "-",
    url: "https://www.enclabs.finance/",
    description: "Enclabs is a risk-adjusted and isolated markets lending/borrowing protocol",
    chain: "Sonic",
    logo: `${baseIconsUrl}/enclabs.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Sonic"],
    module: "enclabs/index.js",
    twitter: "EnclabsFi",
    oracles: [],
    forkedFrom: [],
    audit_links: [],
    listedAt: 1738260859
  },
  {
    id: "5709",
    name: "Angles",
    address: null,
    symbol: "-",
    url: "https://angles.fi",
    description: "Angles enhances Sonic with performant and secure LST ($anS). anS is compatible and can be used in DeFi to get maximum yield out of your Sonics",
    chain: "Sonic",
    logo: `${baseIconsUrl}/angles.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Sonic"],
    module: "angles/index.js",
    twitter: "Angles_Sonic",
    oracles: [],
    forkedFrom: [],
    audit_links: [],
    listedAt: 1738269622
  },
  {
    id: "5710",
    name: "Overnight Finance",
    address: "optimism:0x3b08fcd15280e7b5a6e404c4abb87f7c774d1b2e",
    symbol: "OVN",
    url: "https://overnight.fi",
    description: "Overnight Finance is an asset management protocol offering passive yield products based on delta-neutral strategies, primarily for conservative stablecoin investors.",
    chain: "Optimism",
    logo: `${baseIconsUrl}/overnight-finance.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: "overnight-finance",
    cmcId: "28229",
    category: "CDP",
    chains: ["Optimism", "Arbitrum"],
    module: "overnight-fi/index.js",
    twitter: "overnight_fi",
    oracles: [],
    forkedFrom: [],
    audit_links: [
      "https://github.com/ovnstable/ovnstable-app/blob/master/audits/hacken_2022-02-03.pdf",
      "https://github.com/ovnstable/ovnstable-core/blob/master/audits/hacken_2022-02-03.pdf",
      "https://github.com/ovnstable/ovnstable-core/blob/master/audits/ackee_2023-03-03.pdf",
    ],
    github: ["ovnstable"],
    listedAt: 1738320172
  },
  {
    id: "5711",
    name: "Perena",
    address: null,
    symbol: "-",
    url: "https://perena.org",
    description: "Perena is building the infrastructure for stablecoins on Solana, starting with a novel AMM, Numéraire.",
    chain: "Solana",
    logo: `${baseIconsUrl}/perena.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Solana"],
    module: "perena/index.js",
    twitter: "Perena__",
    oracles: [],
    forkedFrom: [],
    listedAt: 1738322143
  },
  {
    id: "5712",
    name: "Ether Strategy",
    address: null,
    symbol: "-",
    url: "https://ethsr.xyz/",
    description: "Onchain Microstrategy. Transparent, open source, for the community.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ether-strategy.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    module: "eth-strategy/index.js",
    twitter: "ethstrateg",
    oracles: [],
    forkedFrom: [],
    listedAt: 1738322943
  },
  {
    id: "5713",
    name: "CreateMyToken",
    address: null,
    symbol: "-",
    url: "https://www.createmytoken.com/",
    description: "Create your own token in just 1 minute and deploy it on Solana, Ethereum, Base, BNB Smart Chain and more! No code, no setup, no login, and free.",
    chain: "Base",
    logo: `${baseIconsUrl}/createmytoken.png`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Ethereum","Base","Binance","Polygon","Arbitrum","Avalanche","Optimism","Blast"],
    module: "createmytoken/index.js",
    twitter: "CreateMyToken",
    oracles: [],
    forkedFrom: [],
    listedAt: 1738346891
  },
  {
    id: "5714",
    name: "Rabby Wallet",
    address: null,
    symbol: "-",
    url: "https://rabby.io/",
    description: "A wallet for Ethereum and all EVM chains By DeBank",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/rabby-wallet.png`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Wallets",
    chains: ["Ethereum","Base","Binance","Arbitrum"],
    module: "dummy.js",
    twitter: "Rabby_io",
    oracles: [],
    forkedFrom: [],
    audit_links: ["https://github.com/RabbyHub/Rabby/tree/develop/docs"],
    github: ["RabbyHub"]
  },
  {
    id: "5715",
    name: "ƒlaunch",
    address: null,
    symbol: "-",
    url: "https://flaunch.gg",
    description: "Buy, sell and launch memes. 100% of trading fees go to creators and buybacks. Powered by Uniswap V4.",
    chain: "Base",
    logo: `${baseIconsUrl}/ƒlaunch.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    module: "flaunch/index.js",
    twitter: "flaunchgg",
    oracles: [],
    forkedFrom: [],
    listedAt: 1738497748
  },
  {
    id: "5716",
    name: "SupraFi",
    address: null,
    symbol: "-",
    assetToken: "sS",
    url: "https://suprafi.app/",
    description: "SupraFi is a cutting-edge platform offering seamless liquid staking solutions, enabling users to stake their $S tokens, earn substantial rewards, and maintain liquidity.",
    chain: "Sonic",
    logo: `${baseIconsUrl}/suprafi.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Liquid Staking",
    chains: ["Sonic"],
    module: "suprafi/index.js",
    twitter: "SupraFi_Sonic",
    oracles: [],
    forkedFrom: [],
    listedAt: 1738581869
  },
  {
    id: "5717",
    name: "VinuFinance",
    address: null,
    symbol: "-",
    url: "https://vinufinance.app/borrow",
    description: "Oracle-less, no-liquidation lending on VinuChain",
    chain: "VinuChain",
    logo: `${baseIconsUrl}/vinufinance.jpg`,
    audits: "0",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["VinuChain"],
    module: "vinufinance/index.js",
    twitter: "VinuChain",
    oracles: [],
    forkedFrom: [],   // added the github in the chain instead of here
    listedAt: 1738582017
  },
  {
    id: "5718",
    name: "Sonic Market Liquidity Vault",
    address: null,
    symbol: "-",
    url: "https://www.sonic.market/trade",
    description: "Sonic Market is a decentralized exchange (DEX) built on the Sonic blockchain, designed to bring a fully on-chain Central Limit Order Book (CLOB) experience. Unlike traditional Automated Market Makers (AMMs), Sonic Market leverages its advanced order book technology, LOBSTER (Limit Order Book with Segment Tree for Efficient oRder-matching), to provide fast, gas-efficient order matching directly on the Sonic blockchain.",
    chain: "Sonic",
    logo: `${baseIconsUrl}/sonic-market-liquidity-vault.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Dexs",
    chains: ["Sonic"],
    module: "sonic-market-liquidity-vault/index.js",
    twitter: "sonic_market",
    oracles: [],
    forkedFrom: [],  
    audit_links: ["https://docs.clober.io/assets/files/Clober_Liquidity_Vault_v2_Audit_Report_by_Trust_Security-7d8bcf5e7f6b488122f7974aef1d70c7.pdf",
                  "https://docs.clober.io/assets/files/2025_1_Clober_LiquidityVault-50ac1ebac2c19b9449389bcdf1c788bf.pdf"
                 ],
    parentProtocol: "parent#sonic-market",
    listedAt: 1738582281
  },
  {
    id: "5719",
    name: "WINK",
    address: null,
    symbol: "-",
    url: "https://wink.finance",
    description: "WINK Finance is the Web3 division of the WINK project, offering a comprehensive ecosystem that includes staking, farming, lending, and DEX aggregation for both tokens and NFTs. Designed to enhance accessibility and efficiency across multiple blockchains, WINK Finance provides seamless DeFi solutions within the broader WINK ecosystem.",
    chain: "Polygon",
    logo: `${baseIconsUrl}/wink-finance.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Farm",
    chains: ["Polygon"],
    module: "wink/index.js",
    twitter: "WinkFinance",
    oracles: [],
    forkedFrom: [],  
    audit_links: ["https://skynet.certik.com/projects/wink"],
    listedAt: 1738582660
  },
];
export default data4;
