import type {Protocol} from './types'
import { baseIconsUrl } from "../constants";

export default [
{
    id: "1410",
    name: "Cropper",
    address: "solana:DubwWZNWiNGMMeeQHPnMATNj77YZPZSAz2WVR5WjLJqz",
    symbol: "CRP",
    url: "https://cropper.finance",
    description: "Cropper is an automated market maker (AMM) built on the Solana blockchain which enable lightning-fast trades, shared liquidity and new features for earning yield.",
    chain: "Solana",
    logo: `${baseIconsUrl}/cropper.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "cropperfinance",
    cmcId: "11387",
    category: "Dexes",
    chains: ["Solana"],
    oracles: [],
    forkedFrom: [],
    module: "cropper.js",
    twitter: "CropperFinance",
    audit_links: [
      "https://github.com/HalbornSecurity/PublicReports/blob/master/Solana%20Program%20Audit/Cropper_Finance_Farm_Solana_Program_Security_Audit_Report_Halborn_Final.pdf",
      "https://github.com/HalbornSecurity/PublicReports/blob/master/Solana%20Program%20Audit/Cropper_Finance_AMM_Program_Security_Audit_Report_Halborn_Final.pdf",
    ],
    listedAt: 1644868660,
  },
  {
    id: "1411",
    name: "Manarium",
    address: "bsc:0xc80a0a55caf6a7bfb4ee22f9380c4077312c4a35",
    symbol: "ARI",
    url: "https://www.manarium.com",
    description: "Manarium is a unique blockchain gaming platform with play to earn games.",
    chain: "Binance",
    logo: `${baseIconsUrl}/manarium.png`,
    audits: "2",
    audit_note: null,
    gecko_id: "manarium",
    cmcId: "16474",
    category: "Gaming",
    chains: ["Binance"],
    oracles: [],
    forkedFrom: [],
    module: "manarium/index.js",
    twitter: "manarium_gg",
    audit_links: ["https://github.com/solidproof/smart-contract-audits/blob/main/SmartContract_Audit_Solidproof_Manarium.pdf"],
    listedAt: 1644868847,
  },
] as Protocol[]