import { baseIconsUrl } from "../constants";
import type { Protocol } from "./types";
/*
{
  id: string;
  name: string;
  address: string;
  symbol: string;
  url: string;
  description: string;
  chain: string;
  logo: null | string;
  audits: null | "0" | "1" | "2" | "3";
  gecko_id: string;
  cmcId: string;
  category: string;
  chains: string[];
  oracles: string[];
  forkedFrom: string[];
  module: string;
  twitter: string;
  language?: string;
  treasury?: string;
  tokensExcludedFromParent: {
      Avalanche: ["GPC"],    // ADD ALL TIME WITH BIG LETTER, NOT SMALL LETTER
    },
  excludeTvlFromParent?: boolean;
},
*/
/* Audits: Please follow this legend
0 -> No audits
1 -> Part of this protocol may be unaudited
2 -> Yes
3 -> This protocol is a fork of an existing audited protocol
*/
/*
`chain` is the first chain of a protocol we tracked at defillama,
  so if a protocol launches on Ethereum and we start tracking it there, and then it launches on polygon and
  we start tracking it on both polygon and ethereum, then `chain` should be set to `Ethereum`.
`chains` is not used by the current code, but good to fill it out because it is used in our test to detect errors
*/
const data6: Protocol[] = [
  {
    id: "7709",
    name: "MOKEE",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://www.mokee.app/
    description:
      "MOKEE Protocol is the first non-custodial crypto fail-safe protocol. Users deposit native tokens into personal vaults, designate heirs, and set an inactivity threshold",
    chain: "Binance",
    logo: `${baseIconsUrl}/mokee.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Token Locker",
    chains: ["Binance", "Base","Ethereum", "Polygon", "Arbitrum", "Optimism"],
    module: "mokee/index.js",
    twitter: "MokeeApp",
    audit_links: [],
    listedAt: 1776463251
  },
  {
    id: "7710",
    name: "Trinity Protocol",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://graceful-begonia-2b7634.netlify.app/.
    description:
      "Gold-collateralized USDC lending market on Morpho Blue (Arbitrum One)",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/trinity-protocol.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Arbitrum"],
    module: "trinity-protocol/index.js",
    twitter: "cameron_arc_ai",
    audit_links: [],
    listedAt: 1776465699
  },
  {
    id: "7711",
    name: "Liquid Protocol",
    address: null,
    symbol: "-",
    url: "https://app.liquidprotocol.org/tokens",
    description:
      "Liquid Protocol deploys ERC-20 tokens on Base with Uniswap V4 pools, locked liquidity, and configurable fee distribution",
    chain: "Base",
    logo: `${baseIconsUrl}/liquid-protocol.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "LIQUIDPROTOCOL",
    github: ["Liquid-Protocol-Ops"],
    dimensions: {
      fees: "liquid-protocol",
    },
  },
  {
    id: "7712",
    name: "Rainbow Token Launchpad",
    address: null,
    symbol: "-",
    url: "https://rainbow.me/",
    description:
      "A launchpad platform built by Rainbow team",
    chain: "Base",
    logo: `${baseIconsUrl}/rainbow-token-launchpad.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "rainbowdotme",
    parentProtocol: "parent#rainbow",
    dimensions: {
      fees: "rainbow-token-launchpad",
    },
  },
  {
    id: "7713",
    name: "GrelfSwap",
    address: "hedera:0.0.1159074",
    symbol: "GRELF",
    url: "https://grelfswap.com",
    description: "GrelfSwap is a DEX aggregator on Hedera",
    chain: "Hedera",
    logo: `${baseIconsUrl}/grelfswap.jpg`,
    audits: "0",
    gecko_id: "grelf",
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Hedera"],
    module: "dummy.js",
    twitter: "GRELF_",
    dimensions: {
      aggregators: "grelfswap",
      fees: "grelfswap",
    },
  },
  {
    id: "7714",
    name: "Circle CCTP",
    address: null,
    symbol: "-",
    url: "https://www.circle.com/cross-chain-transfer-protocol",
    description: "Circle helps businesses and developers harness the power of USDC for payments and commerce",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/circle-cctp.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Ethereum", "Base", "Polygon", "Optimism", "Arbitrum", "Avalanche", "Monad", "Unichain", "Linea", "Plume Mainnet", "Sonic", "World Chain", "XDC", "Hyperliquid L1", "Ink"],
    module: "dummy.js",
    twitter: "circle",
    stablecoins: ["usd-coin"],
    parentProtocol: "parent#circle",
    dimensions: {
      fees: "cctp"
    }
  },
  {
    id: "7715",
    name: "Paxos Stablecoin Issuer",
    address: null,
    symbol: "-",
    url: "https://paxos.com/",
    description:
      "Paxos is a financial technology company that provides stablecoin services to businesses and developers",
    chain: "Off Chain",
    logo: `${baseIconsUrl}/paxos-stablecoin-issuer.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Stablecoin Issuer",
    chains: ["Off Chain"],
    module: "dummy.js",
    twitter: "Paxos",
    parentProtocol: "parent#paxos",
    dimensions: {
      fees: "paxos"
    }
  },
  {
    id: "7716",
    name: "Lucky38",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://randomy.fun/
    description:
      "On-chain games for Openclaw on Base",
    chain: "Base",
    logo: `${baseIconsUrl}/lucky38.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Luck Games",
    chains: ["Base"],
    module: "lucky38/index.js",
    twitter: null,
    listedAt: 1776628155
  },
  {
    id: "7717",
    name: "ENNI",
    address: "0xE364450b3F702d12b02F0290E0392f02DE53b8E2",
    symbol: "ENNI",
    url: " ", // pending to add url https://enni.ch
    description:
      "Immutable CDP protocol on Ethereum. Borrow stablecoins against WETH at 0% interest. No governance. No admin keys",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/enni.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Ethereum"],
    module: "enni/index.js",
    oraclesBreakdown: [ 
      { name: "Chainlink", type: "Primary", proof: ["https://enni.ch/docs/security/oracles"] },
      { name: "RedStone", type: "Fallback", proof: ["https://enni.ch/docs/security/oracles"] } 
    ],
    twitter: "Enni_Index",
    audit_links: ["https://enni.ch/Hashlock-Audit.pdf", "https://enni.ch/Blockbite-Audit.pdf"],
    github: ["enni-ch"],
    listedAt: 1776628713,
  },
  {
    id: "7718",
    name: "SuiDex",
    address: null,
    symbol: "-",
    url: "https://dex.suidex.org/",
    description:
      "SuiDex is a Uniswap V2-style AMM DEX on Sui with 54 active trading pairs, yield farming (SuiFarm), and a VICTORY token locker",
    chain: "Sui",
    logo: `${baseIconsUrl}/suidex.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Sui"],
    module: "suidex/index.js",
    twitter: "suidexHQ",
    audit_links: ["https://suidex.gitbook.io/suidex/information/audits"],
    listedAt: 1776658891,
  },
  {
    id: "7719",
    name: "Durianfun",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://durianfun.xyz/
    description:
      "Fair-launch meme-token launchpad on KUB. Tokens start on an exponential bonding curve, then graduate to a sealed DurianAMM liquidity pool. No presale, no team allocation, 14.3% of trading fees shared back to creators",
    chain: "Bitkub",
    logo: `${baseIconsUrl}/durianfun.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Bitkub"],
    module: "durianfun/index.js",
    twitter: "duriandotfun",
    audit_links: ["https://durianandfun.gitbook.io/durianfun/overall-audits"],
    github: ["Duriandotfun"],
    listedAt: 1776659179,
  },
  {
    id: "7720",
    name: "Milk Finance",
    address: null,
    symbol: "-",
    url: "https://app.basedmilk.com",
    description:
      "Milk Finance is a USDC-backed stablecoin lending protocol on Base",
    chain: "Base",
    logo: `${baseIconsUrl}/milk-finance.jpg`,
    audits: "3",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Base"],
    module: "milk-finance/index.js",
    twitter: "gotBasedMilk",
    listedAt: 1776659651,
  },
  {
    id: "7721",
    name: "SoulBound Finance",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://soulbound.finance
    description:
      "SoulBound Finance is a privacy-focused transfer protocol on Arbitrum that enables encrypted, wallet-to-wallet payments using one-time redeemable codes. It supports assets like ETH and stablecoins, with batched redemptions and a design that prevents linking senders to recipients",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/soulbound-finance.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    chains: ["Arbitrum"],
    module: "soulbound-finance/index.js",
    twitter: "SoulboundSec",
    github: ["SoulboundSecurity"],
    listedAt: 1776740719,
  },
  {
    id: "7722",
    name: "Pyron",
    address: null,
    symbol: "-",
    url: "https://pyron.fi/",
    description:
      "Asset productivity layer of Fogo. Lend and Borrow without the wait, noise, or limits",
    chain: "Fogo",
    logo: `${baseIconsUrl}/pyron.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Fogo"],
    module: "pyron/index.js",
    twitter: "Pyronfi",
    github: ["pyron-finance"],
    audit_links: ["https://github.com/zenith-security/reports/blob/main/reports/Pyron%20Lendr%20-%20Zenith%20Audit%20Report.pdf"],
    listedAt: 1776741147,
  },
  {
    id: "7723",
    name: "PMI Protocol",
    address: "polygon:0x9DD6641423200b1FBd0BFF45f376BEE66Be1F4E4",
    symbol: "PMI",
    url: " ", // pending to add url https://pmiprotocol.xyz
    description:
      "On-chain index fund for prediction market infrastructure tokens. Deposit USDC, receive PMI shares at NAV. Vault holds UMA, WMATIC, and GNO via Uniswap V3",
    chain: "Polygon",
    logo: `${baseIconsUrl}/pmi-protocol.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    chains: ["Polygon"],
    module: "pmi-protocol/index.js",
    twitter: "predictionidx",
    github: ["ninjacornix"],
    listedAt: 1776741431,
  },
  {
    id: "7724",
    name: "Vaultfire",
    address: null,
    symbol: "-",
    url: " ", // pending to add url project didn't submit url
    description:
      "Vaultfire is an AI agent trust infrastructure protocol",
    chain: "Base",
    logo: `${baseIconsUrl}/vaultfire.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "AI Agents",
    chains: ["Base", "Avalanche", "Arbitrum", "Polygon"],
    module: "vaultfire/index.js",
    twitter: null,
    listedAt: 1776741959,
  },
  {
    id: "7725",
    name: "TopStrike",
    address: null,
    symbol: "-",
    url: "https://topstrike.io",
    description:
      "Real-time, one-tap Football trading game powered by MegaETH",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/topstrike.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gaming",
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "TopStrikeIO",
    dimensions: {
      dexs: "topstrike",
      fees: "topstrike",
    },
  },
  {
    id: "7726",
    name: "ASPE Labs",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://aspelabs.xyz
    description:
      "Automated yield vault on HyperEVM. ERC4626-compliant; deposits USDC, trades on HyperCore via an agent wallet, and returns profits through share price appreciation",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/aspe-labs.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Hyperliquid L1"],
    module: "aspe-labs/index.js",
    twitter: "AspeLabs",
    github: ["aspe-labs"],
    listedAt: 1776742731,
  },
  {
    id: "7727",
    name: "Hubra",
    address: null,
    symbol: "-",
    url: "https://hubra.app/",
    description:
      "Hubra is a Solana-based DeFi protocol providing institutional-grade, non-custodial yield products, including liquid staking (raSOL) and automated yield vaults (raUSDC, raUSDT, raUSDS, raUSDG, raUSD1). It is designed to make professional yield strategies accessible to everyone",
    chain: "Solana",
    logo: `${baseIconsUrl}/hubra.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Solana"],
    module: "hubra/index.js",
    twitter: "HubraApp",
    github: ["Hubra-labs"],
    listedAt: 1776742981,
  },
  {
    id: "7728",
    name: "Apiary",
    address: "berachain:0x5e4d5f1E7b69Cdcd3faDb0cf182ea7821070Cbb5",
    symbol: "APIARY",
    url: "https://www.apiary.fi/",
    description:
      "Treasury-backed protocol designed to perpetually accumulate $BGT (Berachain Governance Token) through Berachain's Proof of Liquidity (PoL)",
    chain: "Berachain",
    logo: `${baseIconsUrl}/apiary.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Reserve Currency",
    chains: ["Berachain"],
    module: "apiary/index.js",
    twitter: "ApiaryFi",
    listedAt: 1776798425,
  },
  {
    id: "7729",
    name: "Dumpfun Gamified Launcher",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dumpfun.io
    description:
      "Dumpfun Gamified Launcher is a gamified token launchpad on Solana. Anyone can launch a mining token; users deploy SOL to a 5x5 grid per round, and VRF-picked winning squares split a SOL + token reward pool. Per reset: 87% winners, 1% creator, 10% buy-and-burn, 0.5% platform fee, 1.4% per-token motherlode, 0.1% global motherlode",
    chain: "Solana",
    logo: `${baseIconsUrl}/dumpfun-gamified-launcher.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Gamified Mining",
    chains: ["Solana"],
    module: "dumpfun-gamified-launcher/index.js",
    twitter: "dumpfundotio",
    audit_links: ["https://skynet.certik.com/projects/dumpfun"],
    treasury: "dumpfun-gamified-launcher.js",
    listedAt: 1776798678,
  },
  {
    id: "7730",
    name: "TxFlow Bridge",
    address: null,
    symbol: "-",
    url: "https://txflow.com/",
    description:
      "TxFlow is an open Layer 1 with multi-application ecosystem around TIP Liquidity Standards — where every Channel shares on-chain liquidity, settlement, and market data without bridging",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/txflow-bridge.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Arbitrum"],
    module: "txflow/index.js",
    twitter: "TxFlow_L1",
    parentProtocol: "parent#txflow",
    listedAt: 1776799092,
  },
  {
    id: "7731",
    name: "Sail.Money",
    address: null,
    symbol: "-",
    url: "https://sail.money/",
    description:
      "Sail is a non-custodial personal AI agent that manages stablecoins across DeFi protocols and networks, automatically reallocating capital to optimize risk-adjusted yield while helping protect capital with continuous risk monitoring and user-controlled permissions",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/sail.money.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum", "Base", "Arbitrum"],
    module: "sail/index.js",
    twitter: "SaildotMoney",
    listedAt: 1776799163,
  },
  {
    id: "7732",
    name: "Hit One",
    address: null,
    symbol: "-",
    url: "https://app.hit.one/r/5YPD66",
    referralUrl: "https://app.hit.one/r/5YPD66",
    description:
      "Hit One is a perpetual futures trading platform on MegaETH. Trades are aggregated off-chain at the venue layer (similar to Hyperliquid's model), so per-trade data is served from a public stats endpoint rather than indexed from on-chain events",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/hit-one.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "hitdotone",
    dimensions: {
      derivatives: "hitone",
      fees: "hitone",
    },
  },
  {
    id: "7733",
    name: "TxFlow Perps",
    address: null,
    symbol: "-",
    url: "https://app.txflow.com/",
    description:
      "TxFlow perpetuals are derivative products with no expiration date. They maintain price convergence with the underlying spot asset through funding payments rather than settlement dates",
    chain: "TxFlow",
    logo: `${baseIconsUrl}/txflow-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["TxFlow"],
    module: "dummy.js",
    twitter: "TxFlow_L1",
    parentProtocol: "parent#txflow",
    dimensions: {
      derivatives: "txflow-perps",
      fees: "txflow-perps",
      "open-interest": "txflow-perps-oi",
    },
  },
  {
    id: "7734",
    name: "Ledgity Yield",
    address: "0x482dF7483a52496F4C65AB499966dfcdf4DDFDbc",
    symbol: "LDY",
    url: "https://ledgity.finance/",
    description:
      "Real-world yield protocol offering USDC and EURC vaults backed by institutional fixed-income strategies",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ledgity-yield.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum", "Sonic", "Arbitrum", "Base"],
    module: "ledgity/index.js",
    twitter: "LedgityYield",
    github: ["LedgityLabs"],
    listedAt: 1776808973,
  },
  {
    id: "7735",
    name: "Premarket",
    address: null,
    symbol: "-",
    url: "https://premarket.xyz/",
    description:
      "Premarket is a prediction-market style protocol for trading premarket/outcome exposure",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/premarket.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Prediction Market",
    chains: ["MegaETH"],
    module: "premarket/index.js",
    twitter: "premarket_xyz",
    listedAt: 1776809132,
  },
  {
    id: "7736",
    name: "Chisino",
    address: null,
    symbol: "-",
    url: " ", // pending to add url chisino.io
    description:
      "Chisino is an instant payout game protocol on MegaETH. Its pioneer game is no-loss scratch cards. Scratch for instant prizes up to $10,000. 55% of cards pay out across 16 prize tiers. Every card you play, win or lose, generates a recovery ticket that works to return what you spent. No permanent loss. The protocol is built on Klarhaus, a prize-linked savings engine that splits each play between instant prizes, entry recovery, and protocol rewards. Deposits are backed 1:1 by stablecoins. All outcomes are determined by onchain VRF. Earn rewards every time you play",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/chisino.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Luck Games",
    chains: ["MegaETH"],
    module: "chisino/index.js",
    twitter: "trychisino",
    listedAt: 1776809625,
  },
  {
    id: "7737",
    name: "RISE Bridge",
    address: null,
    symbol: "-",
    url: "https://risechain.com/",
    description:
      "RISE is an Ethereum Layer 2 blockchain delivering near-instant transactions at unprecedented scale with sub-3ms latency and 100,000+ TPS capacity, all secured by Ethereum",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/rise-bridge.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Ethereum"],
    module: "rise/index.js",
    twitter: "risechain",
    listedAt: 1776809759,
  },
  {
    id: "7738",
    name: "DumpFlow",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dumpfun.io
    description:
      "DumpFlow is Dumpfun's bonding-curve token launchpad on Solana. Anyone can mint a meme token with a configurable virtual SOL reserve, sell-lock period, and dynamic ramping limits. Buys/sells route SOL through a per-token liquidity pool; a 1% SOL fee accrues to the platform fee wallet and sell-side fees split 2.5%/2.5% to creator/company",
    chain: "Solana",
    logo: `${baseIconsUrl}/dumpflow.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "dumpflow/index.js",
    twitter: "dumpfundotio",
    audit_links: ["https://skynet.certik.com/projects/dumpfun"],
    listedAt: 1776810088,
  },
  // { // ownership was transffered to Uniswap: https://github.com/DefiLlama/DefiLlama-Adapters/pull/18866
  //   id: "7739",
  //   name: "Oku Trade",
  //   address: null,
  //   symbol: "-",
  //   url: "https://oku.trade/",
  //   description: "Oku Trade is a premium DEX interface offering advanced trading, deep liquidity, and superior analytics on the chain",
  //   chain: "0G",
  //   logo: `${baseIconsUrl}/oku-trade.jpg`,
  //   audits: "0",
  //   gecko_id: null,
  //   cmcId: null,
  //   tags: ["CLMM"],
  //   chains: ["0G"],
  //   module: "oku-trade/index.js",
  //   twitter: "okutrade",
  //   listedAt: 1776810414,
  // },
  {
    id: "7740",
    name: "Arche",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://arche.money
    description: "Yield-bearing stablecoin vault aggregating best-in-class DeFi yields",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/arche.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    module: "arche-money/index.js",
    twitter: "yieldarche",
    listedAt: 1776810661,
  },
  {
    id: "7741",
    name: "RamsesX Polygon CL",
    address: "polygon:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a concentrated liquidity layer and exchange on Polygon, powered by x(3,3).",
    chain: "Polygon",
    logo: `${baseIconsUrl}/ramsesx-polygon-cl.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Polygon"],
    module: "ramsesx-poly-cl/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    audit_links: ["https://docs.ramses.xyz/pages/audits"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881424,
    dimensions: {
      fees: "ramsesx-poly-cl",
      dexs: "ramsesx-poly-cl",
    },
  },
  {
    id: "7742",
    name: "RamsesX Polygon Legacy",
    address: "polygon:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a ve(3,3) exchange on Polygon with legacy liquidity pools and x(3,3) governance.",
    chain: "Polygon",
    logo: `${baseIconsUrl}/ramsesx-polygon-legacy.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["ve(3,3)"],
    chains: ["Polygon"],
    module: "ramsesx-poly-legacy/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881440,
    dimensions: {
      fees: "ramsesx-poly-legacy",
      dexs: "ramsesx-poly-legacy",
    },
  },
  {
    id: "7743",
    name: "RamsesX Arbitrum CL",
    address: "arbitrum:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a concentrated liquidity layer and exchange on Arbitrum, powered by x(3,3).",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/ramsesx-arbitrum-cl.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Arbitrum"],
    module: "ramsesx-arb-cl/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    audit_links: ["https://docs.ramses.xyz/pages/audits"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881448,
    dimensions: {
      fees: "ramsesx-arb-cl",
      dexs: "ramsesx-arb-cl",
    },
  },
  {
    id: "7744",
    name: "RamsesX Arbitrum Legacy",
    address: "arbitrum:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a ve(3,3) exchange on Arbitrum with legacy liquidity pools and x(3,3) governance.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/ramsesx-arbitrum-legacy.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["ve(3,3)"],
    chains: ["Arbitrum"],
    module: "ramsesx-arb-legacy/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881454,
    dimensions: {
      fees: "ramsesx-arb-legacy",
      dexs: "ramsesx-arb-legacy",
    },
  },
  {
    id: "7745",
    name: "YFarmer",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://yfarmer.xyz
    description:
      "YFarmer is a DeFi yield vault and risk curation protocol where users deposit USDC to access actively managed strategies.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/yfarmer.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Ethereum"],
    module: "yfarmer/index.js",
    twitter: null,
    listedAt: 1776882319,
  },
  {
    id: "7746",
    name: "Altera Finance",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://altera.finance
    description:
      "Altera Vaults deploy capital into market-neutral, hedged, and structured-credit strategies operated by licensed fund managers.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/altera-finance.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Ethereum"],
    module: "altera-finance/index.js",
    twitter: null,
    listedAt: 1776882684,
  },
  {
    id: "7747",
    name: "Streamlock",
    address: "solana:FNhcY1cwQvQqaM8CUjXSuoGKJniwC4maBRLqNRLipump",
    symbol: "LOCK",
    url: "https://www.streamlock.fun/",
    description:
      "Solana token launchpad with price-gated locks. Users buy launched memecoins via a bonding-curve AMM; purchases sit locked in on-chain escrows until each token hits its configured price milestones. Idle SOL reserves are staked as JitoSOL for yield that accrues to the protocol.",
    chain: "Solana",
    logo: `${baseIconsUrl}/streamlock.jpg`,
    audits: "0",
    gecko_id: "streamlock",
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "streamlock/index.js",
    twitter: "0xHao_",
    github: ["0xNike"],
    listedAt: 1776963621,
  },
  {
    id: "7748",
    name: "SpringX",
    address: null,
    symbol: "-",
    url: "https://springx.finance/",
    description:
      "SpringX is the gateway to the Plasma DeFi ecosystem facilitating yield generation through efficient auto-liquidity management.",
    chain: "Plasma",
    logo: `${baseIconsUrl}/springx.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Plasma"],
    module: "springx/index.js",
    twitter: "SpringX_Finance",
    audit_links: ["https://github.com/shieldify-security/audits-portfolio/blob/main/reports/SpringX-Security-Review.pdf"],
    listedAt: 1776964034,
  },
  {
    id: "7749",
    name: "Alchemix V3",
    address: "0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF",
    symbol: "ALCX",
    url: "https://alchemix.fi/",
    description:
      "Alchemix is a DeFi protocol that allows for the creation of synthetic tokens that represent the future yield of a deposit. It enables users to retrieve near instant tokenized value against temporary* deposits of stablecoins.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/alchemix-v3.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Synthetics",
    chains: ["Ethereum", "Arbitrum", "Optimism"],
    module: "alchemix-v3/index.js",
    twitter: "AlchemixFi",
    audit_links: ["https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/Alchemix_v3.pdf"],
    parentProtocol: "parent#alchemix",
    listedAt: 1776975864,
  },
  {
    id: "7750",
    name: "Flying Tulip Lend",
    address: "0x5DD1A7A369e8273371d2DBf9d83356057088082c",
    symbol: "FT",
    url: "https://flyingtulip.com/lend/",
    description: "Flying Tulip Lend is a custom lending market on Sonic.",
    chain: "Sonic",
    logo: `${baseIconsUrl}/flying-tulip-lend.jpg`,
    audits: "2",
    gecko_id: "flying-tulip",
    cmcId: null,
    category: "Lending",
    chains: ["Sonic"],
    module: "dummy.js",
    audit_links: ["https://docs.flyingtulip.com/risks/"],
    twitter: "flyingtulip_",
    listedAt: 1769459609,
    parentProtocol: "parent#flying-tulip",
    dimensions: {
      fees: "flying-tulip-lend"
    }
  },
  {
    id: "7751",
    name: "eva Markets",
    address: null,
    symbol: "-",
    url: "https://www.eva.markets",
    description: "eva Markets allows users to mint portable tokens backed by isolated credit.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/eva-markets.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Private Credit"],
    chains: ["Ethereum"],
    module: "eva/index.js",
    audit_links: ["https://docs.flyingtulip.com/risks/"],
    twitter: "eva_markets",
    listedAt: 1777136758,
    dimensions: {
      fees: "eva"
    }
  },
  {
    id: "7752",
    name: "FrenFlow",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://frenflow.com
    description: "FrenFlow is the social + execution layer for prediction markets. A unified trading UI and Telegram bot with self-custody routing across Polymarket, Kalshi (via DFlow), and Predict.fun — plus native copytrading, social feed, and leaderboards.",
    chain: "Polygon",
    logo: `${baseIconsUrl}/frenflow.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Prediction Market",
    chains: ["Polygon"],
    module: "dummy.js",
    twitter: "frenflow",
    github: ["frenflow"],
    dimensions: {
      fees: "frenflow",
      dexs: "frenflow",
    }
  },
  {
    id: "7753",
    name: "Telegram Wallet",
    address: null,
    symbol: "-",
    url: "https://t.me/wallet",
    description: "Buy, sell and transfer crypto with zero fees on Telegram.",
    chain: "zkLighter",
    logo: `${baseIconsUrl}/telegram-wallet.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["zkLighter"],
    module: "dummy.js",
    twitter: "wallet_tg",
    dimensions: {
      fees: "telegram-wallet-perps",
    }
  },
  {
    id: "7754",
    name: "HypePool",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://hypepool.app
    description: "The first on-chain game protocol on HyperEVM. Multiple ways to play, with verifiable randomness via Chainlink VRF v2.5 routed through Base via CCIP.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/hypepool.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gaming",
    chains: ["Hyperliquid L1"],
    module: "hypepool/index.js",
    twitter: "HypePoolX",
    listedAt: 1777230068,
  },
  {
    id: "7755",
    name: "Kyan Blue Perps",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.kyan.blue/perps
    description: "Kyan Blue Perps is Kyan's perpetuals market.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/kyan-blue-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Arbitrum"],
    module: "kyan-blue/index.js",
    twitter: "KyanExchange",
    parentProtocol: "parent#premia",
    dimensions: {
      derivatives: "kyan",
      fees: "kyan",
      "active-users": "kyan",
    },
  },
  {
    id: "7756",
    name: "Kyan Blue Options",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.kyan.blue/
    description: "Kyan Blue Options is Kyan's options market.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/kyan-blue-options.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Options",
    chains: ["Arbitrum"],
    module: "dummy.js",
    twitter: "KyanExchange",
    parentProtocol: "parent#premia",
    dimensions: {
      options: "kyan",
    },
  },
  {
    id: "7757",
    name: "WeDeFin",
    address: null,
    symbol: "-",
    url: "https://app.wedefin.com/",
    description: "WeDeFin is a non-custodial index and portfolio app that lets users follow community-ranked crypto strategies, rebalance through DEXs, and route supported assets into Aave for yield.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/wedefin.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    chains: ["Ethereum", "Base", "Arbitrum"],
    module: "wedefin/index.js",
    twitter: "wedefin",
    audit_links: ["https://docs.wedefin.com/technical-overview/audits"],
    listedAt: 1777310614,
    dimensions: {
      fees: "wedefin",
    }
  },
  {
    id: "7758",
    name: "LayerZero V1",
    address: "ethereum:0x6985884c4392d348587b19cb9eaaf157f13271cd",
    symbol: "ZRO",
    url: "https://layerzero.network/",
    description:
      "LayerZero is a technology that enables applications to move data across blockchains, uniquely supporting censorship-resistant messages and permissionless development through immutable smart contracts.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/layerzero-v1.jpg`,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Ethereum", "Binance", "Polygon", "Arbitrum", "Optimism", "Base", "Avalanche", "Harmony", "Fantom", "Linea", "Tron", "Scroll", "Mantle", "Blast", "Mode", "Aurora", "Celo", "Story", "Ink", 
      "Polygon zkEVM", "Sonic", "Berachain", "Unichain", "Movement", "Abstract", "MegaETH", "Sophon", "Morph", "Plasma", "Flare", "Monad"],
    module: "dummy.js",
    twitter: "LayerZero_Core",
    parentProtocol: "parent#layerzero",
    dimensions: {
      fees: "layerzerov1",
    }
  },
  {
    id: "7759",
    name: "Flying Tulip ftUSD",
    address: null,
    symbol: "-",
    url: "https://flyingtulip.com/",
    description: "ftUSD is a yield-bearing stablecoin backed by USDC, USDT and ftUSD-wrapped collateral deployed via MintAndRedeem into Aave yield strategies. Holders can stake into sftUSD to earn FT rewards funded by protocol fees that buy FT on the open market.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/flying-tulip-ftusd.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Ethereum", "Sonic"],
    module: "dummy.js",
    audit_links: ["https://docs.flyingtulip.com/risks/"],
    twitter: "flyingtulip_",
    listedAt: 1777298400,
    parentProtocol: "parent#flying-tulip",
    dimensions: {
      fees: "flying-tulip-ftusd"
    }
  },
  {
    id: "7760",
    name: "Veax Perps",
    address: null,
    symbol: "VEAX",
    url: "https://veax.com/",
    description:
      "Veax is an advanced DEX and PerpDEX built on Near Protocol and Orderly . Bringing together the best features of TradFi and DeFi for an unparalleled swap and trading experience.",
    chain: "Orderly",
    logo: `${baseIconsUrl}/veax-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Orderly Builder"],
    chains: ["Orderly"],
    module: "dummy.js",
    twitter: "veaxlabs",
    parentProtocol: "parent#veax",
    dimensions: {
      fees: "veax-perps",
      derivatives: "veax-perps"
    }
  },
  {
    id: "7761",
    name: "Bullet Perps",
    address: null,
    symbol: "-",
    url: "https://bullet.xyz/",
    description:
      "High-performance ZK rollup perpetuals and spot DEX settling on Solana.",
    chain: "Solana",
    logo: `${baseIconsUrl}/bullet-perps.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "Bulletxyz",
    audit_links: ["https://docs.bullet.xyz/bullet-network/audits"],
    oraclesBreakdown: [{name: "Pyth", type: "Primary", proof: ["https://docs.bullet.xyz/bullet-network/architecture/oracle"]}],
    parentProtocol: "parent#bullet",
    dimensions: {
      derivatives: "bullet-perp",
      "open-interest": "bullet"
    }
  },
  {
    id: "7762",
    name: "ShapeSwap V2",
    address: null,
    symbol: "-",
    url: "https://shapeswap.xyz/",
    description:
      "Concentrated-liquidity DEX on Shape chain. Uniswap V3 fork with a companion V2/AMM deployment.",
    chain: "Shape",
    logo: `${baseIconsUrl}/shapeswap-v2.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Shape"],
    forkedFromIds: ["2197"],
    module: "shapeswap-v2/index.js",
    twitter: "shape",
    parentProtocol: "parent#shapeswap",
    listedAt: 1777404083,
    dimensions: {
      dexs: "shapeswap-v2",
      fees: "shapeswap-v2",
    }
  },
  {
    id: "7763",
    name: "ShapeSwap V3",
    address: null,
    symbol: "-",
    url: "https://shapeswap.xyz/",
    description:
      "Concentrated-liquidity DEX on Shape chain. Uniswap V3 fork with a companion V2/AMM deployment.",
    chain: "Shape",
    logo: `${baseIconsUrl}/shapeswap-v3.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Shape"],
    forkedFromIds: ["2198"],
    module: "shapeswap-v3/index.js",
    twitter: "shape",
    parentProtocol: "parent#shapeswap",
    listedAt: 1777404089,
    dimensions: {
      dexs: "shapeswap-v3",
      fees: "shapeswap-v3",
    }
  },
  {
    id: "7764",
    name: "RSwap",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dex.reddicks.meme
    description:
      "RSwap is a meme-driven DEX built for the DCKS ecosystem. Designed as the core trading layer of DCKS, RSwap combines efficient pricing with high-energy community participation, making it both a functional DEX and a growth engine for the ecosystem.",
    chain: "Radix",
    logo: `${baseIconsUrl}/rswap.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Radix"],
    module: "rswap/index.js",
    twitter: "REDDICKS_XRD",
    audit_links: ["https://github.com/pessimistic-io/audits/blob/b886ee548241bc8066843ab110287058ff33ba4f/DefiPlaza%20Radix%20Security%20Analysis%20by%20Pessimistic.pdf"],
    listedAt: 1777404095,
  },
  {
    id: "7765",
    name: "Spreads Finance Leverage",
    address: null,
    symbol: "-",
    url: "https://spreads.fi/",
    description:
      "Spreads Finance has a suite of DeFi products starting with a yield and points vault for users to passively earn yield via market neutral derivative strategies or points from tokenless DeFi markets, all via a vault.",
    chain: "Ink",
    logo: `${baseIconsUrl}/spreads-finance-leverage.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Ink"],
    module: "spreads-strc-leverage/index.js",
    twitter: "spreads_fi",
    parentProtocol: "parent#spreads-finance",
    listedAt: 1777478521
  },
  {
    id: "7766",
    name: "R25",
    address: null,
    symbol: "-",
    url: "https://www.r25.xyz/",
    description:
      "R25 is an RWA stablecoin protocol that issues rcUSD against tokenized money market funds and stablecoins",
    chain: "Pharos",
    logo: `${baseIconsUrl}/r25.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Money Market Funds"],
    chains: ["Pharos"],
    module: "r25/index.js",
    twitter: "R25Official",
    listedAt: 1777489095
  },
  {
    id: "7767",
    name: "x402",
    address: null,
    symbol: "-",
    url: "https://www.x402.org/",
    description:
      "x402 is an open payments standard that lets services charge for API and content access directly over HTTP, with payments settled through crypto-native rails",
    chain: "Base",
    logo: `${baseIconsUrl}/x402.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    chains: ["Base","Arbitrum","Optimism","Polygon","Celo", "Hyperliquid L1","Binance","Avalanche","Abstract"],
    module: "dummy.js",
    twitter: null,
    dimensions: {
      dexs: "x402",
    }
  },
  {
    id: "7768",
    name: "Terminal",
    address: "solana:pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn",
    symbol: "PUMP",
    url: "https://terminal.pump.fun/",
    description: "Terminal is Pump.fun's advanced memecoin trading terminal",
    chain: "Solana",
    logo: `${baseIconsUrl}/terminal.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Telegram Bot",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "Pumpfun",
    parentProtocol: "parent#pump",
    dimensions: {
      fees: "trading-terminal"
    }
  },
  {
    id: "7769",
    name: "Trust Wallet Perps",
    address: "bsc:0x4b0f1812e5df2a09796481ff14017e6005508003",
    symbol: "TWT",
    url: "https://trustwallet.com/download",
    description: "Trust Wallet Perps is Trust Wallet's Perps platform",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/trust-wallet-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Hyperliquid Builder"],
    chains: ["Hyperliquid L1"],
    module: "dummy.js",
    twitter: "TrustWallet",
    parentProtocol: "parent#trust-wallet",
    dimensions: {
      fees: "trust-wallet-perps",
      derivatives: "trust-wallet-perps",
    }
  },
  {
    id: "7770",
    name: "NextRare",
    address: null,
    symbol: "-",
    url: "https://nextrare.cards/",
    description: "First perpetual TCG Gacha live on iOS and Android",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/nextrare.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Physical TCG",
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "NextRare_cards",
    dimensions: {
      fees: "nextrare",
    }
  },
  {
    id: "7771",
    name: "Pool Party",
    address: "base:0xEab49138BA2Ea6dd776220fE26b7b8E446638956",
    symbol: "SEND",
    url: "https://poolparty.fun",
    description: "First AMM on Canton Network. Built by Send Foundation. Accessible from the Send Canton Wallet. Launched February 2026",
    chain: "Canton",
    logo: `${baseIconsUrl}/pool-party.jpg`,
    audits: "0",
    gecko_id: "send-token-2",
    cmcId: "27376",
    tags: ["AMM"],
    chains: ["Canton"],
    module: "pool-party/index.js",
    twitter: "Send",
    listedAt: 1777517069
  },
  {
    id: "7772",
    name: "Phlox",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://phlox.finance
    description: "Phlox is a LUKSO-focused DeFi app with a Uniswap V3-style DEX",
    chain: "LUKSO",
    logo: `${baseIconsUrl}/phlox.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    forkedFromIds: ["2198"],
    chains: ["LUKSO"],
    module: "phlox/index.js",
    twitter: null,
    listedAt: 1777517385
  },
  {
    id: "7758",
    name: "Pool Party",
    address: null,
    symbol: "-",
    url: "https://poolparty.fun",
    description: "Pool Party is the first AMM on Canton Network, built by Send Foundation. It enables non-custodial swaps and liquidity provision in CC, CUSD (Send's privacy stablecoin), and USDCx (bridged USDC) directly from the Send Canton Wallet. Launched February 2026.",
    chain: "Canton",
    logo: `${baseIconsUrl}/pool-party.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Dexes",
    chains: ["Canton"],
    module: "pool-party/index.js",
    twitter: "Send",
    listedAt: 1777311905,
  },
];
export default data6;
