import { baseIconsUrl } from "../constants";
import type { IParentProtocol } from "./types";

/*
    leave `chains` and `category` as an empty array because we fill them based on their child protocols chains and category in api response
*/

const parentProtocols: IParentProtocol[] = [
  {
    id: "parent#aave",
    name: "AAVE",
    url: "https://aave.com\r\n",
    description:
      "Aave is an Open Source and Non-Custodial protocol to earn interest on deposits and borrow assets",
    logo: `${baseIconsUrl}/aave-v2.png`,
    chains: [],
    gecko_id: "aave",
    cmcId: "7278",
    twitter: "AaveAave",
    governanceID: ["snapshot:aave.eth"],
  },
  {
    id: "parent#sushi",
    name: "Sushi",
    url: "https://sushi.com/",
    description:
      "A fully decentralized protocol for automated liquidity provision on Ethereum.\r\n",
    logo: `${baseIconsUrl}/sushi.jpg`,
    gecko_id: "sushi",
    cmcId: "6758",
    chains: [],
    twitter: "SushiSwap",
    governanceID: ["snapshot:sushigov.eth"]
  },
  {
    id: "parent#sun",
    name: "SUN",
    url: "https://sun.io",
    description:
      "First integrated platform for stablecoin swap, stake-mining, and self-governance on TRON",
    logo: `${baseIconsUrl}/sun.jpg`,
    gecko_id: "sun-token",
    cmcId: "10529",
    chains: [],
    twitter: "defi_sunio",
  },
  {
    id: "parent#benqi",
    name: "Benqi",
    url: "https://benqi.fi",
    description:
      "BENQI is a non-custodial liquidity market protocol, built on Avalanche. The protocol enables users to effortlessly lend, borrow, and earn interest with their digital assets.",
    logo: `${baseIconsUrl}/benqi-lending.jpg`,
    gecko_id: "benqi",
    cmcId: "9288",
    chains: [],
    twitter: "BenqiFinance",
  },
  {
    id: "parent#increment-finance",
    name: "Increment Finance",
    url: "https://increment.fi",
    description:
      "Increment Finance, One-stop DeFi Platform on Flow Blockchain.",
    logo: `${baseIconsUrl}/increment-lending.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "incrementfi",
  },
  {
    id: "parent#pods-finance",
    name: "Pods",
    url: "https://www.pods.finance/",
    description:
      "Buliding DeFi, Strategies, primitives and tooling. Welcome to Pods.",
    logo: `${baseIconsUrl}/pods-finance.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "PodsFinance",
    governanceID: ["snapshot:podsfinance.eth"]
  },
  {
    id: "parent#apeswap",
    name: "ApeSwap",
    url: "https://apeswap.finance",
    description:
      "ApeSwap is a Decentralized Autonomous Organization (DAO) that offers a full suite of tools to explore and engage with decentralized finance opportunities. Using the products within our DeFi Hub, users and partners can tap into this new wave of financial innovation in a secure, transparent, and globally accessible way",
    logo: `${baseIconsUrl}/apeswap.png`,
    gecko_id: "apeswap-finance",
    cmcId: "8497",
    chains: [],
    twitter: "ape_swap",
    governanceID: ["snapshot:apeswap-finance.eth"]
  },
  {
    id: "parent#parallel-deFi-super-app",
    name: "Parallel DeFi Super App",
    url: "https://parallel.fi",
    description:
    "Parallel Finance is a Decentralized Money Market Protocol that offers lending, staking, and borrowing in the Polkadot ecosystem. Depositors can lend and stake simultaneously to earn double yield on their staked coins, and borrowers can collateralize to borrow.",
    logo: `${baseIconsUrl}/parallel-defi-super-app.jpg`,
    gecko_id: "parallel-finance" ,
    cmcId: "12887",
    chains: [],
    twitter: "ParallelFi",
  },
  {
    id: "parent#value-finance",
    name: "Value Finance",
    url: "https://valuedefi.io",
    description:
    "The Value DeFi protocol is a platform and suite of products that aim to bring fairness, true value, and innovation to Decentralized Finance.`",
    logo: `${baseIconsUrl}/value finance.png`,
    gecko_id: "value-liquidity" ,
    cmcId: "1183",
    chains: [],
    twitter: "value_defi",
  },
  {
    id: "parent#magik-finance",
    name: "Magik Finance",
    url: "https://magik.finance/",
    description:
    "Yield Optimization as a Service and Algorithmic token pegged to $FTM on the Fantom Opera network.",
    logo: `${baseIconsUrl}/magik-finance.png`,
    gecko_id: "magik",
    cmcId: "17941",
    chains: [],
    twitter: "MagikDotFinance",
  },
  {
    id: "parent#huckleberry",
    name: "Huckleberry",
    url: "https://www.huckleberry.finance/",
    description:
    "Huckleberry is a community driven AMM crosschain DEX and lendin' platform built on Moonriver and CLV.",
    logo: `${baseIconsUrl}/huckleberry.png`,
    gecko_id: "huckleberry",
    cmcId: "12922",
    chains: [],
    twitter: "HuckleberryDEX",
    governanceID: ["snapshot:huckleberrydex.eth"]
  },
  {
    id: "parent#mm-finance",
    name: "MM Finance",
    url: "https://linktr.ee/madmeerkat",
    description:
    "DeFi Ecosystem on Cronos and AMM on Polygon",
    logo: `${baseIconsUrl}/mm-finance.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "MMFcrypto",
    governanceID: ["snapshot:mmfinance.eth"]
  },
  {
    id: "parent#mycelium",
    name: "Mycelium",
    url: "https://mycelium.xyz",
    description:
    "Previously Tracer DAO. Trade with liquidity, leverage and low fees.",
    logo: `${baseIconsUrl}/mycelium.jpg`,
    gecko_id: "mycelium",
    cmcId: "21437",
    chains: [],
    twitter: "mycelium_xyz",
    governanceID: ["snapshot:tracer.eth", "snapshot:myceliumgrowth.eth"]
  },
  {
    id: "parent#bancor",
    name: "Bancor",
    url: "https://app.bancor.network/",
    description:
    "Bancor is an on-chain liquidity protocol that enables automated, decentralized exchange on Ethereum and across blockchains.",
    logo: `${baseIconsUrl}/bancor.png`,
    gecko_id: "bancor",
    cmcId: "1727",
    chains: [],
    twitter: "Bancor",
    governanceID: ["snapshot:bancornetwork.eth"]
  },
  {
    id: "parent#spiritswap",
    name: "SpiritSwap",
    url: "https://app.spiritswap.finance/#/",
    description:
      "AMM and Lending protocol on Fantom",
    logo: `${baseIconsUrl}/spiritswap.jpg`,
    gecko_id: "spiritswap",
    cmcId: "1359",
    chains: [],
    twitter: "Spirit_Swap",
    governanceID: ["snapshot:spiritswap.eth"]
  },
  {
    id: "parent#interlay",
    name: "Interlay",
    url: "https://interlay.io/",
    description:
      "Fully trustless and decentralized Bitcoin bridge and BTC DeFi hub",
    logo: `${baseIconsUrl}/interlay.png`,
    gecko_id: "interlay",
    cmcId: "20366",
    chains: [],
    twitter: "InterlayHQ",
  },
  {
    id: "parent#frax-finance",
    name: "Frax Finance",
    url: "https://frax.finance/",
    description:
      "Inventors of the fractional stablecoin. $FRAX is the 1st stablecoin with parts backed & parts algorithmic",
    logo: `${baseIconsUrl}/frax finance.png`,
    gecko_id: "frax-share",
    cmcId: "6953",
    chains: [],
    twitter: "fraxfinance",
    governanceID: [
      "snapshot:frax.eth",
      "compound:ethereum:0xd74034c6109a23b6c7657144cacbbbb82bdcb00e"//FXS
    ]
  },
  {
    id: "parent#compound-finance",
    name: "Compound Finance",
    url: "https://compound.finance/",
    description:
      "Compound is an algorithmic, autonomous interest rate protocol built for developers, to unlock a universe of open financial applications.",
    logo: `${baseIconsUrl}/compound finance.jpg`,
    gecko_id: "compound-governance-token",
    cmcId: "5692",
    chains: [],
    twitter: "compoundfinance",
    governanceID: [
      "snapshot:comp-vote.eth", 
      "compound:ethereum:0xc0da02939e1441f497fd74f78ce7decb17b66529",
      "compound:ethereum:0xc0da01a04c3f3e0be433606045bb7017a7323e38",
      "compound:ethereum:0x336505ec1bcc1a020eede459f57581725d23465a",
      //"compound:ethereum:0x542ed9b1b50dc686e88404c73c062faa39568304" //GridZone.io ZONE
    ]
  },
  {
    id: "parent#algofi",
    name: "Algofi",
    url: "https://www.algofi.org/",
    description:
      "Algofi is the DeFi hub built on Algorand. Earn interest, borrow, swap and more on the Algofi lending protocol, DEX, and stablecoin. Further, access liquidity against your governance ALGOs through the Algofi Vault.",
    logo: `${baseIconsUrl}/algofi.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "algofiorg",
  },
  {
    id: "parent#redacted",
    name: "Redacted",
    url: "https://redacted.finance",
    description:
      "The Redacted ecosystem is a product suite of smart contracts empowering on-chain liquidity, governance, and cash flow for DeFi protocols.",
    logo: `${baseIconsUrl}/redacted.png`,
    gecko_id: "redacted",
    cmcId: "21324",
    chains: [],
    twitter: "redactedcartel",
    governanceID: ["snapshot:redactedcartel.eth"]
  },
  {
    id: "parent#tomb-finance",
    name: "Tomb Finance",
    url: "https://tomb.finance/",
    description:
      "home to the first algorithmic token pegged to $FTM on the Fantom Opera network",
    logo: `${baseIconsUrl}/tomb-finance.jpg`,
    gecko_id: "tomb",
    cmcId: "11495",
    chains: [],
    twitter: "tombfinance",
    governanceID: ["snapshot:tombfinance.eth"]
  },
  {
    id: "parent#volt-finance",
    name: "Volt Finance",
    url: "https://voltswap.finance",
    description:
      "VoltSwap is the first major DEX in the Meter ecosystem",
    logo: `${baseIconsUrl}/volt finance.png`,
    gecko_id: "voltswap",
    cmcId: "19160",
    chains: [],
    twitter: "Meter_IO",
    governanceID: ["snapshot:voltswap.eth"]
  },
  {
    id: "parent#based-finance",
    name: "Based Finance",
    url: "https://next-gen.basedfinance.io/",
    description:
      "An innovative fork of tomb.finance, pegged to the price of 1 TOMB via seigniorage.",
    logo: `${baseIconsUrl}/based finance.png`,
    gecko_id: "based-finance",
    cmcId: "17954",
    chains: [],
    twitter: "BasedDEFI",
  },
  {
    id: "parent#ribbon-finance",
    name: "Ribbon Finance",
    url: "https://www.ribbon.finance/",
    description:
      "Structured products protocol",
    logo: `${baseIconsUrl}/ribbon-finance.png`,
    gecko_id: "ribbon-finance",
    cmcId: "12387",
    chains: [],
    twitter: "ribbonfinance",
    governanceID: ["snapshot:rbn.eth", "snapshot:gauge.rbn.eth"]
  },
  {
    id: "parent#planet",
    name: "Planet",
    url: "https://app.planet.finance/",
    description:
      "Planet is a decentralized financial protocol consisting of different planets, each their own application, designed to enable anyone to freely activate their capital.",
    logo: `${baseIconsUrl}/planet.png`,
    gecko_id: "planet-finance",
    cmcId: "10023",
    chains: [],
    twitter: "planet_finance",
    governanceID: ["snapshot:planetfinance.eth"]
  },
  {
    id: "parent#dao-maker",
    name: "DAO Maker",
    url: "https://daomaker.com/",
    description:
      "DAO Maker creates growth technologies and funding frameworks for startups, while simultaneously reducing risks for investors.",
    logo: `${baseIconsUrl}/dao-maker.jpg`,
    gecko_id: "dao-maker",
    cmcId: "8420",
    chains: [],
    twitter: "daomaker",
    governanceID: ["snapshot:shomustgoon.eth"]
  },
  {
    id: "parent#morpho",
    name: "Morpho",
    url: "https://www.morpho.xyz",
    description:
      "Morpho is an on-chain peer-to-peer layer on top of lending pools. Rates are seamlessly improved for borrowers and lenders while preserving the same guarantees.",
    logo: `${baseIconsUrl}/morpho.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "MorphoLabs",
    governanceID: ["snapshot:morpho.eth"]
  },
  {
    id: "parent#quickswap",
    name: "Quickswap",
    url: "https://quickswap.exchange",
    description:
      "QuickSwap is a next-gen DEX and Lending for DeFi.",
    logo: `${baseIconsUrl}/quickswap.jpg`,
    gecko_id: "quickswap",
    cmcId: "19966",
    chains: [],
    twitter: "QuickswapDEX",
    governanceID: ["snapshot:quickvote.eth"]
  },
  {
    id: "parent#izumi-finance",
    name: "iZUMi Finance",
    url: "https://izumi.finance/home",
    description:
      "Liquidity Redefined - A multi-chain DeFi protocol providing One-Stop Liquidity as a Service (LaaS).",
    logo: `${baseIconsUrl}/izumi finance.png`,
    gecko_id: "izumi-finance",
    cmcId: "16305",
    chains: [],
    twitter: "izumi_Finance",
    governanceID: ["snapshot:veizi.eth"]
  },
  {
    id: "parent#temple-dao",
    name: "Temple DAO",
    url: "https://www.templedao.link",
    description:
      "The TempleDAO protocol aims to provide DeFi users with a safe haven where they can be sheltered from crypto market volatility while benefiting from a set of investment opportunities offering high yields and steady price appreciation",
    logo: `${baseIconsUrl}/temple-dao.png`,
    gecko_id: "temple",
    cmcId: "16052",
    chains: [],
    twitter: "templedao",
  },
  {
    id: "parent#trader-joe",
    name: "Trader Joe",
    url: "https://www.traderjoexyz.com",
    description:
      "Trader Joe is your one-stop decentralized trading platform on the Avalanche network.",
    logo: `${baseIconsUrl}/trader-joe.png`,
    gecko_id: "joe",
    cmcId: "11396",
    chains: [],
    twitter: "traderjoe_xyz",
    governanceID: ["snapshot:joegovernance.eth"]
  },
  {
    id: "parent#handle-finance",
    name: "handle finance",
    url: "https://handle.fi",
    description:
      "the global defi FX protocol. borrow, convert & trade multi-currency #stablecoins.",
    logo: `${baseIconsUrl}/handle finance.jpg`,
    gecko_id: "handle-fi",
    cmcId: "11794",
    chains: [],
    twitter: "handle_fi",
    governanceID: ["snapshot:handlefx.eth"]
  },
  {
    id: "parent#omnidex",
    name: "Omnidex",
    url: "https://omnidex.finance",
    description:
      "OmniDex is building a comprehensive decentralized trading platform on the Telos Blockchain.",
    logo: `${baseIconsUrl}/omnidex.jpg`,
    gecko_id: "omnidex",
    cmcId: null,
    chains: [],
    twitter: "OmniDex1",
  },
  {
    id: "parent#amulet",
    name: "Amulet",
    url: "https://amulet.org",
    description:
      "Amulet has designed an innovative and open risk protection model which not only effectively addresses the common challenges of existing decentralized RPPs, but also creates a new paradigm shift for the whole risk protection sector.",
    logo: `${baseIconsUrl}/amulet.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "AmuletProtocol",
  },
  {
    id: "parent#uniswap",
    name: "Uniswap",
    url: "https://uniswap.org/",
    description:
      "Swap, earn, and build on the leading decentralized crypto trading protocol.",
    logo: `${baseIconsUrl}/uniswap.png`,
    gecko_id: "uniswap",
    cmcId: "7083",
    chains: [],
    twitter: "Uniswap",
    governanceID: [
      "snapshot:uniswap", 
      "compound:ethereum:0x408ed6354d4973f66138c91495f2f2fcbd8724c3",
      "compound:ethereum:0x5e4be8bc9637f0eaa1a755019e06a68ce081d58f"
    ]
  },
  {
    id: "parent#tetu",
    name: "Tetu",
    url: "http://tetu.io",
    description:
      "Tetu is a decentralized organization committed to providing a next generation yield aggregator to DeFi investors. The Tetu core team has deep industry knowledge building back-end international banking systems and development with leading global payment processing infrastructure.",
    logo: `${baseIconsUrl}/tetu.svg`,
    gecko_id: "tetu",
    cmcId: "12452",
    chains: [],
    twitter: "tetu_io",
    governanceID: ["snapshot:tetu.eth"]
  },
  {
    id: "parent#pando",
    name: "Pando",
    url: "https://pando.im",
    description:
      "Pando is a set of open financial protocols which includes 3 major protocols: 1.Pando Lake/4swap: a decentralized protocol for automated liquidity provision built with the Mixin Trusted Group. 2.Pando Leaf: a decentralized financial network to minting stablecoins. 3.Pando Rings: a decentralized protocol where you can lend or borrow cryptocurrencies",
    logo: `${baseIconsUrl}/pando.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "pando_im",
  },
  {
    id: "parent#meteora",
    name: "Meteora",
    url: "https://meteora.ag/",
    description:
      "Building the most secure, sustainable & composable yield layer for all of Solana and DeFi",
    logo: `${baseIconsUrl}/meteora.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "MeteoraAG",
  },
  {
    id: "parent#folks-finance",
    name: "Folks Finance",
    url: "https://folks.finance/",
    description:
    "Lending and borrowing protocol with innovative features and Liquid Staking built on Algorand Blockchain.",
    logo: `${baseIconsUrl}/folks-finance.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "FolksFinance",
  },
  {
    id: "parent#yield-yak",
    name: "Yield Yak",
    url: "https://yieldyak.com",
    description:
    "Yield Yak provides tools for DeFi users on Avalanche. Discover a huge selection of autocompounding farms and make your life easier.",
    logo: `${baseIconsUrl}/yield yak.png`,
    gecko_id: "yield-yak",
    cmcId: "11415",
    chains: [],
    twitter: "yieldyak_",
    governanceID: ["snapshot:yakherd.eth"]
  },
  {
    id: "parent#animal-farm",
    name: "Animal Farm",
    url: "https://animalfarm.app",
    description:
    "Our vision is to make traditional finance tools, typically only reserved for the super wealthy, available to the anyone by using decentralized protocols which are not limited by the gatekeeping of centralized institutions. All of our products utilize trustless models that allow users to take full ownership of their personal finances. Lending and yield aggregating is the main focus of Animal Farm, but unlike other platforms Animal Farm is the only true decentralized ownership lending and yield aggregating platform.",
    logo: `${baseIconsUrl}/animal farm.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "DRIPcommunity",
    governanceID: ["snapshot:theanimalfarm.eth"]
  },
  {
    id: "parent#metavault",
    name: "Metavault",
    url: "https://metavault.org/",
    description:
    "Metavault is a blockchain-based, community governed investment platform and decentralized venture capital fund. It allows anyone to participate in the latest and most profitable DeFi projects and strategies and deploys a in-house development team for project incubation.",
    logo: `${baseIconsUrl}/metavault.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "MetavaultDAO",
    governanceID: ["snapshot:metavault-trade.eth", "snapshot:metavault-dao.eth"]
  },
  /*
  {
    id: "MUX Protocol",
    name: "MUX Protocol",
    url: "https://mux.network/",
    description:
    "MUX (Previously MCDEX),The first Multi-Chain native leveraged trading protocol,\r\nallowing zero price impact trading, up to 100x leverage, no counterparty risks for traders and an optimized on-chain trading experience",
    logo: `${baseIconsUrl}/mux protocol.png`,
    gecko_id: "mcdex",
    cmcId: "5956",
    chains: [],
    twitter: "muxprotocol",
    governanceID: ["snapshot:muxvote.eth"]
  },
  */
  {
    id: "parent#woofi",
    name: "WOOFi",
    url: "https://fi.woo.org",
    description:
    "One DEX to rule all chains  - trade and earn like royalty with unmatched execution, cross-chain swaps, and single-sided yields.",
    logo: `${baseIconsUrl}/woofi.png`,
    gecko_id: "woo-network",
    cmcId: "7501",
    chains: [],
    twitter: "_WOOFi",
  },
  {
    id: "parent#revert",
    name: "Revert",
    url: "https://revert.finance",
    description:
    "Actionable analytics for AMM liquidity providers.",
    logo: `${baseIconsUrl}/revert.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "revertfinance",
  },
  {
    id: "parent#polycat-finance",
    name: "Polycat Finance",
    url: "https://polycat.finance",
    description:
    "Polycat is a decentralized hybrid yield optimizer (yield farm and yield aggregator) running on the Polygon blockchain (formerly known as MATIC). The Paw token is the second token in their ecosystem that they introduced with the launch of their AMM.",
    logo: `${baseIconsUrl}/polycat finance.jpg`,
    gecko_id: "polycat-finance",
    cmcId: "10134",
    chains: [],
    twitter: "PolycatFinance",
    governanceID: ["snapshot:polycatfi.eth"]
  },
  {
    id: "parent#mstable",
    name: "mStable",
    url: "https://mstable.org/",
    description:
    "mStable unites stablecoins, lending and swapping into one standard.",
    logo: `${baseIconsUrl}/mstable.png`,
    gecko_id: "meta",
    cmcId: "5748",
    chains: [],
    twitter: "mstable_",
    governanceID: ["snapshot:mstablegovernance.eth"]
  },
  {
    id: "parent#realt",
    name: "RealT",
    url: "https://realt.co",
    description:
    "RealToken provides investors with a method to buy into fractional, tokenized properties, leveraging the U.S. legal system and the permissionless, unrestricted token issuance of Ethereum",
    logo: `${baseIconsUrl}/realt.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "RealTPlatform",
  },
  {
    id: "parent#neopin",
    name: "NEOPIN",
    url: "https://neopin.io",
    description:
    "NEOPIN is a one-stop, non-custodial CeDeFi protocol for the secure use of crypto with regulatory frameworks while leveraging the benefits of both CeFi and DeFi.",
    logo: `${baseIconsUrl}/neopin.png`,
    gecko_id: "neopin",
    cmcId: "18966",
    chains: [],
    twitter: "NeopinOfficial",
  },
  {
    id: "parent#sperax",
    name: "Sperax",
    url: "http://sperax.io",
    description:
    "SperaxUSD (USDs) is a stablecoin and yield-automator on Arbitrum. USDs is 100% backed by collateral that is sent to DeFi strategies to produce a yield. This yield is then distributed to holders in a gasless manner, making compound interest easy",
    logo: `${baseIconsUrl}/sperax.png`,
    gecko_id: "sperax",
    cmcId: "6715",
    chains: [],
    twitter: "SperaxUSD",
    governanceID: ["snapshot:speraxdao.eth"]
  },
  {
    id: "parent#opyn",
    name: "Opyn",
    url: "https://www.opyn.co",
    description:
    "Opyn is building Defi-native derivatives and options infrastructure in DeFi",
    logo: `${baseIconsUrl}/opyn.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "opyn_",
  },
  {
    id: "parent#nest-protocol",
    name: "NEST Protocol",
    url: "https://nestprotocol.org",
    description:
    "The NEST oracle solves the problem of price on-chain through a decentralized incentive solution, that is, the price predictor.",
    logo: `${baseIconsUrl}/nest-protocol.png`,
    gecko_id: "nest",
    cmcId: "5841",
    chains: [],
    twitter: "nest_protocol",
    governanceID: ["snapshot:nestecosystem.eth"]
  },
  {
    id: "parent#bao-finance",
    name: "BAO Finance",
    url: "https://app.bao.finance",
    description:
    "Bao Finance is a decentralized, community-run project that uses synthetics to move the power of information from institutions to individuals",
    logo: `${baseIconsUrl}/bao finance.jpg`,
    gecko_id: "bao-finance-v2",
    cmcId: null,
    chains: [],
    twitter: "BaoFinance",
    governanceID: ["snapshot:pandaswapbsc.eth", "snapshot:baovotes.eth"]
  },
  {
    id: "parent#uniwswap",
    name: "UniWswap",
    url: "https://uniwswap.com/",
    description:
    "UniWswap is an AMM and Farm on EthereumPoW",
    logo: `${baseIconsUrl}/uniwswap.png`,
    gecko_id: "uniwswap",
    cmcId: null,
    chains: [],
    twitter: "uniwswap",
  },
  {
    id: "parent#metronome",
    name: "Metronome",
    url: "https://www.metronome.io/",
    description:
    "Synthesizing the future of DeFi.",
    logo: `${baseIconsUrl}/metronome.png`,
    gecko_id: "metronome",
    cmcId: "2873",
    chains: [],
    twitter: "MetronomeDAO",
    governanceID: ["snapshot:metronome.eth", "compound:ethereum:0xc8697de7c190244bfd63d276823aa20035cb5a12"]
  },
  {
    id: "parent#paraluni",
    name: "Paraluni",
    url: "https://paraluni.org",
    description:
    "Paraluni,based on the BSC,a no holding currency, no ICO, no pre-mining decentralized platform.",
    logo: `${baseIconsUrl}/paraluni.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "paraluni",
  },
  {
    id: "parent#waterfall-finance",
    name: "Waterfall Finance",
    url: "https://wtf.defiwaterfall.com",
    description:
    "An innovative eco-system",
    logo: `${baseIconsUrl}/waterfall-wtf.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "defi_waterfall",
    governanceID: ["snapshot:waterfalldao.eth"]
  },
  {
    id: "parent#inverse-finance",
    name: "Inverse Finance",
    url: "https://www.inverse.finance",
    description:
    "DOLA Borrowing Rights replace interest rates with a fixed fee that can earn you more.",
    logo: `${baseIconsUrl}/inverse-finance.jpg`,
    gecko_id: "inverse-finance",
    cmcId: "8720",
    chains: [],
    governanceID: ["compound:ethereum:0x35d9f4953748b318f18c30634ba299b237eedfff"],
    twitter: "InverseFinance",
  },
  {
    id: "parent#kujira-protocol",
    name: "Kujira Protocol",
    url: "https://kujira.app",
    description:
    "A decentralized ecosystem for protocols, builders and web3 users seeking sustainable FinTech.",
    logo: `${baseIconsUrl}/kujira-protocol.png`,
    gecko_id: "kujira",
    cmcId: "15185",
    chains: [],
    twitter: "TeamKujira",
  },
  {
    id: "parent#steakhut-finance",
    name: "Steakhut Finance",
    url: "https://www.steakhut.finance",
    description:
    "Discover endless DeFi opportunities, join the liquidity layer of Avalanche.",
    logo: `${baseIconsUrl}/steakhut-finance.png`,
    gecko_id: "steakhut-finance",
    cmcId: "20266",
    chains: [],
    twitter: "steakhut_fi",
  },
  {
    id: "parent#mahadao",
    name: "MahaDAO",
    url: "https://mahadao.com",
    description:
    "MahaDAO is a community focused DAO focused on building ARTH, a decentralized valuecoin that maintains the purchasing power of it's token. It is designed to appreciate against the US dollar (after accounting for inflation) in the long run whilst remaining relatively stable in the short run.",
    logo: `${baseIconsUrl}/mahadao.png`,
    gecko_id: "mahadao",
    cmcId: "8043",
    chains: [],
    twitter: "TheMahaDAO",
    governanceID: ["snapshot:maha.eth"]
  },
  {
    id: "parent#tethys-finance",
    name: "Tethys Finance",
    url: "https://tethys.finance",
    description:
    "We believe that in the future, L2 solutions will help Ethereum with scaling. Our mission is to empower the Metis Andromeda network with a fast, secure, reliable, and advanced native decentralized exchange app to handle all kinds of trading needs.",
    logo: `${baseIconsUrl}/tethys-finance.png`,
    gecko_id: "tethys-finance",
    cmcId: "16640",
    chains: [],
    twitter: "tethysfinance",
    governanceID: ["snapshot:tethysswap.eth"]
  },
  {
    id: "parent#timeless",
    name: "Timeless",
    url: "https://timelessfi.com",
    description:
    "Timeless is powered by yield tokens, specially designed ERC-20 tokens whose values are related to yield rates. Each farm corresponds to a set of three yield tokens.",
    logo: `${baseIconsUrl}/timeless.jpg`,
    gecko_id: "timeless",
    cmcId: "23236",
    chains: [],
    twitter: "Timeless_Fi",
    governanceID: ["snapshot:timelessfi.eth"]
  },
  {
    id: "parent#cap-finance",
    name: "Cap Finance",
    url: "https://www.cap.io",
    description:
    "Decentralized Perps. Trade with up to 100x leverage directly from your wallet. ",
    logo: `${baseIconsUrl}/cap-finance.jpg`,
    gecko_id: "cap",
    cmcId: "5809",
    chains: [],
    twitter: "CapDotFinance",
  },
  {
    id: "parent#sphere",
    name: "SPHERE",
    url: "https://www.sphere.finance",
    description:
    "The center of DeFi - earn revenue from multiple innovative streams by holding one token.",
    logo: `${baseIconsUrl}/sphere.jpg`,
    gecko_id: "sphere-finance",
    cmcId: "18945",
    chains: [],
    twitter: "SphereDeFi",
    governanceID: ["snapshot:spherefinance.eth"]
  },
  {
    id: "parent#pancakeswap",
    name: "PancakeSwap",
    url: "https://pancakeswap.finance",
    description:
    "Trade. Earn. Win. NFT.",
    logo: `${baseIconsUrl}/pancakeswap.jpg`,
    gecko_id: "pancakeswap-token",
    cmcId: "1165",
    chains: [],
    twitter: "PancakeSwap",
    governanceID: ["snapshot:cakevote.eth"]
  },
  {
    id: "parent#zyberswap",
    name: "ZyberSwap",
    url: "https://www.zyberswap.io",
    description:
    "Zyberswap is one of the first decentralized exchanges (DEX) with an automated market-maker (AMM) on the Arbitrum blockchain. ",
    logo: `${baseIconsUrl}/zyberswap.jpg`,
    gecko_id: "zyberswap",
    cmcId: "23419",
    chains: [],
    twitter: "zyberswap",
    governanceID: ["snapshot:zyberswap.eth"]
  },
  {
    id: "parent#scrub-money",
    name: "Scrub Money",
    url: "https://scrub.money",
    description:
    "Decentralized commerce and services ecosystem",
    logo: `${baseIconsUrl}/scrub-money.png`,
    gecko_id: "lion-scrub-finance",
    cmcId: "19410",
    chains: [],
    twitter: "ScrubFinance",
  },
  {
    id: "parent#bank-of-cronos",
    name: "Bank Of Cronos",
    url: "https://boc.bankofcronos.com",
    description:
    "BOC is a community-owned decentralized autonomous organization introducing DeFi protocols on the Cronos network. DeFi Simplified, on Cronos.",
    logo: `${baseIconsUrl}/bank-of-cronos.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "bankofcronos",
  },
  {
    id: "parent#benddao",
    name: "BendDAO",
    url: "https://www.benddao.xyz",
    description:
    "Use your NFTs as collateral to borrow ETH or deposit your ETH and earn yields instantly.",
    logo: `${baseIconsUrl}/benddao.png`,
    gecko_id: "benddao",
    cmcId: "19162",
    chains: [],
    twitter: "BendDAO",
    governanceID: ["snapshot:benddao.eth"]
  },
  {
    id: "parent#subzero",
    name: "Subzero",
    url: "https://subzero.plus",
    description:
    "Subzero is a decentralized venture capital investment protocol on the Avalanche network. The protocol focuses on sustainable mechanisms to encourage long-term staking and providing liquidity.",
    logo: `${baseIconsUrl}/subzero.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "subzeroplus",
  },
  {
    id: "parent#diamond",
    name: "Diamond",
    url: "https://dmo.finance",
    description:
    "Diamond Protocol aims to be the DeFi Lab to build on-chain structured products to earn sustainable yield on crypto assets.",
    logo: `${baseIconsUrl}/diamond.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "DiamondProtocol",
  },
  {
    id: "parent#lif3.com",
    name: "Lif3.com",
    url: "https://lif3.com/",
    description:
    "Lif3.com is a complete multi-chain DeFi Ecosystem",
    logo: `${baseIconsUrl}/lif3.com.png`,
    gecko_id: "lif3",
    cmcId: "20611",
    chains: [],
    twitter: "Official_LIF3",
  },
  {
    id: "parent#timeswap",
    name: "Timeswap",
    url: "https://timeswap.io",
    description:
    "Timeswap is a fixed time preference protocol for users to manage their ERC20 tokens over discrete time. It works as a zero liquidation money market and options market in one.",
    logo: `${baseIconsUrl}/timeswap.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "TimeswapLabs",
  },
  {
    id: "parent#moonwell",
    name: "Moonwell",
    url: "https://moonwell.fi/",
    description:
    "Moonwell is an open lending and borrowing DeFi protocol on Moonbeam & Moonriver",
    logo: `${baseIconsUrl}/moonwell-artemis.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "LunarTechFdn",
  },
  {
    id: "parent#beamswap",
    name: "BeamSwap",
    url: "https://beamswap.io",
    description:
    "Defi Hub on Moonbeam",
    logo: `${baseIconsUrl}/beamswap.jpg`,
    gecko_id: "beamswap",
    cmcId: "17035",
    chains: [],
    twitter: "Beamswapio",
  },
  {
    id: "parent#surfswap",
    name: "Surfswap",
    url: "https://surfdex.io/",
    description:
    "Community DEX on Kava. One-stop shop for the crypto community, enabling peer-to-peer transactions.",
    logo: `${baseIconsUrl}/surfswap.jpg`,
    gecko_id: "surfswap",
    cmcId: null,
    chains: [],
    twitter: "SurfswapDEX",
  },
  {
    id: "parent#balancer",
    name: "Balancer",
    url: "https://balancer.fi",
    description:
    "Balancer is a decentralized automated market maker (AMM) protocol built on Ethereum that represents a flexible building block for programmable liquidity.",
    logo: `${baseIconsUrl}/balancer.png`,
    gecko_id: "balancer",
    cmcId: "5728",
    chains: [],
    twitter: "Balancer",
    governanceID: ["snapshot:balancer.eth"]
  },
  {
    id: "parent#kyberswap",
    name: "KyberSwap",
    url: "https://kyberswap.com",
    description:
    "Multichain DEX & aggregator on 14 chains. KyberSwap is both a decentralized exchange (DEX) aggregator and a liquidity source with capital-efficient liquidity pools that earns fees for liquidity providers.",
    logo: `${baseIconsUrl}/kyberswap.png`,
    gecko_id: "kyber-network-crystal",
    cmcId: "9444",
    chains: [],
    twitter: "KyberNetwork",
  },
  {
    id: "parent#opensea",
    name: "OpenSea",
    url: "https://opensea.io/",
    description: "OpenSea is the world's first and largest web3 marketplace for NFTs and crypto collectibles.",
    logo: `${baseIconsUrl}/opensea.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "opensea",
  },
  {
    id: "parent#ruby.exchange",
    name: "Ruby.Exchange",
    url: "https://ruby.exchange",
    description: "Gasless, NFT-powered AMM/Dual DEX on the SKALE Network",
    logo: `${baseIconsUrl}/ruby.exchange.jpg`,
    gecko_id: "ruby",
    cmcId: null,
    chains: [],
    twitter: "ruby_exchange",
  },
  {
    id: "parent#skullswap",
    name: "SkullSwap",
    url: "https://www.skullswap.exchange",
    description: "SkullSwap is an automated market-making (AMM) decentralized exchange (DEX) for the Fantom Opera network. ",
    logo: `${baseIconsUrl}/skullswap.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "skullswapdex",
  },
  {
    id: "parent#rocifi",
    name: "RociFi",
    url: "https://roci.fi",
    description: "RociFi - On-chain Credit Scoring and Capital-Efficient Lending Protocol",
    logo: `${baseIconsUrl}/rocifi.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "rocifi",
  },
  {
    id: "parent#lfgswap",
    name: "LFGSwap",
    url: "https://app.lfgswap.finance/swap",
    description: "AMM DEX on EthereumPoW and CORE blockchain",
    logo: `${baseIconsUrl}/lfgswap.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "LfgSwap",
  },
  {
    id: "parent#oswap",
    name: "Oswap",
    url: "https://oswap.io",
    description: "A fully decentralized protocol for automated liquidity provision on Obyte.",
    logo: `${baseIconsUrl}/oswap.jpg`,
    gecko_id: "byteball",
    cmcId: "1492",
    chains: [],
    twitter: "ObyteOrg",
  },
  {
    id: "parent#paraspace",
    name: "ParaSpace",
    url: "https://para.space",
    description: "ParaSpace is a permissionless universal, cross-margin NFT lending protocol that enables users to collateralize both ERC-721 and ERC-20 assets into a single portfolio to borrow against.",
    logo: `${baseIconsUrl}/paraspace.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "ParaSpace_NFT",
  },
  {
    id: "parent#alpaca-finance",
    name: "Alpaca Finance",
    url: "https://www.alpacafinance.org",
    description: "Alpaca Finance is the largest lending protocol allowing leveraged yield farming on BNB Chain and Fantom. It helps lenders earn safe and stable yields, and offers borrowers undercollateralized loans for leveraged yield farming positions, vastly multiplying their farming principals and resulting profits.",
    logo: `${baseIconsUrl}/alpaca-finance.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "AlpacaFinance",
    governanceID: ["snapshot:alpacafinance.eth"]
  },
  {
    id: "parent#spin",
    name: "Spin",
    url: "https://spin.fi",
    description: "Spin is a 360° decentralized trading and investments platform built on NEAR Protocol. Spin offers a wide range of products designed to meet the demands of both novice and savvy traders, DeFi investors, and passive income seekers.",
    logo: `${baseIconsUrl}/spin.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "spin_fi",
  },
  /*
  {
    id: "Morphex",
    name: "Morphex",
    url: "https://www.morphex.trade",
    description: "Trade cryptocurrencies on Fantom with up to 30x leverage directly from your wallet",
    logo: `${baseIconsUrl}/spin.png`,
    gecko_id: "mpx",
    cmcId: "23431",
    chains: [],
    twitter: "MorphexFTM",
  },
  */
  {
    id: "parent#arrakis-finance",
    name: "Arrakis Finance",
    url: "https://www.arrakis.finance",
    description: "Arrakis is web3's trustless market making infrastructure protocol that enables running sophisticated algorithmic strategies on Uniswap V3. Liquidity providers can utilize Arrakis Vaults to have their liquidity be managed in an automated, capital efficient, non-custodial and transparent manner. ",
    logo: `${baseIconsUrl}/arrakis-finance.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "ArrakisFinance",
  },
  {
    id: "parent#enosys",
    name: "Enosys",
    url: "https://enosys.global",
    description: "Formerly FLR Finance. Building a Multi-Chain DeFi Economy. From the creators of @FlareScan and @DeFiOracles",
    logo: `${baseIconsUrl}/enosys.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "enosys_global",
  },
  {
    id: "parent#velocimeter",
    name: "Velocimeter",
    url: "https://canto.velocimeter.xyz/",
    description: "Velocimeter's twin-AMM design unites StableSwap pools with Standard 'kxy' liquidity pools. All the trading fees go to Vote-Escrowers of emission token $FLOW which has to be Locked to earn triple 'Bribes' from candidate pools via Trade Fee, Internal Bribes & External Bribes",
    logo: `${baseIconsUrl}/velocimeter.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "VelocimeterDEX",
  },
  {
    id: "parent#kleva-protocol",
    name: "Kleva Protocol",
    url: "https://kleva.io",
    description: "KLEVA Protocol is the first Leveraged Yield Farming Protocol on KLAYTN, with aim to become the largest Lending Protocol for Leveraged Yield Farmers and Lenders.",
    logo: `${baseIconsUrl}/kleva-protocol.png`,
    gecko_id: "kleva",
    cmcId: "21122",
    chains: [],
    twitter: "KLEVA_Protocol",
  },
  {
    id: "parent#wynd",
    name: "WYND",
    url: "https://app.wynddao.com",
    description: "WYND is a new ReFi protocol to leverage DeFi tokenomics to regenerate the environment.",
    logo: `${baseIconsUrl}/wynd.jpg`,
    gecko_id: "wynd",
    cmcId: null,
    chains: [],
    twitter: "wynddao",
  },
  {
    id: "parent#overnight-finance",
    name: "Overnight Finance",
    url: "https://overnight.fi",
    description: "Overnight Finance is an asset management protocol offering passive yield products based on delta-neutral strategies, primarily for conservative stablecoin investors.",
    logo: `${baseIconsUrl}/overnight-finance.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "overnight_fi",
  },
  {
    id: "parent#fairyswap",
    name: "FairySwap",
    url: "https://fairyswap.finance",
    description: "The first DAPP on Findora, offering unparalleled privacy and security with zero-knowledge technology.",
    logo: `${baseIconsUrl}/fairyswap.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "fairy_swap",
  },
  {
    id: "parent#wemix.fi",
    name: "WEMIX.FI",
    url: "https://wemix.fi",
    description: "WEMIX.Fi is the first decentralized exchange on the WEMIX3.0 mainnet. WEMIX.Fi is a fully on-chain DeFi platform supporting storage, exchange, borrowing, settlement and investment of crypto-assets.",
    logo: `${baseIconsUrl}/wemix.fi.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "WemixNetwork",
  },
  {
    id: "parent#radiant",
    name: "Radiant",
    url: "https://radiant.capital/#/markets",
    description: "Earn Interest & Borrow Assets Cross-Chain, Seamlessly",
    logo: `${baseIconsUrl}/radiant.png`,
    gecko_id: "radiant-capital",
    cmcId: "21106",
    chains: [],
    twitter: "RDNTCapital",
    governanceID: ["snapshot:radiantcapital.eth"],
  },
  {
    id: "parent#puzzleswaporg",
    name: "PuzzleSwapOrg",
    url: "https://puzzleswap.org/trade",
    description: "DEX 2.0 & Lending protocol built on Waves to bring a new light to DeFi experience",
    logo: `${baseIconsUrl}/puzzle-swap.jpg`,
    gecko_id: "puzzle-swap",
    cmcId: null,
    chains: [],
    twitter: "puzzle_swap"
  },
  {
    id: "parent#covo-finance",
    name: "Covo Finance",
    url: "https://covo.finance",
    description: "Covo Finance is a decentralized trading platform that offers spot and perpetual trading with low swap fees and zero market impact. The platform offers a maximum leverage of 50x on major cryptos and is backed by a singular multi-asset pool that generates income for liquidity providers through fees garnered from market making, swap transactions, leveraged trading (including spreads, funding fees, and liquidations), and rebalancing of assets.",
    logo: `${baseIconsUrl}/covo-finance.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "covofinance"
  },
  {
    id: "parent#hadouken-finance",
    name: "Hadouken Finance",
    url: "https://covo.finance",
    description: "An integrated borrowing/lending platform and AMM on Godwoken V1 Network.",
    logo: `${baseIconsUrl}/hadouken-finance.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "HadoukenFinance"
  },
  /*
  {
    id: "parent#synthetix",
    name: "Synthetix",
    url: "https://synthetix.io",
    description: "Synthetix is a derivatives liquidity protocol providing the backbone for derivatives trading in DeFi.",
    logo: `${baseIconsUrl}/synthetix.png`,
    gecko_id: "havven",
    cmcId: "2586",
    chains: [],
    twitter: "synthetix_io",
    governanceID: ["snapshot:synthetix-stakers-poll.eth"]
  },
  */
  {
    id: "parent#starfish",
    name: "Starfish",
    url: "https://app.starfish.finance",
    description: "Leading the Entertainment-Fi experience in Web3",
    logo: `${baseIconsUrl}/starfish.jpg`,
    gecko_id: "starfish-finance",
    cmcId: "22002",
    chains: [],
    twitter: "Starfish_Fi"
  },
  {
    id: "parent#hector-network",
    name: "Hector Network",
    url: "https://hector.network",
    description: "Hector Network is an expansive decentralized ecosystem run by a utility token, HEC, and complemented by the TOR stablecoin.",
    logo: `${baseIconsUrl}/hector-network.png`,
    gecko_id: "hector-dao",
    cmcId: "13881",
    chains: [],
    twitter: "Hector_Network",
    governanceID: ["snapshot:hectordao.eth"]
  },
  {
    id: "parent#zenlink",
    name: "Zenlink",
    url: "https://zenlink.pro",
    description: "An ultimate, open, and universal cross-chain DEX protocol for building DEX on Polkadot with one click. Make DEX easier, for more people.",
    logo: `${baseIconsUrl}/zenlink.png`,
    gecko_id: "zenlink-network-token",
    cmcId: "15419",
    chains: [],
    twitter: "ZenlinkPro",
  },
  {
    id: "parent#camelot",
    name: "Camelot",
    url: "https://camelot.exchange/",
    description: "Camelot is an ecosystem-focused and community-driven DEX built on Arbitrum. It has been built as a highly efficient and customizable protocol, allowing both builders and users to leverage our custom infrastructure for deep, sustainable, and adaptable liquidity. Camelot moves beyond the traditional design of DEXs to focus on offering a tailored approach that prioritises composability",
    logo: `${baseIconsUrl}/camelot.png`,
    gecko_id: "camelot-token",
    cmcId: "22949",
    chains: [],
    twitter: "CamelotDEX",
  },
  {
    id: "parent#thala-labs",
    name: "Thala Labs",
    url: "https://www.thala.fi/",
    description: "Thala is a decentralized finance protocol powered by the Move language, enabling seamless borrowing of a decentralized, over-collateralized stablecoin in Move Dollar and capital-efficient liquidity provisioning via a rebalancing AMM on the Aptos blockchain",
    logo: `${baseIconsUrl}/thala-labs.png`,
    gecko_id: "thala",
    cmcId: "24268",
    chains: [],
    twitter: "ThalaLabs",
  },
  {
    id: "parent#stake.link",
    name: "stake.link",
    url: "https://stake.link",
    description: "stake.link is a diversified liquid staking protocol powered by fifteen of the most experienced and reliable infrastructure providers in Web3",
    logo: `${baseIconsUrl}/stake.link.png`,
    gecko_id: "stake-link",
    cmcId: "22906",
    chains: [],
    twitter: "stakedotlink",
    governanceID: ["snapshot:stakedotlink.eth"]
  },
  {
    id: "parent#dove-swap",
    name: "Dove Swap",
    url: "https://swap.dovish.finance",
    description: "Bringing innovative DeFi to the zkEVM space.",
    logo: `${baseIconsUrl}/dove-swap.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "DovishFi",
  },
  {
    id: "parent#forge-sx",
    name: "Forge SX",
    url: "https://forge.sx",
    description: "Forge is a brand new DeFi protocol enabling anyone to mint & trade real-world assets with the convenience of the blockchain",
    logo: `${baseIconsUrl}/forge-sx.jpg`,
    gecko_id: "forge",
    cmcId: null,
    chains: [],
    twitter: "forge_sx",
  },
  {
    id: "parent#juicebox",
    name: "Juicebox",
    url: "https://juicebox.money/",
    description: "The programmable crypto fundraising protocol for builders and creators. Light enough for a group of friends, powerful enough for a global network of anons. Community-owned, on Ethereum",
    logo: `${baseIconsUrl}/juicebox.png`,
    gecko_id: "juicebox",
    cmcId: "15456",
    chains: [],
    twitter: "juiceboxETH",
  },
  {
    id: "parent#sovryn",
    name: "Sovryn",
    url: "https://sovryn.com/",
    description: "Sovryn is a non-custodial and permission-less smart contract based system for bitcoin lending, borrowing and margin trading.",
    logo: `${baseIconsUrl}/sovryn.png`,
    gecko_id: "sovryn",
    cmcId: "8669",
    chains: [],
    twitter: "SovrynBTC",
  },
  {
    id: "parent#polynomial-protocol",
    name: "Polynomial Protocol",
    url: "https://www.polynomial.fi",
    description: "Polynomial automates financial derivative strategies to create products that deliver passive yield on various assets",
    logo: `${baseIconsUrl}/polynominal-finance.png`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "PolynomialFi",
  },
  {
    id: "parent#arbswap",
    name: "Arbswap",
    url: "https://arbswap.io",
    description: "Arbswap is the only true Arbitrum-native DEX suite, offering the best Game-fi services on Nova and the smoothest trading experience on One.",
    logo: `${baseIconsUrl}/arbswap.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "ArbswapOfficial",
  },
  {
    id: "parent#maia-dao-ecosystem",
    name: "Maia DAO Ecosystem",
    url: "https://maiadao.io",
    description: "MAIA is the first decentralized community-owned reserve currency in Metis Andromeda.",
    logo: `${baseIconsUrl}/maia-dao-ecosystem.jpg`,
    gecko_id: null,
    cmcId: null,
    chains: [],
    twitter: "MaiaDAOEco",
  },
  {
    id: "parent#thena",
    name: "THENA",
    url: "https://www.thena.fi",
    description: "THENA is a native liquidity layer & AMM on BNB Chain",
    logo: `${baseIconsUrl}/thena.png`,
    gecko_id: "thena",
    cmcId: "23335",
    chains: [],
    twitter: "ThenaFi_",
  },
];

export default parentProtocols;
