export default {
  aave: require("./aave"),
  apecoin: require("./apecoin"),
  aptos: require("./aptos"),
  // aura: require("./aura"),
  // convex: require("./convex"),
  curve: require("./curve"),
  dydx: require("./dydx"),
  // euler: require("./euler"),
  forta: require("./forta"),
  sushi: require("./sushi"),
  tornado: require("./tornado"),
  uniswap: require("./uniswap"),
  yearn: require("./yearn"),
};
