export default {
  aave: require("./aave"),
  apecoin: require("./apecoin"),
  aptos: require("./aptos"),
  // aura: require("./aura"),
  benddao: require("./benddao"),
  blur: require("./blur"),
  canto: require("./canto"),
  convex: require("./convex"),
  curve: require("./curve"),
  dydx: require("./dydx"),
  euler: require("./euler"),
  forta: require("./forta"),
  gmx: require("./gmx"),
  idle: require("./idle"),
  gearbox: require("./gearbox"),
  radiant: require("./radiant"),
  rocketpool: require("./rocketpool"),
  stargate: require("./stargate"),
  sushi: require("./sushi"),
  tornado: require("./tornado"),
  uniswap: require("./uniswap"),
  velodrome: require("./velodrome"),
  yearn: require("./yearn"),
  zyberswap: require("./zyberswap"),
};
