type Characteristics = {
  symbols: string[];
  matchExact: boolean;
  redeemable: boolean;
  attestations: boolean;
  cexListed: boolean;
  kyc: boolean;
  transferable: boolean;
  selfCustody: boolean;
};

export const faultyIds: { [id: string]: string } = {
  "415": "NAOS",
  "1459": "ELYFI",
  "1667": "Solv Vesting",
  "2181": "Frigg.eco",
  "2231": "Tangible RWA",
  "2315": "Invar Finance",
  "3267": "Solid World",
  "3466": "Bloom",
  "3573": "Solv RWA",
  "3598": "Mountain Protocol",
  "5481": "Anemoy Capital",
  "4058": "Brickken",
  "4879": "Clearpool TPool",
};

// KYC is true where required for mint / redeem.
// transferable is true where transfer doesnt require KYC.
export const metadata: { [id: string]: Characteristics } = {
  "753": {
    symbols: ["REALTOKEN"], // need to match on inclusion
    matchExact: false,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false, // true but user needs pre - KYC
    selfCustody: true,
  },
  "781": {
    symbols: ["KLIMA", "kVCM"],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: true, // poloniex
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "1952": {
    symbols: [], // no open market
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "1953": {
    symbols: ["CHAR"],
    matchExact: true,
    redeemable: false,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "2002": {
    symbols: ["CGT"], // no open market
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "2482": {
    symbols: ["18SML711", "20SML025"],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "2542": {
    symbols: ["OUSG", "USDY", "USDYc", "rUSDY", "rOUSG"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: true, // bybit
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "2782": {
    symbols: [], // random tickers for each listing
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "2807": {
    symbols: ["STBT"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "2923": {
    symbols: ["TBT", "wTBT"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "2965": {
    symbols: ["GOLD$", "SILVER$"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "3057": {
    symbols: ["TBILL"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "3193": {
    symbols: ["stUSDT"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "3467": {
    symbols: ["bERNX", "bCSPX", "bCOIN", "bC3M", "bIB01", "bIBTA", "bHIGH", "bNVDA"],
    matchExact: false,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "3560": {
    symbols: ["USDP", "rUSDP"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "3580": {
    symbols: ["uMINT", "pEAK0825", "iSNR", "pEAK2", "pEAK", "HYDB1025", "DMMF01", "CMBMINT"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "3665": {
    symbols: ["sUSDS", "sDAI"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "3698": {
    symbols: ["USYC"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: true, // Deribit
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "3795": {
    symbols: ["SWEEP"],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "3831": {
    symbols: [], // no liq
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "3886": {
    symbols: ["fBILL", "fCOIN", "fHOOD", "dSPQQQ", "fHV1"],
    matchExact: false,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "3960": {
    symbols: ["xSOY", "xWHEAT", "xCORN", "xRICE"],
    matchExact: true,
    redeemable: false,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "4003": {
    symbols: ["EGK", "FRK", "USK"],
    matchExact: false,
    redeemable: false,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },

  "4196": {
    symbols: [".d"],
    matchExact: false,
    redeemable: true,
    attestations: true,
    cexListed: true, // gemini
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4265": {
    symbols: ["USCC", "USTB"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4744": {
    symbols: ["USDz", "sUSDz"],
    matchExact: true,
    redeemable: false,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "4709": {
    symbols: [],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4801": {
    symbols: ["USTB"],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "4853": {
    symbols: ["BUIDL"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4862": {
    symbols: ["PAXG"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: true, // nance, kucoin
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4863": {
    symbols: ["XAUt", "XAU₮"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: true, // huobi, bybit
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4873": {
    symbols: ["mTBILL", "mBASIS", "mBTC", "mEDGE", "mMEV", "mRe7YIELD", "mF-ONE"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "4878": {
    symbols: ["BENJI"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "4882": {
    symbols: ["USDO", "ETH0", "USD0++"],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "4980": {
    symbols: ["USTBL", "EUTBL"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },

  "5182": {
    symbols: ["FIUSD"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: false,
  },
  "5241": {
    symbols: ["WM"],
    matchExact: true,
    redeemable: false,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "5284": {
    symbols: ["nALPHA", "nBASIS", "nTBILL", "nINSTO", "nCREDIT", "nELIXIR", "nRWA"],
    matchExact: true,
    redeemable: true,
    attestations: false, //
    cexListed: false,
    kyc: false,
    transferable: false,
    selfCustody: true,
  },
  "5471": {
    symbols: ["XMMF", "XFTB", "XTBT", "XEVT", "XHYC", "XEVT", "XHYCB"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: false,
  },
  "5506": {
    symbols: ["USDtb"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: true, // Bybit earn product
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "5689": {
    symbols: ["UMA1", "BHMA1", "BHMA3", "BHMA4", "HLSPCA"],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "5855": {
    symbols: [],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "5948": {
    symbols: ["JAAA", "JTRSY", "deJAAA", "deJTRSY"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "5983": {
    symbols: [],
    matchExact: true,
    redeemable: false,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "5995": {
    symbols: ["USDO"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },

  "6516": {
    symbols: ["WTGX", "FLTTX", "WTSYX", "WTTSX", "TIPSX", "WTSTX", "WTLGX", "SPXUX", "WTSIX"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "6330": {
    symbols: ["XAUM"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: false,
    selfCustody: true,
  },
  "6378": {
    symbols: [],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: true, // kraken etc
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "6432": {
    symbols: ["ONyc"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "6535": {
    symbols: ["AID"],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "6582": {
    symbols: ["ACRED"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
  "6598": {
    symbols: ["frxUSD"],
    matchExact: true,
    redeemable: true,
    attestations: true,
    cexListed: false,
    kyc: false,
    transferable: true,
    selfCustody: true,
  },
  "6650": {
    symbols: [
      "AAPLon",
      "ABNBon",
      "ABTon",
      "ACNon",
      "ADBEon",
      "AGGon",
      "AMDon",
      "AMZNon",
      "APOon",
      "APPon",
      "ARMon",
      "ASMLon",
      "AVGOon",
      "AXPon",
      "BABAon",
      "BAon",
      "BIDUon",
      "BLKon",
      "CMGon",
      "COINon",
      "COSTon",
      "CRCLon",
      "CRMon",
      "CSCOon",
      "CVXon",
      "DASHon",
      "DISon",
      "EEMon",
      "EFAon",
      "EQIXon",
      "FIGon",
      "FUTUon",
      "GEon",
      "GMEon",
      "GOOGLon",
      "GSon",
      "HIMSon",
      "HOODon",
      "HYGon",
      "IAUon",
      "IBMon",
      "IEFAon",
      "IEMGon",
      "IJHon",
      "INTCon",
      "INTUon",
      "ITOTon",
      "IVVon",
      "IWFon",
      "IWMon",
      "IWNon",
      "JDon",
      "JPMon",
      "KOon",
      "LINon",
      "LLYon",
      "LMTon",
      "MARAon",
      "MAon",
      "MCDon",
      "MELIon",
      "METAon",
      "MRVLon",
      "MSFTon",
      "MSTRon",
      "MUon",
      "NFLXon",
      "NKEon",
      "NOWon",
      "NVDAon",
      "NVOon",
      "ORCLon",
      "PANWon",
      "PBRon",
      "PEPon",
      "PFEon",
      "PGon",
      "PLTRon",
      "PYPLon",
      "QBTSon",
      "QCOMon",
      "QQQon",
      "RDDTon",
      "RIOTon",
      "SBETon",
      "SBUXon",
      "SHOPon",
      "SLVon",
      "SMCIon",
      "SNOWon",
      "SPGIon",
      "SPOTon",
      "SPYon",
      "TIPon",
      "TLTon",
      "TMon",
      "TSLAon",
      "TSMon",
      "UBERon",
      "UNHon",
      "Von",
      "WFCon",
      "WMTon",
    ],
    matchExact: true,
    redeemable: true,
    attestations: false,
    cexListed: false,
    kyc: true,
    transferable: true,
    selfCustody: true,
  },
};
