import { z } from 'zod';

// Protocol schema for nft-volume overview responses
export const nftVolumeProtocolSchema = z.object({
  name: z.string(),
  disabled: z.boolean().optional().nullable(),
  displayName: z.string().optional().nullable(),
  module: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  logo: z.string().optional().nullable(),
  change_1d: z.union([z.number(), z.null()]).optional(),
  change_7d: z.union([z.number(), z.null()]).optional(),
  change_1m: z.union([z.number(), z.null()]).optional(),
  change_7dover7d: z.union([z.number(), z.null()]).optional(),
  change_30dover30d: z.union([z.number(), z.null()]).optional(),
  total24h: z.union([z.number(), z.null()]).optional(),
  total48hto24h: z.union([z.number(), z.null()]).optional(),
  total7d: z.union([z.number(), z.null()]).optional(),
  total14dto7d: z.union([z.number(), z.null()]).optional(),
  total30d: z.union([z.number(), z.null()]).optional(),
  total60dto30d: z.union([z.number(), z.null()]).optional(),
  total1y: z.union([z.number(), z.null()]).optional(),
  totalAllTime: z.union([z.number(), z.null()]).optional(),
  total7DaysAgo: z.union([z.number(), z.null()]).optional(),
  total30DaysAgo: z.union([z.number(), z.null()]).optional(),
  chains: z.array(z.string()).optional(),
  protocolType: z.string().optional().nullable(),
  methodologyURL: z.string().optional().nullable(),
  methodology: z.union([z.string(), z.record(z.string(), z.string())]).optional().nullable(),
  latestFetchIsOk: z.boolean().optional(),
  defillamaId: z.string().optional().nullable(),
  parentProtocol: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  slug: z.string().optional().nullable(),
}).passthrough();

// Data chart point schema [timestamp, value]
export const dataChartPointSchema = z.tuple([
  z.number(),
  z.union([z.number(), z.string()]),
]);

// Overview response schema
export const nftVolumeOverviewResponseSchema = z.object({
  protocols: z.array(nftVolumeProtocolSchema).optional(),
  totalDataChart: z.array(dataChartPointSchema),
  totalDataChartBreakdown: z.array(z.array(z.any())).optional().nullable(),
  allChains: z.array(z.string()).optional(),
  chain: z.string().optional().nullable(),
  total24h: z.union([z.number(), z.null()]).optional(),
  total48hto24h: z.union([z.number(), z.null()]).optional(),
  total7d: z.union([z.number(), z.null()]).optional(),
  total14dto7d: z.union([z.number(), z.null()]).optional(),
  total30d: z.union([z.number(), z.null()]).optional(),
  total60dto30d: z.union([z.number(), z.null()]).optional(),
  total1y: z.union([z.number(), z.null()]).optional(),
  totalAllTime: z.union([z.number(), z.null()]).optional(),
  total7DaysAgo: z.union([z.number(), z.null()]).optional(),
  total30DaysAgo: z.union([z.number(), z.null()]).optional(),
  change_1d: z.union([z.number(), z.null()]).optional(),
  change_7d: z.union([z.number(), z.null()]).optional(),
  change_1m: z.union([z.number(), z.null()]).optional(),
  change_7dover7d: z.union([z.number(), z.null()]).optional(),
  change_30dover30d: z.union([z.number(), z.null()]).optional(),
}).passthrough();

// Summary protocol response schema
export const nftVolumeSummaryResponseSchema = z.object({
  id: z.string().optional().nullable(),
  name: z.string(),
  url: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  logo: z.string().optional().nullable(),
  gecko_id: z.string().optional().nullable(),
  cmcId: z.string().optional().nullable(),
  chains: z.array(z.string()).optional(),
  twitter: z.string().optional().nullable(),
  symbol: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  slug: z.string().optional().nullable(),
  module: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  methodologyURL: z.string().optional().nullable(),
  methodology: z.union([z.string(), z.record(z.string(), z.string())]).optional().nullable(),
  protocolType: z.string().optional().nullable(),
  disabled: z.boolean().optional().nullable(),
  displayName: z.string().optional().nullable(),
  latestFetchIsOk: z.boolean().optional(),
  total24h: z.union([z.number(), z.null()]).optional(),
  total48hto24h: z.union([z.number(), z.null()]).optional(),
  total7d: z.union([z.number(), z.null()]).optional(),
  total30d: z.union([z.number(), z.null()]).optional(),
  total1y: z.union([z.number(), z.null()]).optional(),
  totalAllTime: z.union([z.number(), z.null()]).optional(),
  change_1d: z.union([z.number(), z.null()]).optional(),
  change_7d: z.union([z.number(), z.null()]).optional(),
  change_1m: z.union([z.number(), z.null()]).optional(),
  change_7dover7d: z.union([z.number(), z.null()]).optional(),
  change_30dover30d: z.union([z.number(), z.null()]).optional(),
  totalDataChart: z.array(dataChartPointSchema).optional(),
  totalDataChartBreakdown: z.array(z.array(z.any())).optional().nullable(),
  chainBreakdown: z.record(z.string(), z.any()).optional().nullable(),
  parentProtocol: z.string().optional().nullable(),
}).passthrough();
